--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    -- Independent of `status` (Cold/Warm/Hot/In Contract, a note-driven
    -- temperature label). This is a durable future-sales gate: 'normal'
    -- unless an Application review sets it to 'do_not_engage' (Native
    -- Applications slice, §7), the anchor a future Kit suppression sync
    -- would read from.
    sales_eligibility text not null default 'normal',
    -- Stripe test-mode integration slice: one Stripe Customer per Contact,
    -- reused across every Deal/Checkout for them rather than creating a
    -- new one per payment attempt. Never raw card/bank data — an
    -- identifier only.
    stripe_customer_id text,
    constraint contacts_sales_eligibility_check check (sales_eligibility in ('normal', 'do_not_engage'))
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

-- A persistent product/program definition. Offers are few and change rarely
-- (Leif has exactly two today), so this is deliberately a flat table rather
-- than a versioned catalog — historical pricing integrity for Opportunities
-- already sold comes from the snapshot columns on `deals`, not from this row.
create table public.offers (
    id bigint generated by default as identity primary key,
    name text not null,
    type text not null,
    duration text not null,
    current_price numeric(10, 2) not null,
    -- Only meaningful for individual offers (e.g. The Living Example caps
    -- concurrent active clients). Group offers manage capacity per-Cohort
    -- instead, so this stays null for them.
    max_active_clients smallint,
    is_active boolean not null default true,
    -- Acuity/Sales Call Lifecycle slice: durable mapping to the Acuity
    -- appointment type whose bookings are this Offer's sales calls. For an
    -- individual Offer this is the only level a mapping can live at. A
    -- group Offer may ALSO carry one here (GYU real-infrastructure slice,
    -- sealing pass): the correct, durable home for one canonical
    -- appointment type meant to serve every Cohort of that Offer (e.g.
    -- GYU's real "Let's Meet" type — one calendar for all rounds, not one
    -- per Cohort). A specific Cohort can still override with its own
    -- mapping when a round genuinely needs a separate appointment type/
    -- calendar — see cohorts.acuity_appointment_type_id below; a Cohort-
    -- level mapping is checked second and takes precedence for its own
    -- Cohort. See sales-calls/offerCohortAcuityMapping.ts's own resolver
    -- comment for the full matching rationale (why an Offer-level match on
    -- a group Offer never needs to also identify a specific Cohort here).
    -- Stable ID, never a display-name match.
    acuity_appointment_type_id text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint offers_type_check check (type in ('individual', 'group'))
);

-- Queryable, structured payment plans for an Offer (not a prose blob), so a
-- future Stripe Checkout/payment-plan generator has real rows to read.
create table public.offer_payment_options (
    id bigint generated by default as identity primary key,
    offer_id bigint not null,
    name text not null,
    total numeric(10, 2) not null,
    installments smallint not null,
    installment_amount numeric(10, 2) not null,
    -- Some options (e.g. "Financial Need") are authorized case-by-case, not
    -- surfaced to every prospect by default.
    is_public boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- Contracts + Onboarding slice: the offer-specific onboarding requirement
-- catalog — few rows, changes rarely (same profile as offer_payment_options
-- above), so this is deliberately a plain admin-less config table, managed
-- via migration rather than a UI, not a versioned/UI-editable catalog.
-- Historical integrity for an already-created Enrollment's own checklist
-- comes from enrollment_onboarding_items snapshotting these values at
-- creation time, never from a live join back to this table — editing or
-- deactivating a template row here must never rewrite an existing
-- Enrollment's own history.
create table public.onboarding_requirement_templates (
    id bigint generated by default as identity primary key,
    offer_id bigint not null,
    -- Stable slug (e.g. 'contract', 'slack_access') — the durable identity
    -- an enrollment_onboarding_items row copies forward, never a display
    -- label match.
    key text not null,
    -- Describes the COMPLETED state ("Contract signed"), not the action
    -- ("Send contract") — the Task created from this (see handle_deal_won()
    -- below) carries the action wording separately. Keeps the checklist
    -- readable as durable fulfillment state.
    label text not null,
    -- The Task's own text when this requirement auto-creates one (only for
    -- required items — see handle_deal_won() below) — the ACTION wording
    -- ("Send contract to {name}", "Invite {name} to GYU Slack"), read once
    -- at seed time and rendered into the Task's own permanent `text`; never
    -- re-read afterward, so a later edit here only affects future
    -- Enrollments, same as label/is_required.
    task_text_template text not null,
    is_required boolean not null default true,
    sort_order smallint not null default 0,
    -- Retire a requirement without deleting it (and without touching any
    -- Enrollment that already snapshotted it) — mirrors offers.is_active.
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (offer_id, key)
);

-- A single round of a GROUP offer (e.g. a Growing Yourself Up cohort).
-- Individual offers (The Living Example) never use Cohorts.
create table public.cohorts (
    id bigint generated by default as identity primary key,
    offer_id bigint not null,
    name text not null,
    status text not null default 'draft',
    -- Date-only (not timestamptz): these are calendar dates, not moments in
    -- time, and <DateField>'s UTC-safe rendering only kicks in for bare
    -- "YYYY-MM-DD" values (see date-field.tsx).
    applications_open_at date,
    applications_close_at date,
    program_start_at date,
    program_end_at date,
    minimum_capacity smallint,
    target_capacity smallint,
    maximum_capacity smallint,
    -- Future integration identifiers (not wired up in this slice).
    slack_channel_id text,
    calendar_id text,
    -- Acuity/Sales Call Lifecycle slice: the Acuity appointment type whose
    -- bookings are this Cohort's sales calls, for the case a specific
    -- round needs its own separate appointment type/calendar rather than
    -- sharing the group Offer's canonical one (see
    -- offers.acuity_appointment_type_id above, which is where a single
    -- shared mapping for every Cohort of a group Offer belongs instead —
    -- GYU's real mapping lives there, not here, since one appointment type
    -- serves all of its rounds). Stable ID mapping, never a display-name
    -- match.
    acuity_appointment_type_id text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint cohorts_status_check check (status in ('draft', 'applications_open', 'applications_closed', 'active', 'completed'))
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_id bigint,
    category text,
    offer_id bigint not null,
    -- Only set when offer_id points to a GROUP offer, and only to a Cohort
    -- belonging to that same offer (enforced by handle_deal_saved()).
    cohort_id bigint,
    stage text not null,
    -- Exit/outcome, separate from stage: an active opportunity has no outcome.
    outcome text,
    owner_decision text,
    -- Only meaningful when owner_decision = 'would_work_with'.
    prospect_decision text,
    -- Shown when prospect_decision = 'thinking'; defaults to +4 days in the UI.
    follow_up_date date,
    -- Next scheduled sales call, if any. One piece of the future "Next Up"
    -- surface alongside follow_up_date and Enrollment/Cohort dates.
    sales_call_at timestamp with time zone,
    source text,
    entry_path text,
    description text,
    amount bigint,
    -- Commercial snapshot, captured at save time by handle_deal_saved() so a
    -- later change to the Offer/payment option never rewrites historical
    -- sales context on an existing Opportunity.
    offer_name_snapshot text,
    offer_price_snapshot numeric(10, 2),
    selected_payment_option_id bigint,
    selected_payment_total numeric(10, 2),
    selected_installment_count smallint,
    selected_installment_amount numeric(10, 2),
    -- Payment domain foundation slice: the ONLY way the public personalized
    -- Offer Page resolves a Deal — opaque and random, never the Deal's own
    -- sequential id (which would let one prospect enumerate another's name
    -- and frozen price). Generated once, when the Deal first reaches
    -- Committed (see sales-calls/completeSalesCallOutcome.ts); null before
    -- that. No "active/expired/superseded" status: there is only ever one
    -- current commercial snapshot per Deal (handle_deal_saved() already
    -- re-freezes it in place on change), so the same token always reflects
    -- whatever is currently authorized — nothing to supersede.
    offer_page_token text,
    -- First time the public Offer Page was actually opened with a valid
    -- token, if ever — a lightweight signal ("did they even look"), not a
    -- state machine. Never touched again after the first open.
    offer_page_opened_at timestamp with time zone,
    -- Stripe test-mode integration slice: the minimal identifiers needed to
    -- observe and safely re-enter the payment/schedule-adoption sequence —
    -- never raw card/bank/payment-method data. stripe_checkout_session_id
    -- is the LATEST attempt (a Deal can retry Checkout after an abandoned
    -- session). stripe_subscription_id/stripe_subscription_schedule_id are
    -- only ever set for an installment plan (PIF has neither — a one-time
    -- Checkout Session needs no ongoing Stripe object). Whether the
    -- schedule's future phase has been configured yet is deliberately NOT
    -- persisted here — it's derived live from the real Stripe schedule's
    -- own phase count each time (see recordDealCheckoutCompleted.ts),
    -- never a separate CRM-side flag that could drift from Stripe's actual
    -- state.
    stripe_checkout_session_id text,
    stripe_subscription_id text,
    stripe_subscription_schedule_id text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    -- Kanban queue-ordering slice: when this Opportunity entered its
    -- CURRENT stage — set exactly once per genuine stage change by
    -- set_deal_stage_entered_at() below, never touched by an unrelated
    -- field edit, a note, or metadata change. The easy-to-query current-
    -- state half of the same pattern already used for Sales Calls: full
    -- history lives separately in deal_stage_events.
    stage_entered_at timestamp with time zone not null default now(),
    -- 'workshops_only' (Acuity/Sales Call Lifecycle slice) is a genuine
    -- pipeline exit but explicitly NOT a lost sale — set together with
    -- owner_decision = 'workshops_only', kept distinct from 'lost' so
    -- later analytics never conflates "redirected to Workshops" with
    -- "declined".
    constraint deals_outcome_check check (outcome in ('nurture', 'needs_higher_care', 'not_fit', 'lost', 'workshops_only')),
    constraint deals_owner_decision_check check (owner_decision in ('would_work_with', 'workshops_only', 'do_not_engage')),
    constraint deals_prospect_decision_check check (prospect_decision in ('yes', 'thinking', 'no')),
    constraint deals_source_check check (source in ('instagram', 'referral', 'podcast', 'workshop', 'substack', 'google', 'other')),
    -- 'application_form' is the native public intake route (Native
    -- Application Intake slice, §9) — distinct from 'sales_page' (an
    -- outbound sales-page visit) and 'instagram_conversation' (a DM).
    constraint deals_entry_path_check check (entry_path in ('instagram_conversation', 'sales_page', 'application_form', 'other'))
);

-- Append-only history of every genuine stage transition an Opportunity has
-- made (Kanban queue-ordering slice) — the same "durable event history
-- alongside an easy current-state field" split already used for Sales
-- Calls (sales_calls/sales_call_events). One row per stage the Opportunity
-- has ever entered, written exactly once per genuine change by
-- record_deal_stage_event() below. Deliberately narrow: this exists only
-- to preserve stage transitions, not a general audit log of every field
-- change. Preserves what deals.stage_entered_at alone cannot: durations
-- through EARLIER stages (Application -> Call Booked -> Decision ->
-- Committed -> Won), needed for future per-offer funnel timing.
create table public.deal_stage_events (
    id bigint generated by default as identity primary key,
    opportunity_id bigint not null,
    stage text not null,
    entered_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now()
);

-- A submitted program/coaching application. Reached only through its
-- Opportunity (Contact/Offer/Cohort are all reachable that way), so no extra
-- FKs are duplicated here.
create table public.applications (
    id bigint generated by default as identity primary key,
    opportunity_id bigint not null,
    -- Review outcomes are distinct on purpose (Native Applications slice,
    -- §1): 'approved' means "qualified for a sales call", not "Leif wants
    -- to work with them" — that call still happens later. The generic
    -- 'rejected' value is retired in favor of the specific reason.
    status text not null default 'pending',
    submitted_at timestamp with time zone not null default now(),
    reviewed_at timestamp with time zone,
    -- Application questions differ by Offer and will evolve; jsonb avoids a
    -- migration every time the question set changes. No fixed schema yet.
    raw_answers jsonb not null default '{}'::jsonb,
    -- Free text for now; shaped to hold a future AI-generated summary.
    summary text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint applications_status_check check (status in ('pending', 'approved', 'needs_higher_care', 'not_fit', 'do_not_engage'))
);

-- The commercial/client lifecycle after a successful sale. At most one per
-- Opportunity (enforced by the unique index below), which is also what makes
-- handle_deal_saved()'s Won -> Enrollment creation idempotent.
create table public.enrollments (
    id bigint generated by default as identity primary key,
    opportunity_id bigint not null,
    status text not null default 'onboarding',
    start_date date,
    end_date date,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint enrollments_status_check check (status in ('onboarding', 'active', 'offboarding', 'completed'))
);

-- Contracts + Onboarding slice: one row per (Enrollment x applicable
-- requirement), created once by handle_deal_won() below at the moment the
-- Enrollment itself is created (same idempotency gate, so a duplicate
-- Stripe webhook can never re-seed these any more than it can re-create
-- the Enrollment). label/is_required are SNAPSHOTTED from
-- onboarding_requirement_templates at that moment — deliberately not a
-- live join back to it, so a later template edit never rewrites an
-- already-created Enrollment's own checklist history (same rationale as
-- deals.offer_name_snapshot/offer_price_snapshot).
create table public.enrollment_onboarding_items (
    id bigint generated by default as identity primary key,
    enrollment_id bigint not null,
    requirement_key text not null,
    label text not null,
    -- Snapshotted alongside label — needed if reopenOnboardingItem.ts ever
    -- has to recreate a Task from scratch (its originally-linked Task was
    -- cancelled, not merely completed) without re-reading the live
    -- (possibly since-edited or deactivated) template row.
    task_text_template text not null,
    is_required boolean not null,
    sort_order smallint not null default 0,
    -- 'sent' only meaningful for the 'contract' item (not sent -> sent ->
    -- done, where the UI relabels 'done' as "Signed" for that one row);
    -- every other item goes straight pending -> done. One shared enum, no
    -- per-requirement-type column.
    status text not null default 'pending',
    completed_at timestamp with time zone,
    -- Future integration id (e.g. a DocuSign envelope id, a Slack invite
    -- id), unwired in this slice — same "place to land later" pattern as
    -- cohorts.slack_channel_id/calendar_id above.
    external_ref text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint enrollment_onboarding_items_status_check check (status in ('pending', 'sent', 'done')),
    unique (enrollment_id, requirement_key)
);

-- A person waiting for space/timing in a program, independent of the
-- active sales pipeline (Waitlists slice, §1): "does this person want
-- access when appropriate" rather than "are they currently moving through
-- a sales decision". Deliberately its own entity — not a boolean on
-- contacts (a person can wait for more than one Offer/Cohort over their
-- lifetime) and not an Opportunity stage (waiting and actively deciding
-- are different relationships that can coexist or diverge).
create table public.waitlist_entries (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    offer_id bigint not null,
    -- Only set for a cohort-specific entry, and only to a Cohort belonging
    -- to that same offer (enforced by handle_waitlist_entry_saved()) — an
    -- offer-level entry (e.g. "wants GYU generally") leaves this null.
    cohort_id bigint,
    status text not null default 'waiting',
    joined_at timestamp with time zone not null default now(),
    desired_timing text,
    notes text,
    -- Leif's manual ordering signal, not a strict FIFO queue — nullable
    -- and purely advisory (Waitlists slice, §14).
    priority smallint,
    source text,
    invited_at timestamp with time zone,
    converted_at timestamp with time zone,
    -- The Opportunity this entry became, once converted — lets the Contact
    -- page and this entry both link straight to it (§12).
    converted_opportunity_id bigint,
    removed_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint waitlist_entries_status_check check (status in ('waiting', 'invited', 'converted', 'removed')),
    constraint waitlist_entries_source_check check (source in ('instagram', 'referral', 'podcast', 'workshop', 'substack', 'google', 'other'))
);

-- Prevents duplicate ACTIVE (waiting/invited) entries for the same
-- Contact + Offer + Cohort (§4) at the database level — the primary
-- enforcement is the shared domain check in
-- waitlist/waitlistEntryValidation.ts (the only thing that can behave
-- identically in FakeRest, which has no constraint engine at all), this
-- index is defense-in-depth against races/direct SQL on the real DB.
-- Historical converted/removed entries are excluded, so rejoining later is
-- always allowed. cohort_id is coalesced to -1 (never a valid id) because
-- Postgres treats each NULL as distinct in a plain unique index, which
-- would otherwise let two offer-level (cohort_id null) entries collide
-- silently past this constraint.
create unique index waitlist_entries_active_unique_idx on public.waitlist_entries (contact_id, offer_id, coalesce(cohort_id, -1)) where (status in ('waiting', 'invited'));

-- The durable current-state record for a sales call/appointment (Acuity/
-- Sales Call Lifecycle slice), one row per LOGICAL appointment — a
-- reschedule updates this row rather than creating a second one, so it
-- can never look like two independent calls in later conversion
-- analytics. Individual lifecycle facts (booked/rescheduled/cancelled/
-- attendance recorded, with occurred_at and old/new values) are preserved
-- separately in sales_call_events; this row is only ever current/summary
-- state.
create table public.sales_calls (
    id bigint generated by default as identity primary key,
    -- Nullable: a booking that can't be safely matched to exactly one
    -- active Opportunity is preserved with opportunity_id = null rather
    -- than guessed — see sales-calls/matchAcuityBooking.ts. Surfaced via
    -- a "Resolve Sales Call" task rather than silently buried.
    opportunity_id bigint,
    -- Always resolved (normalized-email match-or-create, Native
    -- Application Intake's own matching principle) even when the
    -- Opportunity is ambiguous.
    contact_id bigint not null,
    status text not null default 'booked',
    -- Set once at creation, never updated by a reschedule.
    original_scheduled_at timestamp with time zone not null,
    -- The current/latest scheduled time. Mirrored onto the owning
    -- Opportunity's sales_call_at (a denormalized convenience field, kept
    -- exactly as it already was) by sync_deal_sales_call_at() below.
    scheduled_at timestamp with time zone not null,
    reschedule_count smallint not null default 0,
    last_rescheduled_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    -- Always a human/CRM action (Complete Sales Call), never inferred
    -- from Acuity — an appointment's time passing does not prove
    -- attendance.
    attendance text,
    attendance_recorded_at timestamp with time zone,
    source text not null default 'manual',
    acuity_appointment_id text,
    acuity_appointment_type_id text,
    -- Unmatched Sales Call Resolution slice: distinct from
    -- opportunity_id — a booking can be unresolved (both null), matched
    -- (opportunity_id set), or deliberately dismissed (dismissed_at set,
    -- opportunity_id stays null forever). Never overload
    -- opportunity_id = null to mean both "not yet resolved" and
    -- "resolved as not-a-sales-situation" — a duplicate Acuity webhook
    -- replay needs to tell those apart to never resurrect a dismissed
    -- booking's alert.
    dismissed_at timestamp with time zone,
    dismissal_reason text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint sales_calls_status_check check (status in ('booked', 'cancelled')),
    constraint sales_calls_attendance_check check (attendance in ('attended', 'no_show')),
    constraint sales_calls_source_check check (source in ('acuity', 'manual'))
);

-- Defense-in-depth alongside the domain-layer duplicate-booking check
-- (sales-calls/bookSalesCall.ts): at most one currently-booked call per
-- Opportunity — a second incoming booking for the same Opportunity is a
-- reschedule of the existing row, never a second one.
create unique index sales_calls_one_booked_per_opportunity_idx on public.sales_calls (opportunity_id) where (status = 'booked' and opportunity_id is not null);
create unique index sales_calls_acuity_appointment_id_idx on public.sales_calls (acuity_appointment_id) where (acuity_appointment_id is not null);

-- Append-only lifecycle history for a sales_calls row (Leif's own decision:
-- durable individual events, not just a reschedule_count + last_rescheduled_at
-- summary). Deliberately NOT a generalized event-sourcing log — sales_calls
-- stays the easy current-state record every read goes through; this table
-- exists only so multiple reschedules don't collapse into a single count.
create table public.sales_call_events (
    id bigint generated by default as identity primary key,
    sales_call_id bigint not null,
    kind text not null,
    occurred_at timestamp with time zone not null default now(),
    -- Only set for kind = 'rescheduled'.
    previous_scheduled_at timestamp with time zone,
    new_scheduled_at timestamp with time zone,
    -- Only set for kind = 'attendance_recorded'.
    attendance text,
    -- Only set for kind = 'dismissed' (Unmatched Sales Call Resolution
    -- slice) — mirrored from sales_calls.dismissal_reason at the moment
    -- of dismissal, same "final state also durable in its own event"
    -- convention as attendance above.
    dismissal_reason text,
    created_at timestamp with time zone not null default now(),
    constraint sales_call_events_kind_check check (kind in ('booked', 'rescheduled', 'cancelled', 'attendance_recorded', 'opportunity_attached', 'dismissed')),
    constraint sales_call_events_attendance_check check (attendance in ('attended', 'no_show'))
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    -- Tasks are reminders/actions, not sales-status controls: this never
    -- reads from or writes to Opportunity/Application state. Kept in sync
    -- with done_date by the app (Pending <-> Completed via the checkbox);
    -- Waiting/Cancelled are set explicitly. ONE deliberate, narrow
    -- exception (Contracts + Onboarding slice): a Task pointing at
    -- onboarding_item_id below IS synced with that one Enrollment
    -- checklist item's status (see sync_onboarding_item_from_task() in
    -- 02_functions.sql) — the checklist is still the durable source of
    -- truth (a cancelled Task never completes its item), this is just
    -- the one direction where completing the Task legitimately means the
    -- work got done.
    status text not null default 'pending',
    sales_id bigint,
    -- Contracts + Onboarding slice: Task points AT its business context
    -- (chosen over the reverse — a context row pointing at its Task —
    -- specifically so a Task can exist for an Enrollment with no specific
    -- checklist item, so one item can later have more than one Task, and
    -- so there is never a stored "current task" pointer elsewhere that
    -- must be kept in sync by hand). Both nullable: most Tasks (sales_call,
    -- follow_up, etc.) still resolve via the existing contact_id heuristic
    -- in useTaskActionDestination.ts, untouched by this slice.
    -- enrollment_id alone: an Enrollment-level Task with no specific
    -- checklist item (e.g. "check in on how onboarding is going").
    enrollment_id bigint,
    -- Set together with enrollment_id (never alone — enforced by
    -- set_task_enrollment_id_consistency() below): this Task is about one
    -- specific checklist item.
    onboarding_item_id bigint,
    -- Unmatched Sales Call Resolution slice: the same "Task points AT its
    -- context" pattern as enrollment_id/onboarding_item_id above — a
    -- resolve_sales_call Task's only real subject is one specific
    -- sales_calls row, never a whole Contact (a returning Contact could
    -- have more than one unresolved booking at once). Independent of
    -- enrollment_id/onboarding_item_id — a Task is never about both an
    -- Enrollment and a Sales Call.
    sales_call_id bigint,
    constraint tasks_status_check check (status in ('pending', 'waiting', 'completed', 'cancelled'))
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deals
    add constraint deals_offer_id_fkey foreign key (offer_id) references public.offers(id);

alter table public.deals
    add constraint deals_cohort_id_fkey foreign key (cohort_id) references public.cohorts(id);

alter table public.deals
    add constraint deals_selected_payment_option_id_fkey foreign key (selected_payment_option_id) references public.offer_payment_options(id);

alter table public.offer_payment_options
    add constraint offer_payment_options_offer_id_fkey foreign key (offer_id) references public.offers(id) on update cascade on delete cascade;

alter table public.cohorts
    add constraint cohorts_offer_id_fkey foreign key (offer_id) references public.offers(id) on update cascade on delete cascade;

alter table public.applications
    add constraint applications_opportunity_id_fkey foreign key (opportunity_id) references public.deals(id) on update cascade on delete cascade;

alter table public.enrollments
    add constraint enrollments_opportunity_id_fkey foreign key (opportunity_id) references public.deals(id) on update cascade on delete cascade;

alter table public.waitlist_entries
    add constraint waitlist_entries_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.waitlist_entries
    add constraint waitlist_entries_offer_id_fkey foreign key (offer_id) references public.offers(id) on update cascade on delete cascade;

alter table public.waitlist_entries
    add constraint waitlist_entries_cohort_id_fkey foreign key (cohort_id) references public.cohorts(id) on update cascade on delete cascade;

-- Not cascaded on delete: a converted Waitlist Entry stays historically
-- meaningful even if the Opportunity it became is later removed, so the
-- link just clears rather than taking the whole entry with it.
alter table public.waitlist_entries
    add constraint waitlist_entries_converted_opportunity_id_fkey foreign key (converted_opportunity_id) references public.deals(id) on update cascade on delete set null;

alter table public.sales_calls
    add constraint sales_calls_opportunity_id_fkey foreign key (opportunity_id) references public.deals(id) on update cascade on delete cascade;

alter table public.sales_calls
    add constraint sales_calls_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.sales_call_events
    add constraint sales_call_events_sales_call_id_fkey foreign key (sales_call_id) references public.sales_calls(id) on update cascade on delete cascade;

alter table public.deal_stage_events
    add constraint deal_stage_events_opportunity_id_fkey foreign key (opportunity_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Contracts + Onboarding slice: set null (not cascade) on delete — a Task
-- is Leif's own durable record of having done or needed to do something;
-- it must survive the Enrollment/item it was originally about being
-- removed, same "the record of the action outlives its subject" instinct
-- as waitlist_entries_converted_opportunity_id_fkey above.
alter table public.tasks
    add constraint tasks_enrollment_id_fkey foreign key (enrollment_id) references public.enrollments(id) on update cascade on delete set null;

alter table public.tasks
    add constraint tasks_onboarding_item_id_fkey foreign key (onboarding_item_id) references public.enrollment_onboarding_items(id) on update cascade on delete set null;

alter table public.tasks
    add constraint tasks_sales_call_id_fkey foreign key (sales_call_id) references public.sales_calls(id) on update cascade on delete set null;

alter table public.onboarding_requirement_templates
    add constraint onboarding_requirement_templates_offer_id_fkey foreign key (offer_id) references public.offers(id) on update cascade on delete cascade;

alter table public.enrollment_onboarding_items
    add constraint enrollment_onboarding_items_enrollment_id_fkey foreign key (enrollment_id) references public.enrollments(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

-- At most one Enrollment per Opportunity.
alter table only public.enrollments
    add constraint enrollments_opportunity_id_key unique (opportunity_id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index deals_contact_id_idx on public.deals using btree (contact_id);
create index deals_offer_id_idx on public.deals using btree (offer_id);
create index deals_cohort_id_idx on public.deals using btree (cohort_id);
-- Payment domain foundation slice: at most one Deal may ever claim a given
-- Offer Page token — the public route's only lookup key, so a collision
-- here would be a genuine security bug, not just a data-integrity nicety.
create unique index deals_offer_page_token_idx on public.deals (offer_page_token) where (offer_page_token is not null);
-- Stripe test-mode integration slice: data-integrity guards — a real
-- Stripe Subscription/Schedule must never end up cross-wired to two
-- different Deals.
create unique index deals_stripe_subscription_id_idx on public.deals (stripe_subscription_id) where (stripe_subscription_id is not null);
create unique index deals_stripe_subscription_schedule_id_idx on public.deals (stripe_subscription_schedule_id) where (stripe_subscription_schedule_id is not null);
create unique index contacts_stripe_customer_id_idx on public.contacts (stripe_customer_id) where (stripe_customer_id is not null);
create index offer_payment_options_offer_id_idx on public.offer_payment_options using btree (offer_id);
create index cohorts_offer_id_idx on public.cohorts using btree (offer_id);
create index applications_opportunity_id_idx on public.applications using btree (opportunity_id);
create index waitlist_entries_contact_id_idx on public.waitlist_entries using btree (contact_id);
create index waitlist_entries_offer_id_idx on public.waitlist_entries using btree (offer_id);
create index waitlist_entries_cohort_id_idx on public.waitlist_entries using btree (cohort_id);
create index waitlist_entries_converted_opportunity_id_idx on public.waitlist_entries using btree (converted_opportunity_id);
create index sales_calls_opportunity_id_idx on public.sales_calls using btree (opportunity_id);
create index sales_calls_contact_id_idx on public.sales_calls using btree (contact_id);
create index sales_call_events_sales_call_id_idx on public.sales_call_events using btree (sales_call_id);
create index deal_stage_events_opportunity_id_idx on public.deal_stage_events using btree (opportunity_id);

-- Prevents two Offers/Cohorts from ever claiming the same Acuity
-- appointment type, which would make the booking -> Offer/Cohort mapping
-- ambiguous (Acuity/Sales Call Lifecycle slice).
create unique index offers_acuity_appointment_type_id_idx on public.offers (acuity_appointment_type_id) where (acuity_appointment_type_id is not null);
create unique index cohorts_acuity_appointment_type_id_idx on public.cohorts (acuity_appointment_type_id) where (acuity_appointment_type_id is not null);

-- Contracts + Onboarding slice.
create index onboarding_requirement_templates_offer_id_idx on public.onboarding_requirement_templates using btree (offer_id);
create index enrollment_onboarding_items_enrollment_id_idx on public.enrollment_onboarding_items using btree (enrollment_id);
create index tasks_enrollment_id_idx on public.tasks using btree (enrollment_id);
create index tasks_onboarding_item_id_idx on public.tasks using btree (onboarding_item_id);
create index tasks_sales_call_id_idx on public.tasks using btree (sales_call_id);
