#!/usr/bin/env python3
"""Emit sql/seed_w3_roster.sql — walkthrough census on top of W0–W3.

Deterministic UUIDs: uuid5(tenant_ns, 'w3-roster:<key>').
Does not recreate the hand-seeded triangle / view rows.
"""

from __future__ import annotations

import uuid
from pathlib import Path

from tenant_uuid import TENANT_NS, tenant_uuid

WOODLEY = tenant_uuid("100004")
ENVOY = tenant_uuid("100081")
OWNER = "11111111-1111-1111-1111-111111111111"
ENVOY_OWNER = "22222222-2222-2222-2222-222222222222"

BROKERAGE = "c1000002-0002-4000-8000-000000000001"
GRIN = "c1000002-0002-4000-8000-000000000002"
HARBOR = "c1000002-0002-4000-8000-000000000003"
PHIL = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaad"
AVERY = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac"
RILEY = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaae"
WILLOW = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
IN_PROCESS = "c1000001-0001-4000-8000-000000000004"
APP_STARTED = "c1000001-0001-4000-8000-000000000041"
UNDERWRITING = "c1000001-0001-4000-8000-000000000042"
RECRUITING = "c1000001-0001-4000-8000-000000000007"
RECRUIT_STAGE = "c1000001-0001-4000-8000-000000000071"
PAIRED_LIST = "a1000004-0004-4000-8000-000000000001"

FIRST = [
    "Ada", "Ben", "Cora", "Drew", "Eve", "Finn", "Gia", "Hank", "Ivy", "Jon",
    "Kim", "Leo", "Mia", "Ned", "Ora", "Pax", "Quin", "Rosa", "Sid", "Tess",
    "Uma", "Vic", "Wren", "Xan", "Yara", "Zed", "Alma", "Beau", "Cleo", "Dale",
    "Edie", "Faye", "Gus", "Hana", "Iris", "Jude",
]
LAST = [
    "Ash", "Bell", "Cole", "Dunn", "East", "Ford", "Gray", "Hart", "Ives",
    "Joss", "Kerr", "Lane", "Moss", "Nash", "Owen", "Pike", "Quinn", "Reed",
    "Shaw", "Tate", "Voss", "Wade", "York", "Zane", "Blair", "Cruz", "Diaz",
]


def uid(key: str) -> str:
    return str(uuid.uuid5(TENANT_NS, f"w3-roster:{key}"))


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    lines: list[str] = [
        "-- Generated by scripts/generate_w3_roster.py. Do not edit by hand.",
        "-- Fake PII only. Adds the walkthrough census on top of seed_w0/w1/w3.",
        "",
        "insert into deal_party_roles (id) values ('recruit') on conflict do nothing;",
        "",
    ]

    # Extra pipelines / stages
    lead = uid("pipe-lead")
    closed = uid("pipe-closed")
    b2b = uid("pipe-b2b")
    lead_stage = uid("stage-lead-02")
    closed_stage = uid("stage-closed-12")
    b2b_stage = uid("stage-b2b-01")
    lines.append(
        "insert into pipelines (id, tenant_id, name, sort_index) values\n"
        f"    ({sql_str(lead)}, {sql_str(str(WOODLEY))}, 'Lead - Active', 10),\n"
        f"    ({sql_str(closed)}, {sql_str(str(WOODLEY))}, 'Closed / Archive', 50),\n"
        f"    ({sql_str(b2b)}, {sql_str(str(WOODLEY))}, 'Mortgage opportunity', 60)\n"
        "on conflict (id) do nothing;\n"
    )
    # Lead - Active already exists in W1 with a different id. Use W1 lead pipe if present.
    w1_lead = "c1000001-0001-4000-8000-000000000001"
    w1_lead_stage = "c1000001-0001-4000-8000-000000000011"
    lines.append(
        "insert into pipeline_stages (id, tenant_id, pipeline_id, code, label, sort_index, is_closed, is_won) values\n"
        f"    ({sql_str(closed_stage)}, {sql_str(str(WOODLEY))}, {sql_str(closed)}, "
        f"'12-inactive', '12 - Inactive', 12, true, false),\n"
        f"    ({sql_str(b2b_stage)}, {sql_str(str(WOODLEY))}, {sql_str(b2b)}, "
        f"'01-open', '01 - Open', 1, false, false)\n"
        "on conflict (id) do nothing;\n"
    )

    # Lender + 3 branches + 2 more teams
    lender = uid("co-lender")
    branches = [uid(f"co-branch-{i}") for i in range(3)]
    team_smile = uid("co-team-smile")
    team_north = uid("co-team-north")
    lines.append("insert into companies (id, tenant_id, owner_id, parent_company_id, kind_id, name) values")
    company_rows = [
        f"    ({sql_str(lender)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, null, 'lender_branch', 'Woodley Bank')",
        *[
            f"    ({sql_str(branches[i])}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
            f"{sql_str(lender)}, 'lender_branch', 'Woodley Branch {i + 1}')"
            for i in range(3)
        ],
        f"    ({sql_str(team_smile)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
        f"{sql_str(BROKERAGE)}, 'place_team', 'Agents with a Smile')",
        f"    ({sql_str(team_north)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
        f"{sql_str(BROKERAGE)}, 'place_team', 'North Shore Team')",
    ]
    lines.append(",\n".join(company_rows) + "\n on conflict (id) do nothing;\n")

    teams = [GRIN, HARBOR, team_smile, team_north]

    def emit_contacts(kind: str, count: int, type_id: str, start: int = 0) -> list[str]:
        ids = []
        contact_rows = []
        type_rows = []
        ident_rows = []
        aff_rows = []
        for i in range(count):
            cid = uid(f"{kind}-{i + start}")
            ids.append(cid)
            first = FIRST[(i + start) % len(FIRST)]
            last = LAST[(i + start * 3) % len(LAST)]
            contact_rows.append(
                f"    ({sql_str(cid)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
                f"{sql_str(first)}, {sql_str(last)})"
            )
            type_rows.append(
                f"    ({sql_str(str(WOODLEY))}, {sql_str(cid)}, {sql_str(type_id)}, true)"
            )
            if type_id in ("real_estate_agent", "loan_officer", "recruit"):
                base = {
                    "real_estate_agent": 700000,
                    "loan_officer": 800000,
                    "recruit": 900000,
                }[type_id]
                ident_rows.append(
                    f"    ({sql_str(str(WOODLEY))}, {sql_str(cid)}, 'nmls', "
                    f"{sql_str(str(base + start + i))})"
                )
            if type_id == "real_estate_agent":
                team = teams[(i + start) % len(teams)]
                aff_rows.append(
                    f"    ({sql_str(str(WOODLEY))}, {sql_str(cid)}, {sql_str(team)}, 'agent', true)"
                )
            if type_id in ("loan_officer", "employee"):
                aff_rows.append(
                    f"    ({sql_str(str(WOODLEY))}, {sql_str(cid)}, {sql_str(branches[(i) % 3])}, "
                    f"{sql_str(type_id)}, true)"
                )
        lines.append(
            "insert into contacts (id, tenant_id, owner_id, first_name, last_name) values\n"
            + ",\n".join(contact_rows)
            + "\n on conflict (id) do nothing;\n"
        )
        lines.append(
            "insert into contact_type_assignments (tenant_id, contact_id, type_id, is_primary) values\n"
            + ",\n".join(type_rows)
            + "\n on conflict do nothing;\n"
        )
        if ident_rows:
            lines.append(
                "insert into contact_identifiers (tenant_id, contact_id, id_type, value) values\n"
                + ",\n".join(ident_rows)
                + "\n on conflict do nothing;\n"
            )
        if aff_rows:
            lines.append(
                "insert into contact_affiliations (tenant_id, contact_id, company_id, role, is_primary) values\n"
                + ",\n".join(aff_rows)
                + "\n on conflict do nothing;\n"
            )
        return ids

    agent_ids = emit_contacts("agent", 38, "real_estate_agent")
    lo_ids = emit_contacts("lo", 14, "loan_officer")
    emit_contacts("staff", 8, "employee")
    borrower_ids = emit_contacts("borrower", 70, "borrower")
    spouse_ids = emit_contacts("spouse", 30, "borrower", start=70)

    # Pair first 30 borrowers with spouses
    link_rows = []
    for i in range(30):
        link_rows.append(
            f"    ({sql_str(str(WOODLEY))}, 'spouse', 'contact', {sql_str(borrower_ids[i])}, "
            f"'contact', {sql_str(spouse_ids[i])})"
        )
    # Extra paired agents on the ENV list (first 8 generated agents)
    list_rows = []
    for cid in agent_ids[:8]:
        list_rows.append(
            f"    ({sql_str(str(WOODLEY))}, {sql_str(PAIRED_LIST)}, 'contact', {sql_str(cid)})"
        )
    lines.append(
        "insert into record_links (tenant_id, link_type_id, from_object_type, from_id, to_object_type, to_id) values\n"
        + ",\n".join(link_rows)
        + "\n on conflict do nothing;\n"
    )
    lines.append(
        "insert into list_members (tenant_id, list_id, object_type, object_id) values\n"
        + ",\n".join(list_rows)
        + "\n on conflict do nothing;\n"
    )

    # Third showcase triangle on generated people
    show_b, show_s, show_a = borrower_ids[0], spouse_ids[0], agent_ids[0]
    show_deal = uid("deal-showcase-3")
    deal_rows = [
        f"    ({sql_str(show_deal)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
        f"{sql_str(IN_PROCESS)}, {sql_str(APP_STARTED)}, 'Ada purchase', 39000000, 'walkthrough')"
    ]
    party_rows = [
        f"    ({sql_str(str(WOODLEY))}, {sql_str(show_deal)}, {sql_str(show_b)}, 'borrower', true)",
        f"    ({sql_str(str(WOODLEY))}, {sql_str(show_deal)}, {sql_str(show_s)}, 'co_borrower', false)",
        f"    ({sql_str(str(WOODLEY))}, {sql_str(show_deal)}, {sql_str(show_a)}, 'referring_agent', false)",
        f"    ({sql_str(str(WOODLEY))}, {sql_str(show_deal)}, {sql_str(PHIL)}, 'loan_officer', false)",
    ]

    # ~55 more loans across pipelines
    pipes = [
        (w1_lead, w1_lead_stage, 15, "lead"),
        (IN_PROCESS, UNDERWRITING, 20, "inproc"),
        (closed, closed_stage, 20, "closed"),
    ]
    n = 0
    for pipe_id, stage_id, count, tag in pipes:
        for i in range(count):
            did = uid(f"deal-{tag}-{i}")
            b = borrower_ids[(n + 1) % len(borrower_ids)]
            a = agent_ids[n % len(agent_ids)]
            lo = lo_ids[n % len(lo_ids)] if lo_ids else PHIL
            amount = 25000000 + n * 137000
            source = "in_the_money" if tag == "closed" and i < 4 else "roster"
            deal_rows.append(
                f"    ({sql_str(did)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
                f"{sql_str(pipe_id)}, {sql_str(stage_id)}, {sql_str(f'{tag.title()} {i + 1}')}, "
                f"{amount}, {sql_str(source)})"
            )
            party_rows.append(
                f"    ({sql_str(str(WOODLEY))}, {sql_str(did)}, {sql_str(b)}, 'borrower', true)"
            )
            party_rows.append(
                f"    ({sql_str(str(WOODLEY))}, {sql_str(did)}, {sql_str(a)}, 'referring_agent', false)"
            )
            party_rows.append(
                f"    ({sql_str(str(WOODLEY))}, {sql_str(did)}, {sql_str(lo)}, 'loan_officer', false)"
            )
            n += 1

    # Recruiting + B2B
    for i in range(7):
        did = uid(f"deal-recruit-{i}")
        recruit = uid(f"recruit-extra-{i}")
        lines.append(
            "insert into contacts (id, tenant_id, owner_id, first_name, last_name) values\n"
            f"    ({sql_str(recruit)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
            f"{sql_str(FIRST[i])}, 'Recruit')\n"
            "on conflict (id) do nothing;\n"
        )
        lines.append(
            "insert into contact_type_assignments (tenant_id, contact_id, type_id, is_primary) values\n"
            f"    ({sql_str(str(WOODLEY))}, {sql_str(recruit)}, 'recruit', true)\n"
            "on conflict do nothing;\n"
        )
        deal_rows.append(
            f"    ({sql_str(did)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
            f"{sql_str(RECRUITING)}, {sql_str(RECRUIT_STAGE)}, {sql_str(f'Recruit {i + 1}')}, "
            f"null, 'roster')"
        )
        party_rows.append(
            f"    ({sql_str(str(WOODLEY))}, {sql_str(did)}, {sql_str(recruit)}, 'recruit', true)"
        )
    for i in range(5):
        did = uid(f"deal-b2b-{i}")
        deal_rows.append(
            f"    ({sql_str(did)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
            f"{sql_str(b2b)}, {sql_str(b2b_stage)}, {sql_str(f'Team opportunity {i + 1}')}, "
            f"{8000000 + i * 500000}, 'roster')"
        )

    lines.append(
        "insert into deals (id, tenant_id, owner_id, pipeline_id, stage_id, name, amount_cents, source) values\n"
        + ",\n".join(deal_rows)
        + "\n on conflict (id) do nothing;\n"
    )
    lines.append(
        "insert into deal_parties (tenant_id, deal_id, contact_id, role, is_primary) values\n"
        + ",\n".join(party_rows)
        + "\n on conflict do nothing;\n"
    )

    # Three intentional duplicates (same name, extra email, missing NMLS)
    dups = [
        ("dup-willow", "Willow", "Woodley", "email", "willow.dup@example.test"),
        ("dup-avery", "Avery", "Agent", "email", "avery.other@example.test"),
        ("dup-blair", "Blair", "Borrower", "email", "blair.old@example.test"),
    ]
    dup_c = []
    dup_t = []
    dup_i = []
    for key, first, last, id_type, value in dups:
        cid = uid(key)
        dup_c.append(
            f"    ({sql_str(cid)}, {sql_str(str(WOODLEY))}, {sql_str(OWNER)}, "
            f"{sql_str(first)}, {sql_str(last)})"
        )
        dup_t.append(
            f"    ({sql_str(str(WOODLEY))}, {sql_str(cid)}, 'borrower', true)"
        )
        dup_i.append(
            f"    ({sql_str(str(WOODLEY))}, {sql_str(cid)}, {sql_str(id_type)}, {sql_str(value)})"
        )
    lines.append(
        "insert into contacts (id, tenant_id, owner_id, first_name, last_name) values\n"
        + ",\n".join(dup_c)
        + "\n on conflict (id) do nothing;\n"
    )
    lines.append(
        "insert into contact_type_assignments (tenant_id, contact_id, type_id, is_primary) values\n"
        + ",\n".join(dup_t)
        + "\n on conflict do nothing;\n"
    )
    lines.append(
        "insert into contact_identifiers (tenant_id, contact_id, id_type, value) values\n"
        + ",\n".join(dup_i)
        + "\n on conflict do nothing;\n"
    )

    # Envoy extras (~3 more contacts)
    envoy_rows = []
    for i, name in enumerate(["Gia Envoy", "Hank Envoy", "Ivy Envoy"]):
        first, last = name.split()
        cid = uid(f"envoy-{i}")
        envoy_rows.append(
            f"    ({sql_str(cid)}, {sql_str(str(ENVOY))}, {sql_str(ENVOY_OWNER)}, "
            f"{sql_str(first)}, {sql_str(last)})"
        )
    lines.append(
        "insert into contacts (id, tenant_id, owner_id, first_name, last_name) values\n"
        + ",\n".join(envoy_rows)
        + "\n on conflict (id) do nothing;\n"
    )

    out = Path(__file__).resolve().parent.parent / "sql" / "seed_w3_roster.sql"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
