// @vitest-environment node
import { describe, expect, it } from "vitest";

import schema from "./creationSchemaContract.json";
import writers from "./writers.json";

// The two artifacts in this folder describe the same INSERT from opposite
// sides: writers.json says what each caller sends, creationSchemaContract
// .json says what the table requires. Nothing compared them, and for one
// revision they disagreed — the schema snapshot listed contact_id, id and
// scheduled_on together as "required at creation with no default", which is
// true of the catalog and useless as a statement about writers: contact_id
// is supplied by both, id is generated by PostgreSQL, and only scheduled_on
// depends on a trigger nobody would miss until production stopped
// accepting bookings.
//
// This file is the join. Every NOT NULL column has exactly one thing that
// fills it, and that thing has to agree with what the writers actually do.
//
// It needs no database: both sides are checked-in facts. The live database
// is held to the snapshot separately, by e2e/salesCallWriteContracts.spec
// .ts, which is also where the writers get replayed for real.

const everyWriter = writers.writers;

describe("the writer inventory and the schema contract tell one story", () => {
  it("has both artifacts populated", () => {
    expect(everyWriter.length).toBeGreaterThan(0);
    expect(schema.not_null_columns.length).toBeGreaterThan(0);
    expect(schema.table).toBe(writers.table);
  });

  it("classifies every NOT NULL column exactly once", () => {
    const buckets = [
      ...schema.writer_supplied_columns,
      ...schema.trigger_filled_columns,
      ...schema.identity_columns,
      ...schema.defaulted_columns,
    ];
    expect(buckets.sort()).toEqual([...schema.not_null_columns].sort());
    expect(
      new Set(buckets).size,
      "a column appears in more than one fill-mechanism bucket",
    ).toBe(buckets.length);
  });

  it.each(everyWriter.map((writer) => [writer.id, writer] as const))(
    "%s supplies every column the database makes the caller's job",
    (_id, writer) => {
      for (const column of schema.writer_supplied_columns) {
        expect(
          writer.supplies,
          `${column} is NOT NULL with no default, no identity and no trigger — ${writer.id} must supply it or every insert it makes fails`,
        ).toContain(column);
      }
    },
  );

  it.each(everyWriter.map((writer) => [writer.id, writer] as const))(
    "%s leaves trigger-filled and identity columns alone",
    (_id, writer) => {
      for (const column of [
        ...schema.trigger_filled_columns,
        ...schema.identity_columns,
      ]) {
        expect(
          writer.supplies,
          `${writer.id} supplies ${column}, which the database fills`,
        ).not.toContain(column);
        expect(
          writer.derived_by_database,
          `${writer.id} does not record ${column} as database-derived`,
        ).toContain(column);
      }
    },
  );

  it.each(everyWriter.map((writer) => [writer.id, writer] as const))(
    "%s only names columns sales_calls actually has",
    (_id, writer) => {
      for (const column of [
        ...writer.supplies,
        ...writer.derived_by_database,
      ]) {
        expect(
          schema.all_columns,
          `${writer.id} names ${column}, which is not a column of ${schema.table}`,
        ).toContain(column);
      }
    },
  );

  // The specific fragility, stated so that removing it has to be deliberate.
  it("scheduled_on is filled by a trigger, by nothing else, and by no writer", () => {
    expect(schema.creation_fill_mechanism.scheduled_on).toBe("trigger");
    expect(schema.trigger_filled_columns).toEqual(["scheduled_on"]);
    expect(Object.keys(schema.column_defaults)).not.toContain("scheduled_on");
    expect(schema.identity_columns).not.toContain("scheduled_on");
    expect(Object.keys(schema.triggers)).toContain(
      "derive_sales_call_scheduled_on_trigger",
    );
    for (const writer of everyWriter) {
      expect(writer.supplies).not.toContain("scheduled_on");
    }
  });

  it("contact_id is the caller's job, and both callers do it", () => {
    expect(schema.creation_fill_mechanism.contact_id).toBe("writer");
    for (const writer of everyWriter) {
      expect(writer.supplies).toContain("contact_id");
    }
  });

  it("id is generated by PostgreSQL, which is not the same as having a default", () => {
    expect(schema.creation_fill_mechanism.id).toBe("identity");
    // An identity column does not appear in column_default. Reading its
    // absence there as "nothing fills this" is what produced the
    // contradiction this file exists to prevent.
    expect(Object.keys(schema.column_defaults)).not.toContain("id");
    expect(schema.identity_columns).toContain("id");
  });
});
