create table "public"."contactNotes" (
    "id" bigint generated by default as identity not null,
    "contact_id" bigint not null,
    "type" text,
    "text" text,
    "date" timestamp with time zone default now(),
    "sales_id" bigint,
    "status" text
);


alter table "public"."contactNotes" enable row level security;

CREATE UNIQUE INDEX "contactNotes_pkey" ON public."contactNotes" USING btree (id);

alter table "public"."contactNotes" add constraint "contactNotes_pkey" PRIMARY KEY using index "contactNotes_pkey";

alter table "public"."contactNotes" add constraint "contactNotes_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."contactNotes" validate constraint "contactNotes_contact_id_fkey";

alter table "public"."contactNotes" add constraint "contactNotes_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES sales(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."contactNotes" validate constraint "contactNotes_sales_id_fkey";

grant delete on table "public"."contactNotes" to "anon";

grant insert on table "public"."contactNotes" to "anon";

grant references on table "public"."contactNotes" to "anon";

grant select on table "public"."contactNotes" to "anon";

grant trigger on table "public"."contactNotes" to "anon";

grant truncate on table "public"."contactNotes" to "anon";

grant update on table "public"."contactNotes" to "anon";

grant delete on table "public"."contactNotes" to "authenticated";

grant insert on table "public"."contactNotes" to "authenticated";

grant references on table "public"."contactNotes" to "authenticated";

grant select on table "public"."contactNotes" to "authenticated";

grant trigger on table "public"."contactNotes" to "authenticated";

grant truncate on table "public"."contactNotes" to "authenticated";

grant update on table "public"."contactNotes" to "authenticated";

grant delete on table "public"."contactNotes" to "service_role";

grant insert on table "public"."contactNotes" to "service_role";

grant references on table "public"."contactNotes" to "service_role";

grant select on table "public"."contactNotes" to "service_role";

grant trigger on table "public"."contactNotes" to "service_role";

grant truncate on table "public"."contactNotes" to "service_role";

grant update on table "public"."contactNotes" to "service_role";

create policy "Enable read access for all users"
on "public"."contactNotes"
as permissive
for select
to authenticated
using (true);





