create table public.location_prices (
    "id" bigint generated by default as identity not null,
    "location_id" bigint not null, -- e.g. China Agent -> Port Yokohama
    "commodity_id" bigint not null, -- e.g Barley
    "commodity_grade" text not null default (''), -- e.g. Canada Barley or SA Barley
    "price_type" text not null, -- FIXED, DISCOUNT (e.g -19$/mt), PERCENT (e.g 98%)
    "price_value" numeric (10,2) not null, -- 0 means the customer is not currently buying
    "market_type" text not null, -- LME, CMX, NONE, LLME
    "market_price_fix" numeric (10,2), -- for situation where FIXED price is only valid for a certain market value,
    "validation_date" TIMESTAMP WITHOUT TIME ZONE, -- last time the price was validated and confirmed to be correct
    "sales_id" bigint not null -- sales person who validated the price
);

alter table public.location_prices enable row level security;

CREATE UNIQUE INDEX location_prices_pkey ON public.location_prices USING btree (id);
alter table public.location_prices add constraint "location_prices_pkey" PRIMARY KEY using index "location_prices_pkey";


ALTER TABLE public.location_prices add constraint "location_prices_uk" UNIQUE (location_id, commodity_id, commodity_grade, market_type);

alter table public.location_prices add constraint "location_prices_commodity_id_fkey" FOREIGN KEY (commodity_id) REFERENCES commodities(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table public.location_prices validate constraint "location_prices_commodity_id_fkey";

alter table public.location_prices add constraint "location_prices_location_id_fkey" FOREIGN KEY (location_id) REFERENCES locations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table public.location_prices validate constraint "location_prices_location_id_fkey";

alter table public.location_prices add constraint "location_prices_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES sales(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table public.location_prices validate constraint "location_prices_sales_id_fkey";



grant delete on table public.location_prices to "authenticated";
grant insert on table public.location_prices to "authenticated";
grant select on table public.location_prices to "authenticated";
grant update on table public.location_prices to "authenticated";

grant delete on table public.location_prices to "service_role";
grant insert on table public.location_prices to "service_role";
grant references on table public.location_prices to "service_role";
grant select on table public.location_prices to "service_role";
grant trigger on table public.location_prices to "service_role";
grant truncate on table public.location_prices to "service_role";
grant update on table public.location_prices to "service_role";


create policy "Enable insert for authenticated users only"
on public.location_prices
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for authenticated users"
on public.location_prices
as permissive
for select
to authenticated
using (true);


create policy "Enable update for authenticated users only"
on public.location_prices
as permissive
for update
to authenticated
using (true)
with check (true);

create policy "Enable delete for authenticated users only"
on public.location_prices
as permissive
for delete
to authenticated
using (true);

