-- Scholarship Pricing + Capacity slice: correction — every other
-- react-admin resource in this app assumes a plain `id` primary key (the
-- Supabase data provider has no per-resource primary-key override), but
-- the original scholarship_slots migration made offer_id itself the
-- primary key. Replace it with an ordinary identity `id` primary key, and
-- keep the same "at most one slot per Offer" guarantee via a plain unique
-- constraint on offer_id instead — functionally identical (ON CONFLICT
-- (offer_id) targets a unique constraint just as well as a primary key),
-- but now Dashboard/DealShow/etc. can read this resource the normal way.
alter table "public"."scholarship_slots" drop constraint "scholarship_slots_pkey";

alter table "public"."scholarship_slots"
  add column "id" bigint generated by default as identity;

alter table "public"."scholarship_slots"
  add constraint "scholarship_slots_pkey" primary key (id);

alter table "public"."scholarship_slots"
  add constraint "scholarship_slots_offer_id_key" unique (offer_id);
