CREATE TABLE public.outreach_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intake_lead_id UUID NOT NULL REFERENCES intake_leads(id) ON DELETE CASCADE,
  sequence_step INTEGER NOT NULL CHECK (sequence_step BETWEEN 1 AND 7),
  channel TEXT NOT NULL DEFAULT 'email'
    CHECK (channel IN ('email', 'linkedin', 'phone')),
  subject TEXT,
  body TEXT,
  review_status TEXT DEFAULT 'pending'
    CHECK (review_status IN ('pending', 'passed', 'failed', 'skipped')),
  review_feedback TEXT,
  status TEXT NOT NULL DEFAULT 'drafting'
    CHECK (status IN ('drafting', 'ai_reviewed', 'action_needed', 'approved', 'sent', 'completed', 'failed', 'replied')),
  provider_message_id TEXT,
  reply_body TEXT,
  reply_received_at TIMESTAMPTZ,
  run_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sent_at TIMESTAMPTZ,
  UNIQUE (intake_lead_id, sequence_step)
);

CREATE INDEX idx_outreach_steps_pending
  ON public.outreach_steps (intake_lead_id, sequence_step)
  WHERE status IN ('ai_reviewed', 'action_needed');

CREATE INDEX idx_outreach_steps_message_id
  ON public.outreach_steps (provider_message_id)
  WHERE provider_message_id IS NOT NULL;

ALTER TABLE public.outreach_steps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_read_outreach_steps"
  ON public.outreach_steps FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated_insert_outreach_steps"
  ON public.outreach_steps FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "authenticated_update_outreach_steps"
  ON public.outreach_steps FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "authenticated_delete_outreach_steps"
  ON public.outreach_steps FOR DELETE TO authenticated USING (true);
