-- Kanban queue-ordering slice.
-- Hand-authored (no local Docker/Supabase available this session — see
-- this slice's report for the production-verification item this leaves
-- open). Mirrors supabase/schemas/{01_tables,02_functions,04_triggers,
-- 05_policies,06_grants}.sql exactly.
--
-- Same "durable current-state field + append-only event history" split
-- already used for Sales Calls (sales_calls/sales_call_events), scoped
-- narrowly to stage transitions — not a general audit log:
--  - deals.stage_entered_at: when the Opportunity entered its CURRENT
--    stage, set exactly once per genuine stage change (never by an
--    unrelated field edit, a note, or metadata change). Kanban columns
--    sort on this, oldest first.
--  - deal_stage_events: one permanent row per stage the Opportunity has
--    ever entered — the only place per-earlier-stage duration (e.g. how
--    long an Opportunity spent in Call Booked before Decision) survives
--    past the Opportunity's current stage.
--
-- Backfill for pre-existing rows: no real transition history exists yet
-- for rows created before this migration, so both stage_entered_at and
-- the one deal_stage_events row seeded for each existing Opportunity use
-- that row's own created_at — a safe, honest fallback (distinct per row,
-- since created_at varies), not fabricated per-stage precision. Every
-- transition from this migration forward is captured exactly.

alter table "public"."deals"
    add column "stage_entered_at" timestamp with time zone;

update "public"."deals"
    set "stage_entered_at" = "created_at"
    where "stage_entered_at" is null;

alter table "public"."deals"
    alter column "stage_entered_at" set default now();
alter table "public"."deals"
    alter column "stage_entered_at" set not null;

create table "public"."deal_stage_events" (
    "id" bigint generated by default as identity primary key,
    "opportunity_id" bigint not null,
    "stage" text not null,
    "entered_at" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now()
);

create index "deal_stage_events_opportunity_id_idx" on "public"."deal_stage_events" using btree ("opportunity_id");

alter table "public"."deal_stage_events"
    add constraint "deal_stage_events_opportunity_id_fkey" foreign key ("opportunity_id") references "public"."deals"("id") on update cascade on delete cascade;

-- Seed one history row per existing Opportunity from the same backfilled
-- stage_entered_at above, so every deal has at least its current stage in
-- deal_stage_events from the moment this migration runs.
insert into "public"."deal_stage_events" ("opportunity_id", "stage", "entered_at")
    select "id", "stage", "stage_entered_at" from "public"."deals";

CREATE OR REPLACE FUNCTION "public"."set_deal_stage_entered_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  if tg_op = 'INSERT' or new.stage is distinct from old.stage then
    new.stage_entered_at := now();
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."record_deal_stage_event"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  if tg_op = 'INSERT' or new.stage is distinct from old.stage then
    insert into deal_stage_events (opportunity_id, stage, entered_at)
    values (new.id, new.stage, new.stage_entered_at);
  end if;
  return new;
end;
$$;

create or replace trigger "on_deal_stage_entered_at"
    before insert or update on "public"."deals"
    for each row execute function "public"."set_deal_stage_entered_at"();

create or replace trigger "on_deal_stage_event"
    after insert or update on "public"."deals"
    for each row execute function "public"."record_deal_stage_event"();

alter table "public"."deal_stage_events" enable row level security;

create policy "Enable read access for authenticated users" on "public"."deal_stage_events" for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."deal_stage_events" for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."deal_stage_events" for update to authenticated using (true) with check (true);
create policy "Deal Stage Events Delete Policy" on "public"."deal_stage_events" for delete to authenticated using (true);

grant all on table "public"."deal_stage_events" to anon;
grant all on table "public"."deal_stage_events" to authenticated;
grant all on table "public"."deal_stage_events" to service_role;

grant all on sequence "public"."deal_stage_events_id_seq" to anon;
grant all on sequence "public"."deal_stage_events_id_seq" to authenticated;
grant all on sequence "public"."deal_stage_events_id_seq" to service_role;
