-- Waitlists slice: a person can want access to a program without being in
-- the active sales pipeline. New standalone entity, not a Contact boolean
-- and not an Opportunity stage — see waitlist_entries table comment in
-- supabase/schemas/01_tables.sql for the full rationale.
--
-- Hand-authored (no local Postgres available in the session that wrote
-- this migration to run `supabase db diff`) — mirrors the declarative
-- schema changes in 01_tables.sql / 02_functions.sql / 04_triggers.sql /
-- 05_policies.sql exactly. Verify with `npx supabase db diff --local`
-- before trusting this file blindly in an environment where that's
-- possible.

CREATE TABLE "public"."waitlist_entries" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "contact_id" bigint NOT NULL,
    "offer_id" bigint NOT NULL,
    "cohort_id" bigint,
    "status" text NOT NULL DEFAULT 'waiting',
    "joined_at" timestamp with time zone NOT NULL DEFAULT now(),
    "desired_timing" text,
    "notes" text,
    "priority" smallint,
    "source" text,
    "invited_at" timestamp with time zone,
    "converted_at" timestamp with time zone,
    "converted_opportunity_id" bigint,
    "removed_at" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "waitlist_entries_status_check" CHECK (status IN ('waiting', 'invited', 'converted', 'removed')),
    CONSTRAINT "waitlist_entries_source_check" CHECK (source IN ('instagram', 'referral', 'podcast', 'workshop', 'substack', 'google', 'other'))
);

ALTER TABLE "public"."waitlist_entries"
    ADD CONSTRAINT "waitlist_entries_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."waitlist_entries"
    ADD CONSTRAINT "waitlist_entries_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES public.offers(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."waitlist_entries"
    ADD CONSTRAINT "waitlist_entries_cohort_id_fkey" FOREIGN KEY (cohort_id) REFERENCES public.cohorts(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."waitlist_entries"
    ADD CONSTRAINT "waitlist_entries_converted_opportunity_id_fkey" FOREIGN KEY (converted_opportunity_id) REFERENCES public.deals(id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX "waitlist_entries_contact_id_idx" ON public.waitlist_entries USING btree (contact_id);
CREATE INDEX "waitlist_entries_offer_id_idx" ON public.waitlist_entries USING btree (offer_id);
CREATE INDEX "waitlist_entries_cohort_id_idx" ON public.waitlist_entries USING btree (cohort_id);
CREATE INDEX "waitlist_entries_converted_opportunity_id_idx" ON public.waitlist_entries USING btree (converted_opportunity_id);

-- Prevents duplicate active (waiting/invited) entries for the same
-- Contact + Offer + Cohort — see the schema file comment for the
-- coalesce(-1) rationale (NULL cohort_id must collide with itself here).
CREATE UNIQUE INDEX "waitlist_entries_active_unique_idx" ON public.waitlist_entries (contact_id, offer_id, coalesce(cohort_id, -1)) WHERE (status IN ('waiting', 'invited'));

CREATE OR REPLACE FUNCTION "public"."handle_waitlist_entry_saved"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_offer offers%ROWTYPE;
  v_cohort_offer_id bigint;
begin
  select * into v_offer from offers where id = new.offer_id;
  if v_offer.id is null then
    raise exception 'Invalid offer_id %', new.offer_id;
  end if;

  if new.cohort_id is not null then
    select offer_id into v_cohort_offer_id from cohorts where id = new.cohort_id;
    if v_cohort_offer_id is null then
      raise exception 'Invalid cohort_id %', new.cohort_id;
    end if;
    if v_offer.type <> 'group' then
      raise exception 'cohort_id can only be set on a group offer (offer_id %)', new.offer_id;
    end if;
    if v_cohort_offer_id <> new.offer_id then
      raise exception 'cohort_id % does not belong to offer_id %', new.cohort_id, new.offer_id;
    end if;
  end if;

  return new;
end;
$$;

CREATE OR REPLACE TRIGGER "05_handle_waitlist_entry_saved"
    BEFORE INSERT OR UPDATE ON public.waitlist_entries
    FOR EACH ROW EXECUTE FUNCTION public.handle_waitlist_entry_saved();

ALTER TABLE "public"."waitlist_entries" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON public.waitlist_entries FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.waitlist_entries FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON public.waitlist_entries FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Waitlist Entries Delete Policy" ON public.waitlist_entries FOR DELETE TO authenticated USING (true);
