-- Migration: Create customer_details table (kundregister, 1:1 mot companies)
-- Created: 2026-06-11
-- Description: Samlad kundinfo för levererade kunder (feedback #5): avtal,
--              levererad hemsida, lanseringsdatum och referenser till var
--              inloggningsuppgifter förvaras. Egen tabell (inte kolumner på
--              companies) eftersom getOne("companies") läser companies_summary-vyn
--              och nya kolumner där hade krävt DROP/CREATE VIEW i produktion.
--              Helt additiv migration — inga DROP/ALTER.

CREATE TABLE IF NOT EXISTS "public"."customer_details" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- 1:1 mot companies — en kundpost per företag
  "company_id" bigint NOT NULL UNIQUE REFERENCES companies(id) ON DELETE CASCADE,
  -- Levererad hemsida + lanseringsdatum (grund för framtida SEO/statistik-fas)
  "delivered_website_url" text,
  "launch_date" date,
  -- Avtal: lista av { name, signed_date, url, note }
  "agreements" jsonb NOT NULL DEFAULT '[]',
  -- VIKTIGT: credential_refs innehåller ENDAST referenser till var uppgifter
  -- förvaras (t.ex. { label: "Vercel-konto", location: "1Password: Kund X" }).
  -- Lagra ALDRIG lösenord, API-nycklar eller andra hemligheter här.
  "credential_refs" jsonb NOT NULL DEFAULT '[]',
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON COLUMN "public"."customer_details"."credential_refs" IS
  'Endast referenser till var inloggningsuppgifter förvaras — aldrig faktiska lösenord eller nycklar.';

-- Enable RLS
ALTER TABLE "public"."customer_details" ENABLE ROW LEVEL SECURITY;

-- RLS Policies — samma modell som feedback_items: hela teamet läser/skriver.
-- Ingen DELETE-policy: kundposter arkiveras inte härifrån, de följer företaget
-- (ON DELETE CASCADE).
CREATE POLICY "Authenticated can view customer details" ON "public"."customer_details"
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can insert customer details" ON "public"."customer_details"
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update customer details" ON "public"."customer_details"
  FOR UPDATE
  USING (auth.role() = 'authenticated');

-- Index för uppslag per företag (UNIQUE-constrainten ger redan ett index,
-- men vi behåller namngivningen konsekvent med övriga tabeller via constrainten).

-- updated_at-trigger: återanvänd befintlig funktion om den finns, annars skapa.
CREATE OR REPLACE FUNCTION set_customer_details_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_customer_details_updated_at_trigger
BEFORE UPDATE ON "public"."customer_details"
FOR EACH ROW
EXECUTE FUNCTION set_customer_details_updated_at();
