alter table public.sales
    add column if not exists role text not null default 'sales_manager',
    add constraint sales_role_check check (role in ('admin', 'sales_manager', 'lead_researcher', 'viewer'));

update public.sales
set role = case when administrator then 'admin' else role end;

alter table public.companies
    add column if not exists assigned_to_user_id bigint references public.sales(id),
    add column if not exists created_by_user_id bigint references public.sales(id),
    add column if not exists last_updated_by_user_id bigint references public.sales(id),
    add column if not exists research_status text not null default 'new',
    add column if not exists icp_score smallint,
    add column if not exists trigger_reason text,
    add column if not exists ready_for_review boolean not null default false,
    add column if not exists approved_for_instantly boolean not null default false,
    add column if not exists reviewed_by_user_id bigint references public.sales(id),
    add column if not exists review_notes text,
    add constraint companies_research_status_check check (
        research_status in (
            'new',
            'researching',
            'enriched',
            'verified',
            'ready_for_review',
            'approved_for_instantly',
            'needs_fixing',
            'rejected',
            'in_campaign',
            'replied',
            'bad_fit'
        )
    ),
    add constraint companies_icp_score_check check (icp_score is null or (icp_score >= 0 and icp_score <= 100));

alter table public.contacts
    add column if not exists assigned_to_user_id bigint references public.sales(id),
    add column if not exists created_by_user_id bigint references public.sales(id),
    add column if not exists last_updated_by_user_id bigint references public.sales(id),
    add column if not exists research_status text not null default 'new',
    add column if not exists icp_score smallint,
    add column if not exists trigger_reason text,
    add column if not exists email_verified boolean not null default false,
    add column if not exists ready_for_review boolean not null default false,
    add column if not exists approved_for_instantly boolean not null default false,
    add column if not exists reviewed_by_user_id bigint references public.sales(id),
    add column if not exists review_notes text,
    add constraint contacts_research_status_check check (
        research_status in (
            'new',
            'researching',
            'enriched',
            'verified',
            'ready_for_review',
            'approved_for_instantly',
            'needs_fixing',
            'rejected',
            'in_campaign',
            'replied',
            'bad_fit'
        )
    ),
    add constraint contacts_icp_score_check check (icp_score is null or (icp_score >= 0 and icp_score <= 100));

create table if not exists public.daily_research_activities (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.sales(id) on update cascade on delete cascade,
    date date not null,
    companies_added integer not null default 0,
    contacts_found integer not null default 0,
    emails_verified integer not null default 0,
    crm_records_updated integer not null default 0,
    ready_for_instantly integer not null default 0,
    bad_fits_removed integer not null default 0,
    blockers text,
    tomorrow_plan text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (user_id, date)
);

alter table public.daily_research_activities enable row level security;

create or replace function public.current_sale_id() returns bigint
    language plpgsql security definer
    set search_path to ''
    as $$
declare
    sale_id bigint;
begin
    select id into sale_id
    from public.sales
    where user_id = auth.uid()
      and disabled = false;

    return sale_id;
end;
$$;

create or replace function public.current_user_role() returns text
    language plpgsql security definer
    set search_path to ''
    as $$
declare
    user_role text;
begin
    select case when administrator then 'admin' else role end into user_role
    from public.sales
    where user_id = auth.uid()
      and disabled = false;

    return coalesce(user_role, 'viewer');
end;
$$;

create or replace function public.is_admin() returns boolean
    language plpgsql security definer
    set search_path to ''
    as $$
begin
  return exists (
    select 1
    from public.sales
    where user_id = auth.uid()
      and disabled = false
      and (administrator = true or role = 'admin')
  );
end;
$$;

create or replace function public.can_review_luke_output() returns boolean
    language plpgsql security definer
    set search_path to ''
    as $$
begin
  return public.current_user_role() in ('admin', 'sales_manager');
end;
$$;

create or replace function public.set_research_audit_fields() returns trigger
    language plpgsql
    set search_path to 'public'
    as $$
declare
    sale_id bigint;
begin
    sale_id := public.current_sale_id();

    if public.current_user_role() = 'lead_researcher'
       and tg_op = 'UPDATE'
       and (
           new.approved_for_instantly is distinct from old.approved_for_instantly
           or new.research_status = 'approved_for_instantly'
       ) then
        raise exception 'Lead researchers cannot approve leads for Instantly';
    end if;

    if tg_op = 'INSERT' then
        new.created_by_user_id = coalesce(new.created_by_user_id, sale_id);
        new.assigned_to_user_id = coalesce(new.assigned_to_user_id, sale_id);
    end if;

    new.last_updated_by_user_id = sale_id;

    if new.approved_for_instantly = true then
        new.research_status = 'approved_for_instantly';
        new.ready_for_review = true;
        new.reviewed_by_user_id = coalesce(new.reviewed_by_user_id, sale_id);
    elsif new.ready_for_review = true and new.research_status not in ('approved_for_instantly', 'needs_fixing', 'rejected', 'bad_fit', 'in_campaign', 'replied') then
        new.research_status = 'ready_for_review';
    end if;

    return new;
end;
$$;

create or replace function public.set_daily_research_activity_updated_at() returns trigger
    language plpgsql
    set search_path to 'public'
    as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_companies_research_audit_fields on public.companies;
create trigger set_companies_research_audit_fields
    before insert or update on public.companies
    for each row execute function public.set_research_audit_fields();

drop trigger if exists set_contacts_research_audit_fields on public.contacts;
create trigger set_contacts_research_audit_fields
    before insert or update on public.contacts
    for each row execute function public.set_research_audit_fields();

drop trigger if exists set_daily_research_activity_updated_at on public.daily_research_activities;
create trigger set_daily_research_activity_updated_at
    before update on public.daily_research_activities
    for each row execute function public.set_daily_research_activity_updated_at();

create policy "Enable read daily research activities" on public.daily_research_activities
    for select to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager') or user_id = public.current_sale_id());

create policy "Enable insert own daily research activity" on public.daily_research_activities
    for insert to authenticated
    with check (public.current_user_role() in ('admin', 'sales_manager') or (public.current_user_role() = 'lead_researcher' and user_id = public.current_sale_id()));

create policy "Enable update own daily research activity" on public.daily_research_activities
    for update to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager') or (public.current_user_role() = 'lead_researcher' and user_id = public.current_sale_id()))
    with check (public.current_user_role() in ('admin', 'sales_manager') or (public.current_user_role() = 'lead_researcher' and user_id = public.current_sale_id()));

create policy "Enable delete daily research activities for admins" on public.daily_research_activities
    for delete to authenticated
    using (public.current_user_role() = 'admin');

grant select, insert, update, delete on table public.daily_research_activities to authenticated;
grant select, insert, update, delete on table public.daily_research_activities to service_role;
grant usage, select on sequence public.daily_research_activities_id_seq to authenticated;
grant usage, select on sequence public.daily_research_activities_id_seq to service_role;

create or replace view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    co.outreach_status,
    co.last_emailed_at,
    co.last_outreach_at,
    co.instantly_campaign,
    co.assigned_to_user_id,
    co.created_by_user_id,
    co.last_updated_by_user_id,
    co.research_status,
    co.icp_score,
    co.trigger_reason,
    co.email_verified,
    co.ready_for_review,
    co.approved_for_instantly,
    co.reviewed_by_user_id,
    co.review_notes,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    c.website as company_website,
    c.linkedin_url as company_linkedin_url,
    c.size as company_size,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
    left join public.companies c on co.company_id = c.id
group by co.id, c.name, c.website, c.linkedin_url, c.size;

drop policy if exists "Enable read access for authenticated users" on public.companies;
drop policy if exists "Enable insert for authenticated users only" on public.companies;
drop policy if exists "Enable update for authenticated users only" on public.companies;
drop policy if exists "Company Delete Policy" on public.companies;

create policy "Enable read access for authenticated users" on public.companies
    for select to authenticated
    using (
        public.current_user_role() in ('admin', 'sales_manager', 'viewer')
        or assigned_to_user_id = public.current_sale_id()
        or sales_id = public.current_sale_id()
    );

create policy "Enable insert for authenticated users only" on public.companies
    for insert to authenticated
    with check (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and coalesce(assigned_to_user_id, public.current_sale_id()) = public.current_sale_id()
            and approved_for_instantly = false
        )
    );

create policy "Enable update for authenticated users only" on public.companies
    for update to authenticated
    using (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and coalesce(assigned_to_user_id, sales_id) = public.current_sale_id()
        )
    )
    with check (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and coalesce(assigned_to_user_id, sales_id) = public.current_sale_id()
            and approved_for_instantly = false
            and research_status <> 'approved_for_instantly'
        )
    );

create policy "Company Delete Policy" on public.companies
    for delete to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

drop policy if exists "Enable read access for authenticated users" on public.contacts;
drop policy if exists "Enable insert for authenticated users only" on public.contacts;
drop policy if exists "Enable update for authenticated users only" on public.contacts;
drop policy if exists "Contact Delete Policy" on public.contacts;

create policy "Enable read access for authenticated users" on public.contacts
    for select to authenticated
    using (
        public.current_user_role() in ('admin', 'sales_manager', 'viewer')
        or assigned_to_user_id = public.current_sale_id()
        or sales_id = public.current_sale_id()
        or exists (
            select 1
            from public.companies c
            where c.id = contacts.company_id
              and c.assigned_to_user_id = public.current_sale_id()
        )
    );

create policy "Enable insert for authenticated users only" on public.contacts
    for insert to authenticated
    with check (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and coalesce(assigned_to_user_id, public.current_sale_id()) = public.current_sale_id()
            and approved_for_instantly = false
        )
    );

create policy "Enable update for authenticated users only" on public.contacts
    for update to authenticated
    using (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and coalesce(assigned_to_user_id, sales_id) = public.current_sale_id()
        )
    )
    with check (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and coalesce(assigned_to_user_id, sales_id) = public.current_sale_id()
            and approved_for_instantly = false
            and research_status <> 'approved_for_instantly'
        )
    );

create policy "Contact Delete Policy" on public.contacts
    for delete to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

drop policy if exists "Enable insert for authenticated users only" on public.deals;
drop policy if exists "Enable update for authenticated users only" on public.deals;
drop policy if exists "Deals Delete Policy" on public.deals;

create policy "Enable insert for authenticated users only" on public.deals
    for insert to authenticated
    with check (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Enable update for authenticated users only" on public.deals
    for update to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'))
    with check (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Deals Delete Policy" on public.deals
    for delete to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

drop policy if exists "Task Update Policy" on public.tasks;
drop policy if exists "Task Delete Policy" on public.tasks;

create policy "Task Update Policy" on public.tasks
    for update to authenticated
    using (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and sales_id = public.current_sale_id()
        )
    );

create policy "Task Delete Policy" on public.tasks
    for delete to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

drop policy if exists "Enable insert for authenticated users only" on public.outreach_events;
drop policy if exists "Outreach Events Update Policy" on public.outreach_events;
drop policy if exists "Outreach Events Delete Policy" on public.outreach_events;

create policy "Enable insert for authenticated users only" on public.outreach_events
    for insert to authenticated
    with check (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Outreach Events Update Policy" on public.outreach_events
    for update to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Outreach Events Delete Policy" on public.outreach_events
    for delete to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

drop policy if exists "Enable insert for authenticated users only" on public.contact_notes;
drop policy if exists "Contact Notes Update policy" on public.contact_notes;
drop policy if exists "Contact Notes Delete Policy" on public.contact_notes;

create policy "Enable insert for authenticated users only" on public.contact_notes
    for insert to authenticated
    with check (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and exists (
                select 1
                from public.contacts c
                where c.id = contact_notes.contact_id
                  and coalesce(c.assigned_to_user_id, c.sales_id) = public.current_sale_id()
            )
        )
    );

create policy "Contact Notes Update policy" on public.contact_notes
    for update to authenticated
    using (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and exists (
                select 1
                from public.contacts c
                where c.id = contact_notes.contact_id
                  and coalesce(c.assigned_to_user_id, c.sales_id) = public.current_sale_id()
            )
        )
    );

create policy "Contact Notes Delete Policy" on public.contact_notes
    for delete to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

drop policy if exists "Enable insert for authenticated users only" on public.deal_notes;
drop policy if exists "Deal Notes Update Policy" on public.deal_notes;
drop policy if exists "Deal Notes Delete Policy" on public.deal_notes;

create policy "Enable insert for authenticated users only" on public.deal_notes
    for insert to authenticated
    with check (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Deal Notes Update Policy" on public.deal_notes
    for update to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Deal Notes Delete Policy" on public.deal_notes
    for delete to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

drop policy if exists "Enable insert for authenticated users only" on public.tags;
drop policy if exists "Enable update for authenticated users only" on public.tags;
drop policy if exists "Enable delete for authenticated users only" on public.tags;

create policy "Enable insert for authenticated users only" on public.tags
    for insert to authenticated
    with check (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Enable update for authenticated users only" on public.tags
    for update to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Enable delete for authenticated users only" on public.tags
    for delete to authenticated
    using (public.current_user_role() = 'admin');

drop policy if exists "Enable insert for authenticated users only" on public.tasks;

create policy "Enable insert for authenticated users only" on public.tasks
    for insert to authenticated
    with check (
        public.current_user_role() in ('admin', 'sales_manager')
        or (
            public.current_user_role() = 'lead_researcher'
            and sales_id = public.current_sale_id()
        )
    );
