-- Client + Session Operations: Service Period model correction.
--
-- Human acceptance (and Leif's own business-model correction) replaced
-- the calendar-month/anniversary "service period" with the real Living
-- Example model: 12 total 1:1 session opportunities, grouped into 4
-- Service Periods of exactly 3, defined by the CHRONOLOGICAL SEQUENCE of
-- qualifying Year Planning windows after the Enrollment's own service
-- start date — never by elapsed calendar days. A Service Period can
-- legitimately span more or less than a literal month; a calendar gap
-- (holiday, travel) never consumes one of the 12 slots or invents a
-- phantom one. See this slice's own report for the full reasoning,
-- including the historical-stability question this table's own
-- snapshot-at-assignment design answers (an already-assigned slot's
-- ordinal, Service Period number, and displayed dates are frozen against
-- any LATER edit to the source calendar event).

create table "public"."enrollment_expected_sessions" (
    "id" bigint generated by default as identity primary key,
    "enrollment_id" bigint not null,
    "source_window_id" bigint not null,
    "ordinal" smallint not null,
    "window_start" date not null,
    "window_end" date not null,
    "raw_title" text not null,
    "created_at" timestamp with time zone not null default now(),
    constraint "enrollment_expected_sessions_ordinal_check" check ((ordinal >= 1) and (ordinal <= 12))
);

create unique index "enrollment_expected_sessions_enrollment_ordinal_idx" on "public"."enrollment_expected_sessions" ("enrollment_id", "ordinal");
create unique index "enrollment_expected_sessions_enrollment_window_idx" on "public"."enrollment_expected_sessions" ("enrollment_id", "source_window_id");

alter table "public"."enrollment_expected_sessions" add constraint "enrollment_expected_sessions_enrollment_id_fkey" foreign key ("enrollment_id") references "public"."enrollments"("id") on update cascade on delete cascade;
alter table "public"."enrollment_expected_sessions" add constraint "enrollment_expected_sessions_source_window_id_fkey" foreign key ("source_window_id") references "public"."expected_session_windows"("id") on update cascade on delete cascade;

alter table "public"."enrollment_expected_sessions" enable row level security;

create policy "Enable read access for authenticated users" on "public"."enrollment_expected_sessions" for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."enrollment_expected_sessions" for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."enrollment_expected_sessions" for update to authenticated using (true) with check (true);
create policy "Enrollment Expected Sessions Delete Policy" on "public"."enrollment_expected_sessions" for delete to authenticated using (true);

grant all on table "public"."enrollment_expected_sessions" to "anon";
grant all on table "public"."enrollment_expected_sessions" to "authenticated";
grant all on table "public"."enrollment_expected_sessions" to "service_role";

grant all on sequence "public"."enrollment_expected_sessions_id_seq" to "anon";
grant all on sequence "public"."enrollment_expected_sessions_id_seq" to "authenticated";
grant all on sequence "public"."enrollment_expected_sessions_id_seq" to "service_role";

-- Backfill: one enrollment_expected_sessions row per (enrollment, window)
-- pair any EXISTING client_session_cadence_issues row already references
-- — a no-op on a database with none (a fresh environment), and on the
-- linked project only ever touches the two known disposable fixture
-- rows (contact 24's own issues), never real client data. Ordinal here
-- is assigned by window_start order purely to keep the new NOT NULL/
-- unique constraints satisfied for this pre-existing data; it carries no
-- real Service Period meaning for these disposable rows.
insert into "public"."enrollment_expected_sessions" (enrollment_id, source_window_id, ordinal, window_start, window_end, raw_title)
select distinct
    ci.enrollment_id,
    ci.expected_session_window_id,
    row_number() over (partition by ci.enrollment_id order by w.window_start) as ordinal,
    w.window_start,
    w.window_end,
    w.raw_title
from "public"."client_session_cadence_issues" ci
join "public"."expected_session_windows" w on w.id = ci.expected_session_window_id;

alter table "public"."client_session_cadence_issues" add column "enrollment_expected_session_id" bigint;

update "public"."client_session_cadence_issues" ci
set "enrollment_expected_session_id" = ees.id
from "public"."enrollment_expected_sessions" ees
where ees.enrollment_id = ci.enrollment_id
  and ees.source_window_id = ci.expected_session_window_id;

alter table "public"."client_session_cadence_issues" alter column "enrollment_expected_session_id" set not null;

drop index "public"."client_session_cadence_issues_enrollment_window_idx";
alter table "public"."client_session_cadence_issues" drop constraint "client_session_cadence_issues_window_id_fkey";
alter table "public"."client_session_cadence_issues" drop column "expected_session_window_id";

alter table "public"."client_session_cadence_issues" add constraint "client_session_cadence_issues_slot_id_fkey" foreign key ("enrollment_expected_session_id") references "public"."enrollment_expected_sessions"("id") on update cascade on delete cascade;
create unique index "client_session_cadence_issues_enrollment_slot_idx" on "public"."client_session_cadence_issues" ("enrollment_id", "enrollment_expected_session_id");
