--
-- supabase/migrations/20260512000003_time_billing.sql
--
-- Phase 4: Time Billing Module
-- Adds default_hourly_rate_szl to sales, creates invoices and time_entries tables.
--

-- Add default hourly rate to users/sales
alter table public.sales
    add column if not exists default_hourly_rate_szl numeric(10,2);

-- Invoices (must exist before time_entries for the FK)
create table public.invoices (
    id bigint generated by default as identity primary key,
    invoice_number text not null,
    company_id bigint not null,
    period_start date not null,
    period_end date not null,
    subtotal_szl numeric(10,2) not null default 0,
    vat_szl numeric(10,2) not null default 0,
    total_szl numeric(10,2) not null default 0,
    status text not null default 'DRAFT',
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint invoices_invoice_number_unique unique (invoice_number)
);

alter table public.invoices
    add constraint invoices_company_id_fkey
    foreign key (company_id) references public.companies(id) on delete cascade;

create index invoices_company_id_idx on public.invoices using btree (company_id);
create index invoices_status_idx on public.invoices using btree (status);

-- Time entries
create table public.time_entries (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    contact_id bigint,
    entry_date date not null,
    hours numeric(5,2) not null,
    billable boolean not null default true,
    hourly_rate_szl numeric(10,2) not null,
    service_line text not null,
    description text not null default '',
    linked_filing_id bigint,
    invoice_id bigint,
    created_at timestamp with time zone not null default now()
);

alter table public.time_entries
    add constraint time_entries_company_id_fkey
    foreign key (company_id) references public.companies(id) on delete cascade;

alter table public.time_entries
    add constraint time_entries_contact_id_fkey
    foreign key (contact_id) references public.contacts(id) on delete set null;

alter table public.time_entries
    add constraint time_entries_linked_filing_id_fkey
    foreign key (linked_filing_id) references public.compliance_filings(id) on delete set null;

alter table public.time_entries
    add constraint time_entries_invoice_id_fkey
    foreign key (invoice_id) references public.invoices(id) on delete set null;

create index time_entries_company_id_idx on public.time_entries using btree (company_id);
create index time_entries_entry_date_idx on public.time_entries using btree (entry_date);
create index time_entries_invoice_id_idx on public.time_entries using btree (invoice_id);
