-- Migration: Create website_snapshots table + monthly pg_cron job
-- Created: 2026-06-11
-- Description: Fas 2 av kundregistret (feedback #5): tidsserie med hemsidestatistik
--              per företag — PageSpeed (prestanda/SEO), egen SEO/AI-sök-crawl,
--              Google Business-profil och (hybrid) Search Console-data, plus en
--              regelbaserad brist-analys för merförsäljning. Fylls av edge-funktionen
--              analyze_website, manuellt via Kund-fliken eller månadsvis via pg_cron.
--              Helt additiv migration — inga DROP/ALTER på befintliga objekt.

CREATE TABLE IF NOT EXISTS "public"."website_snapshots" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  "fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
  -- source: 'manual' (knappen på Kund-fliken) eller 'cron' (månadsjobbet)
  "source" text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'cron')),
  -- Den URL som analyserades (delivered_website_url ?? companies.website)
  "url" text NOT NULL,
  -- PageSpeed Insights (0–100); null om källan felade
  "performance_score" integer,
  "seo_score" integer,
  -- Detaljer per källa. Varje källa kan vara null om hämtningen felade —
  -- ett källfel fäller aldrig hela analysen.
  "pagespeed" jsonb,          -- { lcp_ms, cls, inp_ms/tbt_ms, opportunities: [{id, title, savings_ms}] }
  "seo_checks" jsonb,         -- { title, meta_description, og_tags, schema_org, sitemap, robots, llms_txt, h1 }
  "business_profile" jsonb,   -- { found, rating, reviews_count, place_id } | { found: false }
  "search_console" jsonb,     -- null = ingen GSC-åtkomst; annars { clicks, impressions, position, top_queries }
  -- Brist-analys: [{ key, severity: 'high'|'medium'|'low', title, description, service }]
  "findings" jsonb NOT NULL DEFAULT '[]',
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE "public"."website_snapshots" ENABLE ROW LEVEL SECURITY;

-- Hela teamet läser; endast insert (snapshots är immutabla — historik ändras inte).
-- Edge-funktionen skriver via service role och påverkas inte av RLS.
CREATE POLICY "Authenticated can view website snapshots" ON "public"."website_snapshots"
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can insert website snapshots" ON "public"."website_snapshots"
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE INDEX idx_website_snapshots_company_fetched
  ON website_snapshots(company_id, fetched_at DESC);

-- ============================================================================
-- Månadsvis automatisk uppdatering via pg_cron + pg_net
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- SECURITY DEFINER-funktion som anropar analyze_website i cron-läge.
-- Läser supabase_url + cron_secret från vault (samma mönster som
-- proposal_automation). Saknas något → varna och hoppa över, blockera aldrig.
CREATE OR REPLACE FUNCTION public.run_monthly_website_snapshots()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  edge_function_url text;
  cron_secret text;
BEGIN
  SELECT decrypted_secret INTO edge_function_url
  FROM vault.decrypted_secrets
  WHERE name = 'supabase_url'
  LIMIT 1;

  SELECT decrypted_secret INTO cron_secret
  FROM vault.decrypted_secrets
  WHERE name = 'cron_secret'
  LIMIT 1;

  IF edge_function_url IS NULL OR cron_secret IS NULL THEN
    RAISE WARNING 'run_monthly_website_snapshots: missing supabase_url or cron_secret in vault — skipping run';
    RETURN;
  END IF;

  PERFORM net.http_post(
    url     := edge_function_url || '/functions/v1/analyze_website',
    body    := jsonb_build_object('cron', true),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', cron_secret
    ),
    timeout_milliseconds := 10000
  );
END;
$$;

-- Kör 06:00 den 1:a varje månad. cron.schedule är idempotent på jobbnamn.
SELECT cron.schedule(
  'monthly-website-snapshots',
  '0 6 1 * *',
  $$SELECT public.run_monthly_website_snapshots();$$
);
