-- The sales state machine, given one authority each.
--
-- Audit #2 found the rule that decides whether an Opportunity is still
-- being sold written out by hand about nine times, a stage column with no
-- CHECK at all, outcome changes with no history whatsoever, and a stage
-- value — 'onboarding' — that the modern architecture does not use but
-- that live code could still write.
--
-- Four things land here, and nothing reinterprets a single historical row.

begin;

-- ---------------------------------------------------------------------
-- 1. What "still being sold" means, in one place
-- ---------------------------------------------------------------------
-- An Opportunity is one sales attempt for one Offer. While the attempt is
-- running there is no outcome; won is the successful end; any outcome at
-- all is an end. archived_at stays in the predicate because it still
-- exists, even though nothing currently sets it.
--
-- Immutable, so it can be used in an index or a generated column later
-- without the definition drifting from the nine copies it replaces.
create or replace function public.deal_is_active(
  p_archived_at timestamptz,
  p_stage text,
  p_outcome text
) returns boolean
  language sql
  immutable
  set search_path to 'public'
as $$
  select p_archived_at is null
     and p_stage is distinct from 'won'
     and p_outcome is null;
$$;

comment on function public.deal_is_active(timestamptz, text, text) is
  'The canonical active-sales predicate. One sales attempt is active while it has not been won and has not ended. Mirrored in TypeScript by deals/dealActivity.ts, which is tested for equivalence against this function.';

-- ---------------------------------------------------------------------
-- 2. Outcome changes stop being unrecorded
-- ---------------------------------------------------------------------
-- deal_stage_events has existed for stage the whole time; the far more
-- consequential field had nothing. Shaped like its sibling, with one
-- deliberate difference: deal_stage_events defaults entered_at to now(),
-- which means a backfilled row claims to have happened the day the
-- migration ran. Here occurred_at is nullable and stays NULL when nobody
-- knows, recorded_at says when we wrote it down, and `reconstructed`
-- admits which of the two a row is.
create table if not exists public.deal_outcome_events (
  id bigint generated by default as identity primary key,
  opportunity_id bigint not null references public.deals (id) on delete cascade,
  old_outcome text,
  new_outcome text,
  exit_reason text,
  -- When the business event happened. NULL means unknown, never today.
  occurred_at timestamptz,
  recorded_at timestamptz not null default now(),
  source text not null default 'app',
  reconstructed boolean not null default false,
  note text
);

create index if not exists deal_outcome_events_opportunity_idx
  on public.deal_outcome_events (opportunity_id);

comment on table public.deal_outcome_events is
  'Append-only history of how sales attempts ended. A reconstructed row carries occurred_at = NULL rather than the migration date: not knowing when something happened is a fact, and inventing a timestamp would destroy it.';
comment on column public.deal_outcome_events.occurred_at is
  'When the outcome actually changed, where that is known. NULL on reconstructed history — deliberately not the backfill date.';
comment on column public.deal_outcome_events.reconstructed is
  'True when this row was inferred from current state rather than observed as it happened.';

-- A trigger rather than a convention, because the alternative is hoping
-- every future writer remembers — and the nine hand-written copies of the
-- active predicate are what that hope looks like after a year.
create or replace function public.record_deal_outcome_event()
  returns trigger
  language plpgsql
  set search_path to 'public'
as $$
begin
  if tg_op = 'INSERT' then
    if new.outcome is not null then
      insert into public.deal_outcome_events
        (opportunity_id, old_outcome, new_outcome, exit_reason, occurred_at, source)
      values (new.id, null, new.outcome, new.exit_reason, now(), 'app');
    end if;
  elsif new.outcome is distinct from old.outcome
     or (new.outcome is not null and new.exit_reason is distinct from old.exit_reason) then
    insert into public.deal_outcome_events
      (opportunity_id, old_outcome, new_outcome, exit_reason, occurred_at, source)
    values (new.id, old.outcome, new.outcome, new.exit_reason, now(), 'app');
  end if;
  return new;
end;
$$;

drop trigger if exists on_deal_outcome_changed on public.deals;
create trigger on_deal_outcome_changed
  after insert or update of outcome, exit_reason on public.deals
  for each row execute function public.record_deal_outcome_event();

-- ---------------------------------------------------------------------
-- 3. The stage vocabulary, including the legacy value it must tolerate
-- ---------------------------------------------------------------------
-- Every live value already fits; this asserts it rather than assuming it.
do $$
declare
  v_unexpected text;
begin
  select string_agg(distinct stage, ', ') into v_unexpected
  from public.deals
  where stage not in ('interested', 'application_received', 'approved',
                      'call_booked', 'decision', 'won', 'onboarding');
  if v_unexpected is not null then
    raise exception 'live stages outside the vocabulary: %', v_unexpected;
  end if;
end $$;

alter table public.deals drop constraint if exists deals_stage_check;
alter table public.deals
  add constraint deals_stage_check check (
    stage in (
      'interested', 'application_received', 'approved', 'call_booked',
      'decision', 'won',
      -- LEGACY STORAGE ONLY. Fourteen rows were mechanically renamed from
      -- 'committed' and never made a sale. The Onboarding column on the
      -- board is synthetic — Won, with an Enrollment, with post-sale setup
      -- unfinished — and has nothing to do with this value. Permitted so
      -- those rows can keep existing and can later be repaired out; new
      -- writes are refused by the trigger below.
      'onboarding'
    )
  );

-- ---------------------------------------------------------------------
-- 4. Nothing new ever becomes a persisted 'onboarding'
-- ---------------------------------------------------------------------
-- A CHECK cannot express this, because it has to permit the fourteen rows
-- that already hold the value while refusing any new arrival at it.
create or replace function public.guard_persisted_onboarding_stage()
  returns trigger
  language plpgsql
  set search_path to 'public'
as $$
begin
  if new.stage = 'onboarding'
     and (tg_op = 'INSERT' or old.stage is distinct from 'onboarding') then
    raise exception
      'stage "onboarding" is legacy storage and cannot be written. A sale that succeeded is stage = won; the Onboarding column is derived from Won plus an Enrollment plus unfinished setup.'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

drop trigger if exists guard_deal_onboarding_stage on public.deals;
create trigger guard_deal_onboarding_stage
  before insert or update of stage on public.deals
  for each row execute function public.guard_persisted_onboarding_stage();

-- ---------------------------------------------------------------------
-- 5. Reconstructed history for the attempts that already ended
-- ---------------------------------------------------------------------
-- Auditability, not reinterpretation. Nothing about these Opportunities
-- changes; they simply stop having no recorded ending at all.
insert into public.deal_outcome_events
  (opportunity_id, old_outcome, new_outcome, exit_reason,
   occurred_at, source, reconstructed, note)
select d.id, null, d.outcome, d.exit_reason,
       null, 'import', true,
       'Reconstructed from the Opportunity''s current outcome when outcome history was introduced. When this ending happened is not recorded anywhere, so occurred_at is null rather than the date of this migration.'
from public.deals d
where d.outcome is not null
  and not exists (
    select 1 from public.deal_outcome_events e where e.opportunity_id = d.id
  );

do $$
declare
  v_terminal int;
  v_covered int;
begin
  select count(*) into v_terminal from public.deals where outcome is not null;
  select count(distinct opportunity_id) into v_covered from public.deal_outcome_events;
  if v_covered <> v_terminal then
    raise exception 'outcome history covers % of % terminal opportunities', v_covered, v_terminal;
  end if;
  if exists (select 1 from public.deal_outcome_events
             where reconstructed and occurred_at is not null) then
    raise exception 'a reconstructed event was given an occurrence time';
  end if;
end $$;

commit;
