-- Create custom_field_definitions table
create table if not exists "public"."custom_field_definitions" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "workspace_id" bigint not null references workspaces(id) on delete cascade,
    "entity_type" text not null check (entity_type in ('contact', 'company', 'deal')),
    "key" text not null,
    "label" text not null,
    "data_type" text not null check (data_type in ('string', 'number', 'date', 'boolean', 'enum', 'multi_enum', 'url', 'email', 'phone')),
    "input_type" text not null check (input_type in ('text', 'textarea', 'number', 'date', 'checkbox', 'select', 'multiselect', 'url', 'email', 'phone')),
    "is_required" boolean not null default false,
    "is_filterable" boolean not null default true,
    "is_active" boolean not null default true,
    "sort_order" int not null default 0,
    "options" jsonb default '[]'::jsonb,
    "default_value" jsonb default null,
    "validation_rules" jsonb default '{}'::jsonb,
    "help_text" text default null,
    unique(workspace_id, entity_type, key)
);

alter table "public"."custom_field_definitions" enable row level security;

-- Add custom_fields JSONB column to entity tables
alter table "public"."companies" add column if not exists "custom_fields" jsonb default '{}'::jsonb;
alter table "public"."contacts" add column if not exists "custom_fields" jsonb default '{}'::jsonb;
alter table "public"."deals" add column if not exists "custom_fields" jsonb default '{}'::jsonb;

-- Create GIN indexes for fast JSON queries
create index if not exists companies_custom_fields_idx on "public"."companies" using gin (custom_fields);
create index if not exists contacts_custom_fields_idx on "public"."contacts" using gin (custom_fields);
create index if not exists deals_custom_fields_idx on "public"."deals" using gin (custom_fields);

-- Create index on custom_field_definitions
create index if not exists custom_field_definitions_workspace_entity_idx
  on "public"."custom_field_definitions"(workspace_id, entity_type, is_active);

-- RLS policies for custom_field_definitions
create policy "Users can view custom field definitions in their workspace"
  on custom_field_definitions for select
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

create policy "Admins can create custom field definitions"
  on custom_field_definitions for insert
  with check (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid() and administrator = true
    )
  );

create policy "Admins can update custom field definitions"
  on custom_field_definitions for update
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid() and administrator = true
    )
  );

create policy "Admins can delete custom field definitions"
  on custom_field_definitions for delete
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid() and administrator = true
    )
  );

-- Migrate hardcoded fields to custom field definitions
do $$
declare
  default_workspace_id bigint;
begin
  select id into default_workspace_id from workspaces where slug = 'default';

  -- Contact gender field
  insert into custom_field_definitions (workspace_id, entity_type, key, label, data_type, input_type, is_filterable, sort_order, options)
  values (
    default_workspace_id,
    'contact',
    'gender',
    'Gender',
    'enum',
    'select',
    true,
    1,
    '["Male", "Female", "Non-binary", "Prefer not to say"]'::jsonb
  )
  on conflict (workspace_id, entity_type, key) do nothing;

  -- Company size field
  insert into custom_field_definitions (workspace_id, entity_type, key, label, data_type, input_type, is_filterable, sort_order, options)
  values (
    default_workspace_id,
    'company',
    'size',
    'Company Size',
    'enum',
    'select',
    true,
    1,
    '[
      {"value": 1, "label": "Self-employed"},
      {"value": 10, "label": "2-10"},
      {"value": 50, "label": "11-50"},
      {"value": 250, "label": "51-250"},
      {"value": 500, "label": "251-500"},
      {"value": 1000, "label": "500+"}
    ]'::jsonb
  )
  on conflict (workspace_id, entity_type, key) do nothing;

  -- Company sector field
  insert into custom_field_definitions (workspace_id, entity_type, key, label, data_type, input_type, is_filterable, sort_order, options)
  values (
    default_workspace_id,
    'company',
    'sector',
    'Industry Sector',
    'enum',
    'select',
    true,
    2,
    '[
      "Communication",
      "Energy",
      "Financials",
      "Health Care",
      "Industrials",
      "Information Technology",
      "Manufacturing",
      "Materials",
      "Professional Services",
      "Real Estate",
      "Utilities",
      "Other"
    ]'::jsonb
  )
  on conflict (workspace_id, entity_type, key) do nothing;

end $$;

-- Function to update updated_at timestamp
create or replace function update_custom_field_definition_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_custom_field_definition_updated_at
  before update on custom_field_definitions
  for each row
  execute function update_custom_field_definition_updated_at();
