-- Client Offboarding slice: completes the fulfillment lifecycle
-- (onboarding -> active -> offboarding -> completed / Past Client).
-- Mirrors the proven Contracts + Onboarding architecture exactly (see
-- supabase/schemas/01_tables.sql / 02_functions.sql / 04_triggers.sql for
-- the full rationale comments this migration reflects) — offer-scoped
-- requirement templates, snapshotted onto the Enrollment the moment
-- offboarding genuinely starts, one Task per required item, a DB-level
-- guard against completing with incomplete requirements, and the
-- smallest append-only Enrollment lifecycle history. Won stays terminal
-- sales state; offboarding/completion is a fulfillment-lifecycle concern
-- only.

--
-- Tables
--

create table public.offboarding_requirement_templates (
    id bigint generated by default as identity primary key,
    offer_id bigint not null,
    key text not null,
    label text not null,
    task_text_template text not null,
    is_required boolean not null default true,
    sort_order smallint not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (offer_id, key)
);

create table public.enrollment_offboarding_items (
    id bigint generated by default as identity primary key,
    enrollment_id bigint not null,
    requirement_key text not null,
    label text not null,
    task_text_template text not null,
    is_required boolean not null,
    sort_order smallint not null default 0,
    status text not null default 'pending',
    completed_at timestamp with time zone,
    external_ref text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint enrollment_offboarding_items_status_check check (status in ('pending', 'done')),
    unique (enrollment_id, requirement_key)
);

create table public.enrollment_status_events (
    id bigint generated by default as identity primary key,
    enrollment_id bigint not null,
    status text not null,
    entered_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now()
);

alter table public.tasks
    add column offboarding_item_id bigint;

--
-- Foreign keys
--

alter table public.offboarding_requirement_templates
    add constraint offboarding_requirement_templates_offer_id_fkey foreign key (offer_id) references public.offers(id) on update cascade on delete cascade;

alter table public.enrollment_offboarding_items
    add constraint enrollment_offboarding_items_enrollment_id_fkey foreign key (enrollment_id) references public.enrollments(id) on update cascade on delete cascade;

alter table public.enrollment_status_events
    add constraint enrollment_status_events_enrollment_id_fkey foreign key (enrollment_id) references public.enrollments(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_offboarding_item_id_fkey foreign key (offboarding_item_id) references public.enrollment_offboarding_items(id) on update cascade on delete set null;

--
-- Indexes
--

create index offboarding_requirement_templates_offer_id_idx on public.offboarding_requirement_templates using btree (offer_id);
create index enrollment_offboarding_items_enrollment_id_idx on public.enrollment_offboarding_items using btree (enrollment_id);
create index enrollment_status_events_enrollment_id_idx on public.enrollment_status_events using btree (enrollment_id);
create index tasks_offboarding_item_id_idx on public.tasks using btree (offboarding_item_id);

--
-- Row Level Security
--

alter table public.offboarding_requirement_templates enable row level security;
alter table public.enrollment_offboarding_items enable row level security;
alter table public.enrollment_status_events enable row level security;

create policy "Enable read access for authenticated users" on public.offboarding_requirement_templates for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.offboarding_requirement_templates for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.offboarding_requirement_templates for update to authenticated using (true) with check (true);
create policy "Offboarding Requirement Templates Delete Policy" on public.offboarding_requirement_templates for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.enrollment_offboarding_items for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.enrollment_offboarding_items for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.enrollment_offboarding_items for update to authenticated using (true) with check (true);
create policy "Enrollment Offboarding Items Delete Policy" on public.enrollment_offboarding_items for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.enrollment_status_events for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.enrollment_status_events for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.enrollment_status_events for update to authenticated using (true) with check (true);
create policy "Enrollment Status Events Delete Policy" on public.enrollment_status_events for delete to authenticated using (true);

--
-- Grants
--

grant all on table public.offboarding_requirement_templates to anon;
grant all on table public.offboarding_requirement_templates to authenticated;
grant all on table public.offboarding_requirement_templates to service_role;

grant all on table public.enrollment_offboarding_items to anon;
grant all on table public.enrollment_offboarding_items to authenticated;
grant all on table public.enrollment_offboarding_items to service_role;

grant all on table public.enrollment_status_events to anon;
grant all on table public.enrollment_status_events to authenticated;
grant all on table public.enrollment_status_events to service_role;

grant all on sequence public.offboarding_requirement_templates_id_seq to anon;
grant all on sequence public.offboarding_requirement_templates_id_seq to authenticated;
grant all on sequence public.offboarding_requirement_templates_id_seq to service_role;

grant all on sequence public.enrollment_offboarding_items_id_seq to anon;
grant all on sequence public.enrollment_offboarding_items_id_seq to authenticated;
grant all on sequence public.enrollment_offboarding_items_id_seq to service_role;

grant all on sequence public.enrollment_status_events_id_seq to anon;
grant all on sequence public.enrollment_status_events_id_seq to authenticated;
grant all on sequence public.enrollment_status_events_id_seq to service_role;

--
-- Functions
--

-- Replaces the existing function to also validate offboarding_item_id
-- consistency, alongside the pre-existing onboarding_item_id check.
CREATE OR REPLACE FUNCTION "public"."set_task_enrollment_id_consistency"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_item_enrollment_id bigint;
begin
  if new.onboarding_item_id is not null then
    select enrollment_id into v_item_enrollment_id
      from enrollment_onboarding_items where id = new.onboarding_item_id;
    if v_item_enrollment_id is null then
      raise exception 'Invalid onboarding_item_id %', new.onboarding_item_id;
    end if;
    if new.enrollment_id is null then
      new.enrollment_id := v_item_enrollment_id;
    elsif new.enrollment_id <> v_item_enrollment_id then
      raise exception 'enrollment_id % does not match onboarding_item_id %''s own enrollment_id %',
        new.enrollment_id, new.onboarding_item_id, v_item_enrollment_id;
    end if;
  end if;
  if new.offboarding_item_id is not null then
    select enrollment_id into v_item_enrollment_id
      from enrollment_offboarding_items where id = new.offboarding_item_id;
    if v_item_enrollment_id is null then
      raise exception 'Invalid offboarding_item_id %', new.offboarding_item_id;
    end if;
    if new.enrollment_id is null then
      new.enrollment_id := v_item_enrollment_id;
    elsif new.enrollment_id <> v_item_enrollment_id then
      raise exception 'enrollment_id % does not match offboarding_item_id %''s own enrollment_id %',
        new.enrollment_id, new.offboarding_item_id, v_item_enrollment_id;
    end if;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."enforce_enrollment_lifecycle_sequence"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_old_rank int;
  v_new_rank int;
begin
  v_old_rank := case old.status
    when 'onboarding' then 0
    when 'active' then 1
    when 'offboarding' then 2
    when 'completed' then 3
  end;
  v_new_rank := case new.status
    when 'onboarding' then 0
    when 'active' then 1
    when 'offboarding' then 2
    when 'completed' then 3
  end;
  if v_new_rank > v_old_rank + 1 then
    raise exception 'Cannot transition enrollment % directly from % to % — the fulfillment lifecycle (onboarding -> active -> offboarding -> completed) cannot skip a stage', new.id, old.status, new.status;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_enrollment_offboarding_started"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_offer_id bigint;
  v_contact_id bigint;
  v_contact_name text;
  v_item record;
begin
  if new.status = 'offboarding' and old.status = 'active' then
    select d.offer_id, d.contact_id into v_offer_id, v_contact_id
      from deals d where d.id = new.opportunity_id;

    select trim(both ' ' from coalesce(first_name, '') || ' ' || coalesce(last_name, ''))
      into v_contact_name
      from contacts where id = v_contact_id;
    if v_contact_name is null or v_contact_name = '' then
      select name into v_contact_name from deals where id = new.opportunity_id;
    end if;

    for v_item in
      insert into enrollment_offboarding_items
        (enrollment_id, requirement_key, label, task_text_template, is_required, sort_order)
      select new.id, t.key, t.label, t.task_text_template, t.is_required, t.sort_order
      from offboarding_requirement_templates t
      where t.offer_id = v_offer_id and t.is_active
      returning id, is_required, task_text_template
    loop
      if v_item.is_required then
        insert into tasks (contact_id, type, text, due_date, status, enrollment_id, offboarding_item_id)
        values (
          v_contact_id,
          'offboarding_item',
          replace(v_item.task_text_template, '{name}', v_contact_name),
          now() + interval '3 days',
          'pending',
          new.id,
          v_item.id
        );
      end if;
    end loop;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."sync_offboarding_item_from_task"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  if new.offboarding_item_id is null then
    return new;
  end if;

  if new.done_date is not null and old.done_date is null then
    update enrollment_offboarding_items
      set status = 'done', completed_at = coalesce(completed_at, new.done_date), updated_at = now()
      where id = new.offboarding_item_id and status <> 'done';
  elsif new.done_date is null and old.done_date is not null then
    update enrollment_offboarding_items
      set status = 'pending', completed_at = null, updated_at = now()
      where id = new.offboarding_item_id and status = 'done';
  end if;

  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."enforce_enrollment_completion_requirements"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  if new.status = 'completed' and old.status = 'offboarding' then
    if exists (
      select 1 from enrollment_offboarding_items
      where enrollment_id = new.id and is_required and status <> 'done'
    ) then
      raise exception 'Cannot complete enrollment %: required offboarding items incomplete', new.id;
    end if;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."record_enrollment_status_event"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into enrollment_status_events (enrollment_id, status, entered_at)
    values (new.id, new.status, now());
  end if;
  return new;
end;
$$;

--
-- Triggers
--

create or replace trigger enforce_enrollment_lifecycle_sequence_trigger
    before update on public.enrollments
    for each row execute function public.enforce_enrollment_lifecycle_sequence();

create or replace trigger on_enrollment_offboarding_started
    after update on public.enrollments
    for each row execute function public.handle_enrollment_offboarding_started();

create or replace trigger on_task_offboarding_sync
    after update on public.tasks
    for each row
    when (old.done_date is distinct from new.done_date)
    execute function public.sync_offboarding_item_from_task();

create or replace trigger enforce_enrollment_completion_requirements_trigger
    before update on public.enrollments
    for each row execute function public.enforce_enrollment_completion_requirements();

create or replace trigger on_enrollment_status_event
    after insert or update on public.enrollments
    for each row execute function public.record_enrollment_status_event();
