--
-- Phase 3: Compliance Calendar Module
-- Creates the compliance_filings table for recurring ERS filing schedules.
--

create table public.compliance_filings (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    filing_type text not null,
    period_covered text not null,
    due_date date not null,
    submitted_date date,
    status text not null default 'UPCOMING',
    assigned_to bigint,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.compliance_filings
    add constraint compliance_filings_company_id_fkey
    foreign key (company_id) references public.companies(id) on delete cascade;

alter table public.compliance_filings
    add constraint compliance_filings_assigned_to_fkey
    foreign key (assigned_to) references public.sales(id) on delete set null;

create index compliance_filings_company_id_idx
    on public.compliance_filings using btree (company_id);

create index compliance_filings_due_date_idx
    on public.compliance_filings using btree (due_date);

create index compliance_filings_status_idx
    on public.compliance_filings using btree (status);
