-- Second Foundation Audit proof slice: the core Leif CRM business domain.
--
-- Adds four first-class tables (offers, offer_payment_options, cohorts,
-- applications, enrollments — five, counting payment options) and rewires
-- `deals` (the Opportunity) to reference a real Offer/Cohort instead of the
-- fixed 'the_living_example' text value the previous proof slice used.
--
-- Offers and their payment options are real business data (Leif has exactly
-- two offers today), so they are seeded here as production rows. Cohorts are
-- NOT seeded here — the demo September/November GYU cohorts are fake dates
-- for the FakeRest/demo layer only (see dataGenerator/leifProofSliceFixtures.ts)
-- and have no place in a real deploy's migration.

CREATE TABLE "public"."offers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "type" text NOT NULL,
    "duration" text NOT NULL,
    "current_price" numeric(10, 2) NOT NULL,
    "max_active_clients" smallint,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "offers_type_check" CHECK (type IN ('individual', 'group'))
);

CREATE TABLE "public"."offer_payment_options" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "offer_id" bigint NOT NULL,
    "name" text NOT NULL,
    "total" numeric(10, 2) NOT NULL,
    "installments" smallint NOT NULL,
    "installment_amount" numeric(10, 2) NOT NULL,
    "is_public" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "public"."cohorts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "offer_id" bigint NOT NULL,
    "name" text NOT NULL,
    "status" text NOT NULL DEFAULT 'draft',
    "applications_open_at" date,
    "applications_close_at" date,
    "program_start_at" date,
    "program_end_at" date,
    "minimum_capacity" smallint,
    "target_capacity" smallint,
    "maximum_capacity" smallint,
    "slack_channel_id" text,
    "calendar_id" text,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "cohorts_status_check" CHECK (status IN ('draft', 'applications_open', 'applications_closed', 'active', 'completed'))
);

CREATE TABLE "public"."applications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "opportunity_id" bigint NOT NULL,
    "status" text NOT NULL DEFAULT 'pending',
    "submitted_at" timestamp with time zone NOT NULL DEFAULT now(),
    "reviewed_at" timestamp with time zone,
    "raw_answers" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "summary" text,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "applications_status_check" CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE TABLE "public"."enrollments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "opportunity_id" bigint NOT NULL,
    "status" text NOT NULL DEFAULT 'onboarding',
    "start_date" date,
    "end_date" date,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "enrollments_status_check" CHECK (status IN ('onboarding', 'active', 'offboarding', 'completed'))
);

ALTER TABLE "public"."offer_payment_options"
    ADD CONSTRAINT "offer_payment_options_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES "public"."offers"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."cohorts"
    ADD CONSTRAINT "cohorts_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES "public"."offers"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."applications"
    ADD CONSTRAINT "applications_opportunity_id_fkey" FOREIGN KEY (opportunity_id) REFERENCES "public"."deals"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."enrollments"
    ADD CONSTRAINT "enrollments_opportunity_id_fkey" FOREIGN KEY (opportunity_id) REFERENCES "public"."deals"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    ADD CONSTRAINT "enrollments_opportunity_id_key" UNIQUE (opportunity_id);

CREATE INDEX "offer_payment_options_offer_id_idx" ON "public"."offer_payment_options" USING btree (offer_id);
CREATE INDEX "cohorts_offer_id_idx" ON "public"."cohorts" USING btree (offer_id);
CREATE INDEX "applications_opportunity_id_idx" ON "public"."applications" USING btree (opportunity_id);

-- Seed Leif's two real offers and their payment options.
INSERT INTO "public"."offers" ("name", "type", "duration", "current_price", "max_active_clients")
VALUES
    ('The Living Example', 'individual', '4 months', 4000.00, 12),
    ('Growing Yourself Up', 'group', '8 weeks', 1400.00, NULL);

INSERT INTO "public"."offer_payment_options" ("offer_id", "name", "total", "installments", "installment_amount", "is_public")
SELECT o.id, v.name, v.total, v.installments, v.installment_amount, v.is_public
FROM "public"."offers" o
JOIN (
    VALUES
        ('The Living Example', 'Pay in Full', 4000.00, 1, 4000.00, true),
        ('The Living Example', 'Monthly', 4000.00, 4, 1000.00, true),
        ('The Living Example', 'Financial Need', 3996.00, 6, 666.00, false),
        ('Growing Yourself Up', 'Pay in Full', 1400.00, 1, 1400.00, true),
        ('Growing Yourself Up', 'Monthly', 1400.00, 2, 700.00, true),
        ('Growing Yourself Up', 'Financial Need', 1400.00, 4, 350.00, false)
) AS v (offer_name, name, total, installments, installment_amount, is_public)
    ON v.offer_name = o.name;

-- Rewire deals (the Opportunity) onto the new Offer/Cohort model.
ALTER TABLE "public"."deals"
    ADD COLUMN "offer_id" bigint,
    ADD COLUMN "cohort_id" bigint,
    ADD COLUMN "sales_call_at" timestamp with time zone,
    ADD COLUMN "offer_name_snapshot" text,
    ADD COLUMN "offer_price_snapshot" numeric(10, 2),
    ADD COLUMN "selected_payment_option_id" bigint,
    ADD COLUMN "selected_payment_total" numeric(10, 2),
    ADD COLUMN "selected_installment_count" smallint,
    ADD COLUMN "selected_installment_amount" numeric(10, 2);

-- Backfill: every existing Opportunity (all created under the previous proof
-- slice's fixed-offer implementation) was implicitly The Living Example.
UPDATE "public"."deals"
SET
    "offer_id" = (SELECT id FROM "public"."offers" WHERE name = 'The Living Example'),
    "offer_name_snapshot" = 'The Living Example',
    "offer_price_snapshot" = 4000.00;

ALTER TABLE "public"."deals"
    ALTER COLUMN "offer_id" SET NOT NULL;

ALTER TABLE "public"."deals"
    DROP CONSTRAINT "deals_offer_check",
    DROP COLUMN "offer";

ALTER TABLE "public"."deals"
    ADD CONSTRAINT "deals_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES "public"."offers"(id),
    ADD CONSTRAINT "deals_cohort_id_fkey" FOREIGN KEY (cohort_id) REFERENCES "public"."cohorts"(id),
    ADD CONSTRAINT "deals_selected_payment_option_id_fkey" FOREIGN KEY (selected_payment_option_id) REFERENCES "public"."offer_payment_options"(id);

CREATE INDEX "deals_offer_id_idx" ON "public"."deals" USING btree (offer_id);
CREATE INDEX "deals_cohort_id_idx" ON "public"."deals" USING btree (cohort_id);

-- Validate Offer/Cohort consistency and snapshot commercial info at save time.
CREATE OR REPLACE FUNCTION "public"."handle_deal_saved"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_offer offers%ROWTYPE;
  v_cohort_offer_id bigint;
begin
  select * into v_offer from offers where id = new.offer_id;
  if v_offer.id is null then
    raise exception 'Invalid offer_id %', new.offer_id;
  end if;

  if new.cohort_id is not null then
    select offer_id into v_cohort_offer_id from cohorts where id = new.cohort_id;
    if v_cohort_offer_id is null then
      raise exception 'Invalid cohort_id %', new.cohort_id;
    end if;
    if v_offer.type <> 'group' then
      raise exception 'cohort_id can only be set on a group offer (offer_id %)', new.offer_id;
    end if;
    if v_cohort_offer_id <> new.offer_id then
      raise exception 'cohort_id % does not belong to offer_id %', new.cohort_id, new.offer_id;
    end if;
  end if;

  if tg_op = 'INSERT' or new.offer_id is distinct from old.offer_id then
    new.offer_name_snapshot := v_offer.name;
    new.offer_price_snapshot := v_offer.current_price;
  end if;

  if new.selected_payment_option_id is not null
     and (tg_op = 'INSERT' or new.selected_payment_option_id is distinct from old.selected_payment_option_id)
  then
    select total, installments, installment_amount
      into new.selected_payment_total, new.selected_installment_count, new.selected_installment_amount
      from offer_payment_options
      where id = new.selected_payment_option_id;
  end if;

  return new;
end;
$$;

-- Create the Opportunity's Enrollment the moment it genuinely transitions
-- into Won. Idempotent via enrollments_opportunity_id_key.
CREATE OR REPLACE FUNCTION "public"."handle_deal_won"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_cohort cohorts%ROWTYPE;
begin
  if new.stage = 'won' and (tg_op = 'INSERT' or old.stage is distinct from 'won') then
    if new.cohort_id is not null then
      select * into v_cohort from cohorts where id = new.cohort_id;
    end if;

    insert into enrollments (opportunity_id, status, start_date, end_date)
    values (
      new.id,
      'onboarding',
      v_cohort.program_start_at::date,
      v_cohort.program_end_at::date
    )
    on conflict (opportunity_id) do nothing;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE TRIGGER "05_handle_deal_saved"
    BEFORE INSERT OR UPDATE ON "public"."deals"
    FOR EACH ROW EXECUTE FUNCTION "public"."handle_deal_saved"();

CREATE OR REPLACE TRIGGER "on_deal_won"
    AFTER INSERT OR UPDATE ON "public"."deals"
    FOR EACH ROW EXECUTE FUNCTION "public"."handle_deal_won"();

-- Row level security: same permissive "any authenticated user" posture as
-- every other table in this app.
ALTER TABLE "public"."offers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."offer_payment_options" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."cohorts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."enrollments" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON "public"."offers" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON "public"."offers" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON "public"."offers" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Offers Delete Policy" ON "public"."offers" FOR DELETE TO authenticated USING (true);

CREATE POLICY "Enable read access for authenticated users" ON "public"."offer_payment_options" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON "public"."offer_payment_options" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON "public"."offer_payment_options" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Offer Payment Options Delete Policy" ON "public"."offer_payment_options" FOR DELETE TO authenticated USING (true);

CREATE POLICY "Enable read access for authenticated users" ON "public"."cohorts" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON "public"."cohorts" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON "public"."cohorts" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Cohorts Delete Policy" ON "public"."cohorts" FOR DELETE TO authenticated USING (true);

CREATE POLICY "Enable read access for authenticated users" ON "public"."applications" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON "public"."applications" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON "public"."applications" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Applications Delete Policy" ON "public"."applications" FOR DELETE TO authenticated USING (true);

CREATE POLICY "Enable read access for authenticated users" ON "public"."enrollments" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON "public"."enrollments" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON "public"."enrollments" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enrollments Delete Policy" ON "public"."enrollments" FOR DELETE TO authenticated USING (true);

GRANT ALL ON FUNCTION "public"."handle_deal_saved"() TO anon;
GRANT ALL ON FUNCTION "public"."handle_deal_saved"() TO authenticated;
GRANT ALL ON FUNCTION "public"."handle_deal_saved"() TO service_role;

GRANT ALL ON FUNCTION "public"."handle_deal_won"() TO anon;
GRANT ALL ON FUNCTION "public"."handle_deal_won"() TO authenticated;
GRANT ALL ON FUNCTION "public"."handle_deal_won"() TO service_role;

GRANT ALL ON TABLE "public"."offers" TO anon;
GRANT ALL ON TABLE "public"."offers" TO authenticated;
GRANT ALL ON TABLE "public"."offers" TO service_role;

GRANT ALL ON TABLE "public"."offer_payment_options" TO anon;
GRANT ALL ON TABLE "public"."offer_payment_options" TO authenticated;
GRANT ALL ON TABLE "public"."offer_payment_options" TO service_role;

GRANT ALL ON TABLE "public"."cohorts" TO anon;
GRANT ALL ON TABLE "public"."cohorts" TO authenticated;
GRANT ALL ON TABLE "public"."cohorts" TO service_role;

GRANT ALL ON TABLE "public"."applications" TO anon;
GRANT ALL ON TABLE "public"."applications" TO authenticated;
GRANT ALL ON TABLE "public"."applications" TO service_role;

GRANT ALL ON TABLE "public"."enrollments" TO anon;
GRANT ALL ON TABLE "public"."enrollments" TO authenticated;
GRANT ALL ON TABLE "public"."enrollments" TO service_role;

GRANT ALL ON SEQUENCE "public"."offers_id_seq" TO anon;
GRANT ALL ON SEQUENCE "public"."offers_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE "public"."offers_id_seq" TO service_role;

GRANT ALL ON SEQUENCE "public"."offer_payment_options_id_seq" TO anon;
GRANT ALL ON SEQUENCE "public"."offer_payment_options_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE "public"."offer_payment_options_id_seq" TO service_role;

GRANT ALL ON SEQUENCE "public"."cohorts_id_seq" TO anon;
GRANT ALL ON SEQUENCE "public"."cohorts_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE "public"."cohorts_id_seq" TO service_role;

GRANT ALL ON SEQUENCE "public"."applications_id_seq" TO anon;
GRANT ALL ON SEQUENCE "public"."applications_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE "public"."applications_id_seq" TO service_role;

GRANT ALL ON SEQUENCE "public"."enrollments_id_seq" TO anon;
GRANT ALL ON SEQUENCE "public"."enrollments_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE "public"."enrollments_id_seq" TO service_role;
