create table if not exists public.ai_commands (
    id bigint generated by default as identity primary key,
    idempotency_key text unique,
    command_hash text,
    source_ai text not null,
    command_type text not null,
    target_entity_type text,
    target_entity_id bigint,
    payload jsonb not null default '{}',
    status text not null default 'pending',
    requires_approval boolean not null default true,
    approved_by_user_id bigint references public.sales(id),
    approved_at timestamptz,
    executed_at timestamptz,
    execution_result jsonb,
    error_message text,
    expires_at timestamptz not null default (now() + interval '24 hours'),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ai_commands_source_ai_check check (
        source_ai in ('chatgpt', 'claude', 'gemini', 'manual', 'system')
    ),
    constraint ai_commands_status_check check (
        status in ('pending', 'approved', 'executing', 'completed', 'failed', 'rejected', 'expired')
    )
);

create index if not exists idx_ai_commands_status_created_at
on public.ai_commands (status, created_at desc);

create index if not exists idx_ai_commands_source_created_at
on public.ai_commands (source_ai, created_at desc);

create table if not exists public.ai_audit_events (
    id bigint generated by default as identity primary key,
    command_id bigint references public.ai_commands(id),
    source_ai text,
    action text not null,
    entity_type text,
    entity_id bigint,
    before_data jsonb,
    after_data jsonb,
    metadata jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_ai_audit_events_command_id
on public.ai_audit_events (command_id);

create index if not exists idx_ai_audit_events_created_at
on public.ai_audit_events (created_at desc);

alter table public.tasks
    add column if not exists title text,
    add column if not exists priority text default 'medium',
    add column if not exists source text default 'manual',
    add column if not exists source_command_id bigint references public.ai_commands(id),
    add column if not exists linked_entity_type text,
    add column if not exists linked_entity_id bigint,
    add column if not exists success_definition text;

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'tasks_priority_check'
    ) then
        alter table public.tasks
        add constraint tasks_priority_check
        check (priority in ('low', 'medium', 'high', 'urgent'));
    end if;
    if not exists (
        select 1 from pg_constraint where conname = 'tasks_source_check'
    ) then
        alter table public.tasks
        add constraint tasks_source_check
        check (source in ('manual', 'ai_command', 'instantly_webhook', 'system'));
    end if;
end $$;

alter table public.ai_commands enable row level security;
alter table public.ai_audit_events enable row level security;

create or replace function public.set_ai_commands_updated_at() returns trigger
    language plpgsql
    set search_path to 'public'
    as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_ai_commands_updated_at on public.ai_commands;
create trigger set_ai_commands_updated_at
    before update on public.ai_commands
    for each row execute function public.set_ai_commands_updated_at();

create policy "Enable ai command read for managers" on public.ai_commands
    for select to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Enable ai command creation for authenticated" on public.ai_commands
    for insert to authenticated
    with check (true);

create policy "Enable ai command update for admins" on public.ai_commands
    for update to authenticated
    using (public.current_user_role() = 'admin')
    with check (public.current_user_role() = 'admin');

create policy "Enable ai audit read for managers" on public.ai_audit_events
    for select to authenticated
    using (public.current_user_role() in ('admin', 'sales_manager'));

create policy "Enable ai audit creation for authenticated" on public.ai_audit_events
    for insert to authenticated
    with check (true);

grant select, insert, update on table public.ai_commands to authenticated;
grant select, insert on table public.ai_audit_events to authenticated;
grant all on table public.ai_commands to service_role;
grant all on table public.ai_audit_events to service_role;
grant usage, select on sequence public.ai_commands_id_seq to authenticated;
grant usage, select on sequence public.ai_audit_events_id_seq to authenticated;
grant all on sequence public.ai_commands_id_seq to service_role;
grant all on sequence public.ai_audit_events_id_seq to service_role;
grant all on function public.set_ai_commands_updated_at() to anon;
grant all on function public.set_ai_commands_updated_at() to authenticated;
grant all on function public.set_ai_commands_updated_at() to service_role;
