-- Migration: Create monthly_reports table + monthly pg_cron job
-- Created: 2026-06-24
-- Description: Fas 1 av kundrapporten — paketerar website_snapshots-tidsserien till
--              ett kundvänligt månadsmail (trend + en skräddarsydd upsell) bakom en
--              godkännande-grind: cronen skapar en DRAFT per kund och pingar Discord;
--              mailet skickas först efter godkännande (Discord-länk eller CRM-knapp).
--              Fylls av edge-funktionen generate_monthly_reports (manuellt via Kund-
--              fliken eller månadsvis via pg_cron) och skickas av send_monthly_report.
--              Helt additiv migration — inga DROP/ALTER på befintliga objekt.

CREATE TABLE IF NOT EXISTS "public"."monthly_reports" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  -- Rapportperioden som första dagen i månaden (2026-06-01) → (company_id, period) unikt
  "period" date NOT NULL,
  -- Snapshot som rapporten bygger på + den föregående (för trend). SET NULL så att
  -- en raderad snapshot inte tar rapporten med sig (historiken bevaras).
  "snapshot_id" bigint REFERENCES website_snapshots(id) ON DELETE SET NULL,
  "previous_snapshot_id" bigint REFERENCES website_snapshots(id) ON DELETE SET NULL,
  -- draft: skapad av cron/manuellt, väntar på godkännande
  -- approved: godkänd i CRM, på väg att skickas
  -- sent: mailet skickat till kund
  -- failed: AI-validering eller utskick misslyckades (se error)
  -- skipped: ingen snapshot/mottagare → inget att rapportera
  "status" text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'approved', 'sent', 'failed', 'skipped')),
  "recipient_email" text,
  "recipient_name" text,
  -- AI-genererad, kundvänd text (validerad mot monthlyReportContentSchema innan spar)
  "ai_content" jsonb,        -- { greeting, summary, recommended_action, upsell_pitch }
  -- Valda upsells (alla matchande sparas; mailet visar den högst prioriterade)
  "selected_upsells" jsonb NOT NULL DEFAULT '[]',
  -- Fryst trend-data så rapporten är reproducerbar även om snapshots ändras
  "metrics" jsonb,           -- { clicks: {current, previous, deltaPct}, ... }
  "generated_html" text,     -- färdig mail-HTML (källa vid utskick + förhandsgranskning)
  "public_url" text,         -- Fas 2: länk till full HTML-rapportsida i Storage
  "approval_token" uuid NOT NULL DEFAULT gen_random_uuid(),
  "email_send_id" bigint REFERENCES email_sends(id) ON DELETE SET NULL,
  "error" text,
  "approved_by" bigint REFERENCES sales(id) ON DELETE SET NULL,
  "approved_at" timestamp with time zone,
  "sent_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE "public"."monthly_reports" ENABLE ROW LEVEL SECURITY;

-- Hela teamet läser, skapar och uppdaterar (godkänner/redigerar draft i CRM).
-- Edge-funktionerna skriver via service role och påverkas inte av RLS.
CREATE POLICY "Authenticated can view monthly reports" ON "public"."monthly_reports"
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can insert monthly reports" ON "public"."monthly_reports"
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update monthly reports" ON "public"."monthly_reports"
  FOR UPDATE
  USING (auth.role() = 'authenticated');

-- En rapport per kund och månad (idempotens vid cron-omkörning).
CREATE UNIQUE INDEX idx_monthly_reports_company_period
  ON monthly_reports(company_id, period);
CREATE INDEX idx_monthly_reports_status ON monthly_reports(status);
CREATE INDEX idx_monthly_reports_approval_token ON monthly_reports(approval_token);

-- ============================================================================
-- Månadsvis automatisk draft-generering via pg_cron + pg_net
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- SECURITY DEFINER-funktion som anropar generate_monthly_reports i cron-läge.
-- Läser supabase_url + cron_secret från vault (samma mönster som
-- run_monthly_website_snapshots). Saknas något → varna och hoppa över.
CREATE OR REPLACE FUNCTION public.run_monthly_reports()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  edge_function_url text;
  cron_secret text;
BEGIN
  SELECT decrypted_secret INTO edge_function_url
  FROM vault.decrypted_secrets
  WHERE name = 'supabase_url'
  LIMIT 1;

  SELECT decrypted_secret INTO cron_secret
  FROM vault.decrypted_secrets
  WHERE name = 'cron_secret'
  LIMIT 1;

  IF edge_function_url IS NULL OR cron_secret IS NULL THEN
    RAISE WARNING 'run_monthly_reports: missing supabase_url or cron_secret in vault — skipping run';
    RETURN;
  END IF;

  PERFORM net.http_post(
    url     := edge_function_url || '/functions/v1/generate_monthly_reports',
    body    := jsonb_build_object('cron', true),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', cron_secret
    ),
    timeout_milliseconds := 10000
  );
END;
$$;

-- Kör 07:00 den 1:a varje månad — en timme efter monthly-website-snapshots (06:00)
-- så att den färska snapshoten finns när rapporten genereras. cron.schedule är
-- idempotent på jobbnamn.
SELECT cron.schedule(
  'monthly-reports',
  '0 7 1 * *',
  $$SELECT public.run_monthly_reports();$$
);
