-- Contracts + Onboarding slice: durable, offer-scoped onboarding
-- checklist infrastructure. See supabase/schemas/01_tables.sql /
-- 02_functions.sql / 04_triggers.sql for the full rationale comments this
-- migration mirrors exactly.

--
-- Tables
--

create table public.onboarding_requirement_templates (
    id bigint generated by default as identity primary key,
    offer_id bigint not null,
    key text not null,
    label text not null,
    task_text_template text not null,
    is_required boolean not null default true,
    sort_order smallint not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (offer_id, key)
);

create table public.enrollment_onboarding_items (
    id bigint generated by default as identity primary key,
    enrollment_id bigint not null,
    requirement_key text not null,
    label text not null,
    is_required boolean not null,
    sort_order smallint not null default 0,
    status text not null default 'pending',
    completed_at timestamp with time zone,
    external_ref text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint enrollment_onboarding_items_status_check check (status in ('pending', 'sent', 'done')),
    unique (enrollment_id, requirement_key)
);

alter table public.tasks
    add column enrollment_id bigint,
    add column onboarding_item_id bigint;

--
-- Foreign keys
--

alter table public.onboarding_requirement_templates
    add constraint onboarding_requirement_templates_offer_id_fkey foreign key (offer_id) references public.offers(id) on update cascade on delete cascade;

alter table public.enrollment_onboarding_items
    add constraint enrollment_onboarding_items_enrollment_id_fkey foreign key (enrollment_id) references public.enrollments(id) on update cascade on delete cascade;

alter table public.tasks
    add constraint tasks_enrollment_id_fkey foreign key (enrollment_id) references public.enrollments(id) on update cascade on delete set null;

alter table public.tasks
    add constraint tasks_onboarding_item_id_fkey foreign key (onboarding_item_id) references public.enrollment_onboarding_items(id) on update cascade on delete set null;

--
-- Indexes
--

create index onboarding_requirement_templates_offer_id_idx on public.onboarding_requirement_templates using btree (offer_id);
create index enrollment_onboarding_items_enrollment_id_idx on public.enrollment_onboarding_items using btree (enrollment_id);
create index tasks_enrollment_id_idx on public.tasks using btree (enrollment_id);
create index tasks_onboarding_item_id_idx on public.tasks using btree (onboarding_item_id);

--
-- Row Level Security
--

alter table public.onboarding_requirement_templates enable row level security;
alter table public.enrollment_onboarding_items enable row level security;

create policy "Enable read access for authenticated users" on public.onboarding_requirement_templates for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.onboarding_requirement_templates for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.onboarding_requirement_templates for update to authenticated using (true) with check (true);
create policy "Onboarding Requirement Templates Delete Policy" on public.onboarding_requirement_templates for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.enrollment_onboarding_items for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.enrollment_onboarding_items for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.enrollment_onboarding_items for update to authenticated using (true) with check (true);
create policy "Enrollment Onboarding Items Delete Policy" on public.enrollment_onboarding_items for delete to authenticated using (true);

--
-- Grants
--

grant all on table public.onboarding_requirement_templates to anon;
grant all on table public.onboarding_requirement_templates to authenticated;
grant all on table public.onboarding_requirement_templates to service_role;

grant all on table public.enrollment_onboarding_items to anon;
grant all on table public.enrollment_onboarding_items to authenticated;
grant all on table public.enrollment_onboarding_items to service_role;

grant all on sequence public.onboarding_requirement_templates_id_seq to anon;
grant all on sequence public.onboarding_requirement_templates_id_seq to authenticated;
grant all on sequence public.onboarding_requirement_templates_id_seq to service_role;

grant all on sequence public.enrollment_onboarding_items_id_seq to anon;
grant all on sequence public.enrollment_onboarding_items_id_seq to authenticated;
grant all on sequence public.enrollment_onboarding_items_id_seq to service_role;

--
-- Functions
--

CREATE OR REPLACE FUNCTION "public"."handle_deal_won"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_cohort cohorts%ROWTYPE;
  v_enrollment_id bigint;
  v_contact_name text;
  v_item record;
begin
  if new.stage = 'won' and (tg_op = 'INSERT' or old.stage is distinct from 'won') then
    if new.cohort_id is not null then
      select * into v_cohort from cohorts where id = new.cohort_id;
    end if;

    insert into enrollments (opportunity_id, status, start_date, end_date)
    values (
      new.id,
      'onboarding',
      v_cohort.program_start_at::date,
      v_cohort.program_end_at::date
    )
    on conflict (opportunity_id) do nothing
    returning id into v_enrollment_id;

    if v_enrollment_id is not null then
      select trim(both ' ' from coalesce(first_name, '') || ' ' || coalesce(last_name, ''))
        into v_contact_name
        from contacts where id = new.contact_id;
      if v_contact_name is null or v_contact_name = '' then
        v_contact_name := new.name;
      end if;

      for v_item in
        with inserted_items as (
          insert into enrollment_onboarding_items (enrollment_id, requirement_key, label, is_required, sort_order)
          select v_enrollment_id, t.key, t.label, t.is_required, t.sort_order
          from onboarding_requirement_templates t
          where t.offer_id = new.offer_id and t.is_active
          returning id, requirement_key, is_required
        )
        select i.id, i.is_required, t.task_text_template
        from inserted_items i
        join onboarding_requirement_templates t
          on t.offer_id = new.offer_id and t.key = i.requirement_key
      loop
        if v_item.is_required then
          insert into tasks (contact_id, type, text, due_date, status, enrollment_id, onboarding_item_id)
          values (
            new.contact_id,
            'onboarding_item',
            replace(v_item.task_text_template, '{name}', v_contact_name),
            now() + interval '3 days',
            'pending',
            v_enrollment_id,
            v_item.id
          );
        end if;
      end loop;
    end if;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."set_task_enrollment_id_consistency"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_item_enrollment_id bigint;
begin
  if new.onboarding_item_id is not null then
    select enrollment_id into v_item_enrollment_id
      from enrollment_onboarding_items where id = new.onboarding_item_id;
    if v_item_enrollment_id is null then
      raise exception 'Invalid onboarding_item_id %', new.onboarding_item_id;
    end if;
    if new.enrollment_id is null then
      new.enrollment_id := v_item_enrollment_id;
    elsif new.enrollment_id <> v_item_enrollment_id then
      raise exception 'enrollment_id % does not match onboarding_item_id %''s own enrollment_id %',
        new.enrollment_id, new.onboarding_item_id, v_item_enrollment_id;
    end if;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."sync_onboarding_item_from_task"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  if new.onboarding_item_id is null then
    return new;
  end if;

  if new.done_date is not null and old.done_date is null then
    update enrollment_onboarding_items
      set status = 'done', completed_at = coalesce(completed_at, new.done_date), updated_at = now()
      where id = new.onboarding_item_id and status <> 'done';
  elsif new.done_date is null and old.done_date is not null then
    update enrollment_onboarding_items
      set status = 'pending', completed_at = null, updated_at = now()
      where id = new.onboarding_item_id and status = 'done';
  end if;

  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."enforce_enrollment_activation_requirements"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  if new.status = 'active' and old.status = 'onboarding' then
    if exists (
      select 1 from enrollment_onboarding_items
      where enrollment_id = new.id and is_required and status <> 'done'
    ) then
      raise exception 'Cannot activate enrollment %: required onboarding items incomplete', new.id;
    end if;
  end if;
  return new;
end;
$$;

--
-- Triggers
--

create or replace trigger set_task_enrollment_id_consistency_trigger
    before insert or update on public.tasks
    for each row execute function public.set_task_enrollment_id_consistency();

create or replace trigger on_task_onboarding_sync
    after update on public.tasks
    for each row
    when (old.done_date is distinct from new.done_date)
    execute function public.sync_onboarding_item_from_task();

create or replace trigger enforce_enrollment_activation_requirements_trigger
    before update on public.enrollments
    for each row execute function public.enforce_enrollment_activation_requirements();
