-- Google OAuth tokens storage (per user)
CREATE TABLE public.google_oauth_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  sales_id bigint NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamptz NOT NULL,
  scopes text[] NOT NULL DEFAULT '{}',
  google_email text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.google_oauth_tokens ENABLE ROW LEVEL SECURITY;

-- Only Edge Functions (service_role) can access tokens directly
CREATE POLICY "service_role_full_access" ON public.google_oauth_tokens
  FOR ALL USING (auth.role() = 'service_role');

-- Connector preferences (per user, per connector type)
CREATE TABLE public.connector_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  connector_type text NOT NULL,
  preferences jsonb DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, connector_type)
);

ALTER TABLE public.connector_preferences ENABLE ROW LEVEL SECURITY;

-- Users can manage their own preferences
CREATE POLICY "users_own_preferences" ON public.connector_preferences
  FOR ALL USING (user_id = auth.uid());
