-- Acuity/Sales Call Lifecycle slice.
-- Hand-authored (no local Docker/Supabase available this session — see
-- this slice's report for the production-verification item this leaves
-- open). Mirrors supabase/schemas/{01_tables,02_functions,04_triggers,
-- 05_policies,06_grants}.sql exactly.
--
-- Adds:
--  - offers.acuity_appointment_type_id, cohorts.acuity_appointment_type_id
--    (durable Offer/Cohort <-> Acuity appointment-type mapping)
--  - deals_outcome_check gains 'workshops_only' (a genuine pipeline exit,
--    explicitly not a lost sale)
--  - sales_calls: the durable current-state sales-call/appointment record
--  - sales_call_events: append-only lifecycle history for a sales_calls row
--  - sync_deal_sales_call_at(): keeps deals.sales_call_at (existing field)
--    in sync with sales_calls, the new source of truth

alter table "public"."offers"
    add column "acuity_appointment_type_id" text;

alter table "public"."cohorts"
    add column "acuity_appointment_type_id" text;

create unique index "offers_acuity_appointment_type_id_idx" on "public"."offers" ("acuity_appointment_type_id") where ("acuity_appointment_type_id" is not null);
create unique index "cohorts_acuity_appointment_type_id_idx" on "public"."cohorts" ("acuity_appointment_type_id") where ("acuity_appointment_type_id" is not null);

alter table "public"."deals" drop constraint "deals_outcome_check";
alter table "public"."deals"
    add constraint "deals_outcome_check" check (outcome in ('nurture', 'needs_higher_care', 'not_fit', 'lost', 'workshops_only'));

create table "public"."sales_calls" (
    "id" bigint generated by default as identity primary key,
    "opportunity_id" bigint,
    "contact_id" bigint not null,
    "status" text not null default 'booked',
    "original_scheduled_at" timestamp with time zone not null,
    "scheduled_at" timestamp with time zone not null,
    "reschedule_count" smallint not null default 0,
    "last_rescheduled_at" timestamp with time zone,
    "cancelled_at" timestamp with time zone,
    "attendance" text,
    "attendance_recorded_at" timestamp with time zone,
    "source" text not null default 'manual',
    "acuity_appointment_id" text,
    "acuity_appointment_type_id" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    constraint "sales_calls_status_check" check (status in ('booked', 'cancelled')),
    constraint "sales_calls_attendance_check" check (attendance in ('attended', 'no_show')),
    constraint "sales_calls_source_check" check (source in ('acuity', 'manual'))
);

create unique index "sales_calls_one_booked_per_opportunity_idx" on "public"."sales_calls" ("opportunity_id") where (status = 'booked' and opportunity_id is not null);
create unique index "sales_calls_acuity_appointment_id_idx" on "public"."sales_calls" ("acuity_appointment_id") where (acuity_appointment_id is not null);
create index "sales_calls_opportunity_id_idx" on "public"."sales_calls" using btree ("opportunity_id");
create index "sales_calls_contact_id_idx" on "public"."sales_calls" using btree ("contact_id");

alter table "public"."sales_calls"
    add constraint "sales_calls_opportunity_id_fkey" foreign key ("opportunity_id") references "public"."deals"("id") on update cascade on delete cascade;
alter table "public"."sales_calls"
    add constraint "sales_calls_contact_id_fkey" foreign key ("contact_id") references "public"."contacts"("id") on update cascade on delete cascade;

create table "public"."sales_call_events" (
    "id" bigint generated by default as identity primary key,
    "sales_call_id" bigint not null,
    "kind" text not null,
    "occurred_at" timestamp with time zone not null default now(),
    "previous_scheduled_at" timestamp with time zone,
    "new_scheduled_at" timestamp with time zone,
    "attendance" text,
    "created_at" timestamp with time zone not null default now(),
    constraint "sales_call_events_kind_check" check (kind in ('booked', 'rescheduled', 'cancelled', 'attendance_recorded')),
    constraint "sales_call_events_attendance_check" check (attendance in ('attended', 'no_show'))
);

create index "sales_call_events_sales_call_id_idx" on "public"."sales_call_events" using btree ("sales_call_id");

alter table "public"."sales_call_events"
    add constraint "sales_call_events_sales_call_id_fkey" foreign key ("sales_call_id") references "public"."sales_calls"("id") on update cascade on delete cascade;

CREATE OR REPLACE FUNCTION "public"."sync_deal_sales_call_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_opportunity_id bigint;
  v_latest timestamp with time zone;
begin
  v_opportunity_id := coalesce(new.opportunity_id, old.opportunity_id);
  if v_opportunity_id is null then
    return coalesce(new, old);
  end if;

  select scheduled_at into v_latest
    from sales_calls
    where opportunity_id = v_opportunity_id and status = 'booked'
    order by scheduled_at desc
    limit 1;

  update deals set sales_call_at = v_latest where id = v_opportunity_id;

  return coalesce(new, old);
end;
$$;

create or replace trigger "on_sales_call_saved"
    after insert or update or delete on "public"."sales_calls"
    for each row execute function "public"."sync_deal_sales_call_at"();

alter table "public"."sales_calls" enable row level security;
alter table "public"."sales_call_events" enable row level security;

create policy "Enable read access for authenticated users" on "public"."sales_calls" for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."sales_calls" for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."sales_calls" for update to authenticated using (true) with check (true);
create policy "Sales Calls Delete Policy" on "public"."sales_calls" for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on "public"."sales_call_events" for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."sales_call_events" for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."sales_call_events" for update to authenticated using (true) with check (true);
create policy "Sales Call Events Delete Policy" on "public"."sales_call_events" for delete to authenticated using (true);

grant all on table "public"."sales_calls" to anon;
grant all on table "public"."sales_calls" to authenticated;
grant all on table "public"."sales_calls" to service_role;

grant all on table "public"."sales_call_events" to anon;
grant all on table "public"."sales_call_events" to authenticated;
grant all on table "public"."sales_call_events" to service_role;

grant all on sequence "public"."sales_calls_id_seq" to anon;
grant all on sequence "public"."sales_calls_id_seq" to authenticated;
grant all on sequence "public"."sales_calls_id_seq" to service_role;

grant all on sequence "public"."sales_call_events_id_seq" to anon;
grant all on sequence "public"."sales_call_events_id_seq" to authenticated;
grant all on sequence "public"."sales_call_events_id_seq" to service_role;
