-- Client + Session Operations: cadence correction.
--
-- Human acceptance on the original Slice A ("Mark Completed" per session,
-- hardcoded 3-sessions-per-month) surfaced that this isn't how Leif
-- actually runs The Living Example: he doesn't manually open every client
-- every week, and the real cadence expectation is driven by which weeks
-- he is actually open for 1:1s (Google Calendar's "Year Planning"
-- calendar), not by an assumed 3-per-calendar-month. This migration
-- corrects the schema for that: booked sessions are now assumed attended
-- by default (no_show_at replaces the old completed_at/"Mark Completed"
-- model), and two new tables hold the read-only ingested calendar
-- expectation (expected_session_windows) and the resolvable cadence
-- exception this creates when an active Enrollment has no fulfilling
-- session in a window that already closed (client_session_cadence_issues,
-- surfaced via the existing Dashboard Needs Attention Task mechanism).
--
-- The prior client_sessions/client_session_events tables (migration
-- 20260906050000) are corrected in place rather than replaced — the
-- durable booking/reschedule/cancel history and the Acuity 90522599
-- routing they hold are unaffected by this product correction and are
-- explicitly preserved.

-- No real data depends on the values being removed below — the only
-- rows in client_sessions at this point are the prior slice's own
-- disposable human-acceptance fixture, already deleted before this
-- migration runs (see this slice's own cleanup notes).

alter table "public"."client_sessions" drop column "completed_at";
alter table "public"."client_sessions" add column "no_show_at" timestamp with time zone;

alter table "public"."client_sessions" drop constraint "client_sessions_status_check";
alter table "public"."client_sessions" add constraint "client_sessions_status_check" check ((status = any (array['booked'::text, 'cancelled'::text]))) not valid;
alter table "public"."client_sessions" validate constraint "client_sessions_status_check";

alter table "public"."client_session_events" drop constraint "client_session_events_kind_check";
alter table "public"."client_session_events" add constraint "client_session_events_kind_check" check ((kind = any (array['booked'::text, 'rescheduled'::text, 'cancelled'::text, 'no_show'::text, 'no_show_reversed'::text]))) not valid;
alter table "public"."client_session_events" validate constraint "client_session_events_kind_check";

create table "public"."expected_session_windows" (
    "id" bigint generated by default as identity primary key,
    "offer_id" bigint not null,
    "external_calendar_id" text not null,
    "external_event_id" text not null,
    "raw_title" text not null,
    "window_start" date not null,
    "window_end" date not null,
    "deleted_at" timestamp with time zone,
    "synced_at" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    constraint "expected_session_windows_window_check" check ((window_end > window_start))
);

create unique index "expected_session_windows_external_event_idx" on "public"."expected_session_windows" ("external_calendar_id", "external_event_id");
create index "expected_session_windows_offer_id_idx" on "public"."expected_session_windows" using btree ("offer_id");
create index "expected_session_windows_active_idx" on "public"."expected_session_windows" using btree ("offer_id", "window_start") where ("deleted_at" is null);

alter table "public"."expected_session_windows" add constraint "expected_session_windows_offer_id_fkey" foreign key ("offer_id") references "public"."offers"("id") on update cascade on delete cascade;

create table "public"."client_session_cadence_issues" (
    "id" bigint generated by default as identity primary key,
    "enrollment_id" bigint not null,
    "expected_session_window_id" bigint not null,
    "classification" text,
    "note" text,
    "resolved_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    constraint "client_session_cadence_issues_classification_check" check ((classification is null or classification = any (array['known_skip'::text, 'rescheduled'::text, 'missed_ghosted'::text])))
);

create unique index "client_session_cadence_issues_enrollment_window_idx" on "public"."client_session_cadence_issues" ("enrollment_id", "expected_session_window_id");
create index "client_session_cadence_issues_enrollment_id_idx" on "public"."client_session_cadence_issues" using btree ("enrollment_id");
create index "client_session_cadence_issues_unresolved_idx" on "public"."client_session_cadence_issues" using btree ("enrollment_id") where ("resolved_at" is null);

alter table "public"."client_session_cadence_issues" add constraint "client_session_cadence_issues_enrollment_id_fkey" foreign key ("enrollment_id") references "public"."enrollments"("id") on update cascade on delete cascade;
alter table "public"."client_session_cadence_issues" add constraint "client_session_cadence_issues_window_id_fkey" foreign key ("expected_session_window_id") references "public"."expected_session_windows"("id") on update cascade on delete cascade;

alter table "public"."tasks" add column "cadence_issue_id" bigint;
create index "tasks_cadence_issue_id_idx" on "public"."tasks" using btree ("cadence_issue_id");
alter table "public"."tasks" add constraint "tasks_cadence_issue_id_fkey" foreign key ("cadence_issue_id") references "public"."client_session_cadence_issues"("id") on update cascade on delete set null;

alter table "public"."expected_session_windows" enable row level security;
alter table "public"."client_session_cadence_issues" enable row level security;

create policy "Enable read access for authenticated users" on "public"."expected_session_windows" for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."expected_session_windows" for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."expected_session_windows" for update to authenticated using (true) with check (true);
create policy "Expected Session Windows Delete Policy" on "public"."expected_session_windows" for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on "public"."client_session_cadence_issues" for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."client_session_cadence_issues" for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."client_session_cadence_issues" for update to authenticated using (true) with check (true);
create policy "Client Session Cadence Issues Delete Policy" on "public"."client_session_cadence_issues" for delete to authenticated using (true);

grant all on table "public"."expected_session_windows" to "anon";
grant all on table "public"."expected_session_windows" to "authenticated";
grant all on table "public"."expected_session_windows" to "service_role";

grant all on table "public"."client_session_cadence_issues" to "anon";
grant all on table "public"."client_session_cadence_issues" to "authenticated";
grant all on table "public"."client_session_cadence_issues" to "service_role";

grant all on sequence "public"."expected_session_windows_id_seq" to "anon";
grant all on sequence "public"."expected_session_windows_id_seq" to "authenticated";
grant all on sequence "public"."expected_session_windows_id_seq" to "service_role";

grant all on sequence "public"."client_session_cadence_issues_id_seq" to "anon";
grant all on sequence "public"."client_session_cadence_issues_id_seq" to "authenticated";
grant all on sequence "public"."client_session_cadence_issues_id_seq" to "service_role";
