-- Scholarship Pricing + Capacity slice.
--
-- Hand-written (not CLI-generated): the sandbox this migration was authored
-- in has no Docker/Podman available, so `supabase db diff` cannot spin up
-- its shadow database. Every statement below matches
-- supabase/schemas/{01_tables,02_functions,04_triggers,05_policies,06_grants}.sql
-- exactly — see those files for the full design rationale in comments.
--
-- Scholarship is a PRICING MODE of an existing Offer, never a second Offer,
-- pipeline, or coupon. Locked business rules (Leif, 2026-09-09):
--   - The Living Example scholarship total: $3,000 (PIF, or 3 x $1,000)
--   - Growing Yourself Up scholarship total: $700 (PIF, or 2 x $350)
--   - At most ONE scholarship slot holder per Offer at a time — a slot is
--     held by either an outstanding (granted, unpaid) Deal, or a current
--     (onboarding/active/offboarding) Enrollment, never both.

-- ---------------------------------------------------------------------
-- 1. Columns
-- ---------------------------------------------------------------------

alter table "public"."offers"
  add column "scholarship_price" numeric(10,2);

alter table "public"."offer_payment_options"
  add column "pricing_mode" text not null default 'standard';

alter table "public"."offer_payment_options"
  add constraint "offer_payment_options_pricing_mode_check" check (pricing_mode in ('standard', 'scholarship'));

alter table "public"."deals"
  add column "pricing_mode" text not null default 'standard';

alter table "public"."deals"
  add constraint "deals_pricing_mode_check" check (pricing_mode in ('standard', 'scholarship'));

-- ---------------------------------------------------------------------
-- 2. New tables
-- ---------------------------------------------------------------------

create table "public"."scholarship_slots" (
    "offer_id" bigint primary key,
    "holder_deal_id" bigint,
    "holder_enrollment_id" bigint,
    "reserved_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    constraint "scholarship_slots_single_holder_check" check (not (holder_deal_id is not null and holder_enrollment_id is not null)),
    constraint "scholarship_slots_holder_deal_unique" unique (holder_deal_id),
    constraint "scholarship_slots_holder_enrollment_unique" unique (holder_enrollment_id)
);

create table "public"."scholarship_slot_events" (
    "id" bigint generated by default as identity primary key,
    "offer_id" bigint not null,
    "deal_id" bigint,
    "enrollment_id" bigint,
    "event_type" text not null,
    "occurred_at" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now(),
    constraint "scholarship_slot_events_event_type_check" check (event_type in (
        'scholarship_granted',
        'scholarship_released',
        'deal_converted_to_enrollment',
        'enrollment_completed_slot_released',
        'slot_reclaimed_after_backward_lifecycle_correction'
    ))
);

alter table "public"."scholarship_slots"
  add constraint "scholarship_slots_offer_id_fkey" foreign key (offer_id) references public.offers(id) on update cascade on delete cascade;

alter table "public"."scholarship_slots"
  add constraint "scholarship_slots_holder_deal_id_fkey" foreign key (holder_deal_id) references public.deals(id) on update cascade on delete set null;

alter table "public"."scholarship_slots"
  add constraint "scholarship_slots_holder_enrollment_id_fkey" foreign key (holder_enrollment_id) references public.enrollments(id) on update cascade on delete set null;

alter table "public"."scholarship_slot_events"
  add constraint "scholarship_slot_events_offer_id_fkey" foreign key (offer_id) references public.offers(id) on update cascade on delete cascade;

alter table "public"."scholarship_slot_events"
  add constraint "scholarship_slot_events_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete set null;

alter table "public"."scholarship_slot_events"
  add constraint "scholarship_slot_events_enrollment_id_fkey" foreign key (enrollment_id) references public.enrollments(id) on update cascade on delete set null;

create index "scholarship_slot_events_offer_id_idx" on public.scholarship_slot_events using btree (offer_id);
create index "scholarship_slot_events_deal_id_idx" on public.scholarship_slot_events using btree (deal_id);
create index "scholarship_slot_events_enrollment_id_idx" on public.scholarship_slot_events using btree (enrollment_id);

-- ---------------------------------------------------------------------
-- 3. RLS + grants (same shape as every other trigger-managed table in
--    this schema — see 05_policies.sql/06_grants.sql for the rationale)
-- ---------------------------------------------------------------------

alter table "public"."scholarship_slots" enable row level security;
alter table "public"."scholarship_slot_events" enable row level security;

create policy "Enable read access for authenticated users" on public.scholarship_slots for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.scholarship_slots for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.scholarship_slots for update to authenticated using (true) with check (true);
create policy "Scholarship Slots Delete Policy" on public.scholarship_slots for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.scholarship_slot_events for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.scholarship_slot_events for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.scholarship_slot_events for update to authenticated using (true) with check (true);
create policy "Scholarship Slot Events Delete Policy" on public.scholarship_slot_events for delete to authenticated using (true);

grant all on table public.scholarship_slots to anon;
grant all on table public.scholarship_slots to authenticated;
grant all on table public.scholarship_slots to service_role;

grant all on table public.scholarship_slot_events to anon;
grant all on table public.scholarship_slot_events to authenticated;
grant all on table public.scholarship_slot_events to service_role;

grant all on sequence public.scholarship_slot_events_id_seq to anon;
grant all on sequence public.scholarship_slot_events_id_seq to authenticated;
grant all on sequence public.scholarship_slot_events_id_seq to service_role;

-- ---------------------------------------------------------------------
-- 4. Functions (full replacement bodies — see 02_functions.sql for the
--    canonical, commented source of truth)
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION "public"."handle_deal_saved"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_offer offers%ROWTYPE;
  v_cohort_offer_id bigint;
  v_contact contacts%ROWTYPE;
  v_option_offer_id bigint;
  v_option_pricing_mode text;
  v_rows int;
begin
  select * into v_offer from offers where id = new.offer_id;
  if v_offer.id is null then
    raise exception 'Invalid offer_id %', new.offer_id;
  end if;

  if new.cohort_id is not null then
    select offer_id into v_cohort_offer_id from cohorts where id = new.cohort_id;
    if v_cohort_offer_id is null then
      raise exception 'Invalid cohort_id %', new.cohort_id;
    end if;
    if v_offer.type <> 'group' then
      raise exception 'cohort_id can only be set on a group offer (offer_id %)', new.offer_id;
    end if;
    if v_cohort_offer_id <> new.offer_id then
      raise exception 'cohort_id % does not belong to offer_id %', new.cohort_id, new.offer_id;
    end if;
  end if;

  if tg_op = 'UPDATE' and old.stage = 'won' and new.pricing_mode is distinct from old.pricing_mode then
    raise exception 'Cannot change pricing_mode on deal % once it has reached Won', new.id;
  end if;

  if tg_op = 'INSERT' and new.pricing_mode = 'scholarship' then
    raise exception 'A new Opportunity cannot be created directly as scholarship — grant scholarship pricing via Deal edit after creation';
  end if;

  if tg_op = 'UPDATE'
     and old.pricing_mode = 'scholarship'
     and new.offer_id is distinct from old.offer_id
  then
    raise exception 'Cannot change offer_id on deal % while it holds a scholarship reservation — release scholarship pricing first', new.id;
  end if;

  if tg_op = 'UPDATE' and new.pricing_mode is distinct from old.pricing_mode then
    if new.pricing_mode = 'scholarship' then
      if v_offer.scholarship_price is null then
        raise exception 'Offer % has no scholarship price configured', new.offer_id;
      end if;

      insert into scholarship_slots (offer_id, holder_deal_id, reserved_at)
      values (new.offer_id, new.id, now())
      on conflict (offer_id) do update
        set holder_deal_id = excluded.holder_deal_id,
            reserved_at = excluded.reserved_at
        where scholarship_slots.holder_deal_id is null
          and scholarship_slots.holder_enrollment_id is null;
      get diagnostics v_rows = row_count;
      if v_rows = 0 then
        raise exception 'Scholarship slot for offer % is already held', new.offer_id;
      end if;

      insert into scholarship_slot_events (offer_id, deal_id, event_type, occurred_at)
      values (new.offer_id, new.id, 'scholarship_granted', now());
    elsif old.pricing_mode = 'scholarship' then
      update scholarship_slots
        set holder_deal_id = null, reserved_at = null, updated_at = now()
        where offer_id = old.offer_id and holder_deal_id = new.id;

      insert into scholarship_slot_events (offer_id, deal_id, event_type, occurred_at)
      values (old.offer_id, new.id, 'scholarship_released', now());
    end if;
  end if;

  if tg_op = 'INSERT'
     or new.offer_id is distinct from old.offer_id
     or new.pricing_mode is distinct from old.pricing_mode
  then
    new.offer_name_snapshot := v_offer.name;
    new.offer_price_snapshot := case
      when new.pricing_mode = 'scholarship' then v_offer.scholarship_price
      else v_offer.current_price
    end;
  end if;

  if new.selected_payment_option_id is not null
     and (tg_op = 'INSERT'
          or new.selected_payment_option_id is distinct from old.selected_payment_option_id
          or new.pricing_mode is distinct from old.pricing_mode)
  then
    select offer_id, pricing_mode, total, installments, installment_amount
      into v_option_offer_id, v_option_pricing_mode,
           new.selected_payment_total, new.selected_installment_count, new.selected_installment_amount
      from offer_payment_options
      where id = new.selected_payment_option_id;

    if v_option_offer_id is null then
      raise exception 'Invalid selected_payment_option_id %', new.selected_payment_option_id;
    end if;
    if v_option_offer_id <> new.offer_id or v_option_pricing_mode <> new.pricing_mode then
      raise exception 'Payment option % does not match deal %''s offer/pricing_mode', new.selected_payment_option_id, new.id;
    end if;
  end if;

  select * into v_contact from contacts where id = new.contact_id;
  if v_contact.id is not null then
    new.name := trim(both ' ' from coalesce(v_contact.first_name, '') || ' ' || coalesce(v_contact.last_name, ''));
  end if;

  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_deal_won"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_cohort cohorts%ROWTYPE;
  v_enrollment_id bigint;
  v_contact_name text;
  v_item record;
begin
  if new.stage = 'won' and (tg_op = 'INSERT' or old.stage is distinct from 'won') then
    if new.cohort_id is not null then
      select * into v_cohort from cohorts where id = new.cohort_id;
    end if;

    insert into enrollments (opportunity_id, status, start_date, end_date)
    values (
      new.id,
      'onboarding',
      v_cohort.program_start_at::date,
      v_cohort.program_end_at::date
    )
    on conflict (opportunity_id) do nothing
    returning id into v_enrollment_id;

    if v_enrollment_id is not null then
      select trim(both ' ' from coalesce(first_name, '') || ' ' || coalesce(last_name, ''))
        into v_contact_name
        from contacts where id = new.contact_id;
      if v_contact_name is null or v_contact_name = '' then
        v_contact_name := new.name;
      end if;

      for v_item in
        insert into enrollment_onboarding_items
          (enrollment_id, requirement_key, label, task_text_template, is_required, sort_order)
        select v_enrollment_id, t.key, t.label, t.task_text_template, t.is_required, t.sort_order
        from onboarding_requirement_templates t
        where t.offer_id = new.offer_id and t.is_active
        returning id, is_required, task_text_template
      loop
        if v_item.is_required then
          insert into tasks (contact_id, type, text, due_date, status, enrollment_id, onboarding_item_id)
          values (
            new.contact_id,
            'onboarding_item',
            replace(v_item.task_text_template, '{name}', v_contact_name),
            now() + interval '3 days',
            'pending',
            v_enrollment_id,
            v_item.id
          );
        end if;
      end loop;

      if new.pricing_mode = 'scholarship' then
        update scholarship_slots
          set holder_deal_id = null, holder_enrollment_id = v_enrollment_id, updated_at = now()
          where offer_id = new.offer_id and holder_deal_id = new.id;
        if not found then
          raise exception 'Deal % reached Won as scholarship but held no scholarship slot for offer % — data inconsistency', new.id, new.offer_id;
        end if;

        insert into scholarship_slot_events (offer_id, deal_id, enrollment_id, event_type, occurred_at)
        values (new.offer_id, new.id, v_enrollment_id, 'deal_converted_to_enrollment', now());
      end if;
    end if;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_enrollment_scholarship_slot_transition"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_offer_id bigint;
  v_rows int;
begin
  if new.status is distinct from old.status then
    if new.status = 'completed' then
      update scholarship_slots
        set holder_enrollment_id = null, updated_at = now()
        where holder_enrollment_id = new.id;
      if found then
        select offer_id into v_offer_id from deals where id = new.opportunity_id;
        insert into scholarship_slot_events (offer_id, enrollment_id, event_type, occurred_at)
        values (v_offer_id, new.id, 'enrollment_completed_slot_released', now());
      end if;
    elsif old.status = 'completed' then
      select offer_id into v_offer_id
        from deals
        where id = new.opportunity_id and pricing_mode = 'scholarship';

      if v_offer_id is not null then
        insert into scholarship_slots (offer_id, holder_enrollment_id, reserved_at)
        values (v_offer_id, new.id, now())
        on conflict (offer_id) do update
          set holder_enrollment_id = excluded.holder_enrollment_id,
              reserved_at = excluded.reserved_at
          where scholarship_slots.holder_deal_id is null
            and scholarship_slots.holder_enrollment_id is null;
        get diagnostics v_rows = row_count;
        if v_rows = 0 then
          raise exception 'Cannot reopen enrollment %: scholarship slot for offer % is already held by another Deal/Enrollment', new.id, v_offer_id;
        end if;

        insert into scholarship_slot_events (offer_id, enrollment_id, event_type, occurred_at)
        values (v_offer_id, new.id, 'slot_reclaimed_after_backward_lifecycle_correction', now());
      end if;
    end if;
  end if;
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- 5. Trigger
-- ---------------------------------------------------------------------

create or replace trigger on_enrollment_scholarship_slot_transition
    after update on public.enrollments
    for each row execute function public.handle_enrollment_scholarship_slot_transition();

-- ---------------------------------------------------------------------
-- 6. Locked seed data (Leif, 2026-09-09)
-- ---------------------------------------------------------------------

-- The Living Example (offer_id = 1): scholarship total $3,000.
update public.offers set scholarship_price = 3000.00 where id = 1;

-- Growing Yourself Up (offer_id = 2): scholarship total $700.
update public.offers set scholarship_price = 700.00 where id = 2;

insert into public.offer_payment_options
  (offer_id, name, total, installments, installment_amount, is_public, pricing_mode)
values
  (1, 'Scholarship — Pay in Full', 3000.00, 1, 3000.00, true, 'scholarship'),
  (1, 'Scholarship — 3 Installments', 3000.00, 3, 1000.00, true, 'scholarship'),
  (2, 'Scholarship — Pay in Full', 700.00, 1, 700.00, true, 'scholarship'),
  (2, 'Scholarship — 2 Installments', 700.00, 2, 350.00, true, 'scholarship');
