-- Outreach tracking: denormalized status on contacts + an events timeline table.

alter table public.contacts
    add column if not exists outreach_status text default 'not_contacted',
    add column if not exists last_emailed_at timestamp with time zone,
    add column if not exists last_outreach_at timestamp with time zone,
    add column if not exists instantly_campaign text;

create table if not exists public.outreach_events (
    id bigint generated by default as identity primary key,
    contact_id bigint not null references public.contacts (id) on delete cascade,
    type text not null,
    campaign text,
    summary text,
    occurred_at timestamp with time zone not null default now(),
    payload jsonb,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_outreach_events_contact
    on public.outreach_events using btree (contact_id, occurred_at desc);

alter table public.outreach_events enable row level security;

create policy "Enable read access for authenticated users" on public.outreach_events for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.outreach_events for insert to authenticated with check (true);
create policy "Outreach Events Update Policy" on public.outreach_events for update to authenticated using (true);
create policy "Outreach Events Delete Policy" on public.outreach_events for delete to authenticated using (true);

grant all on table public.outreach_events to anon;
grant all on table public.outreach_events to authenticated;
grant all on table public.outreach_events to service_role;

grant all on sequence public.outreach_events_id_seq to anon;
grant all on sequence public.outreach_events_id_seq to authenticated;
grant all on sequence public.outreach_events_id_seq to service_role;

-- Recreate the view to add the new outreach columns (Postgres requires DROP
-- when column order changes in a CREATE OR REPLACE VIEW).
drop view if exists public.contacts_summary;
create or replace view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    co.outreach_status,
    co.last_emailed_at,
    co.last_outreach_at,
    co.instantly_campaign,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
    left join public.companies c on co.company_id = c.id
group by co.id, c.name;
