-- Create import_jobs table to track CSV imports
create table if not exists "public"."import_jobs" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "completed_at" timestamp with time zone default null,
    "workspace_id" bigint not null references workspaces(id) on delete cascade,
    "entity_type" text not null check (entity_type in ('contact', 'company', 'deal')),
    "created_by" bigint not null references sales(id),
    "status" text not null check (status in ('pending', 'mapping', 'validating', 'importing', 'completed', 'failed', 'cancelled')) default 'pending',
    "total_rows" int default 0,
    "processed_rows" int default 0,
    "success_rows" int default 0,
    "failed_rows" int default 0,
    "file_name" text not null,
    "file_url" text default null,
    "mapping" jsonb default '{}'::jsonb,
    "validation_errors" jsonb default '[]'::jsonb,
    "failed_rows_data" jsonb default '[]'::jsonb,
    "options" jsonb default '{}'::jsonb
);

alter table "public"."import_jobs" enable row level security;

-- Create import_mapping_templates table to save reusable mappings
create table if not exists "public"."import_mapping_templates" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "workspace_id" bigint not null references workspaces(id) on delete cascade,
    "entity_type" text not null check (entity_type in ('contact', 'company', 'deal')),
    "name" text not null,
    "description" text default null,
    "mapping" jsonb not null,
    "is_default" boolean default false,
    "created_by" bigint not null references sales(id),
    unique(workspace_id, entity_type, name)
);

alter table "public"."import_mapping_templates" enable row level security;

-- Create indexes
create index if not exists import_jobs_workspace_idx on "public"."import_jobs"(workspace_id, status, created_at desc);
create index if not exists import_jobs_created_by_idx on "public"."import_jobs"(created_by);
create index if not exists import_mapping_templates_workspace_idx on "public"."import_mapping_templates"(workspace_id, entity_type);

-- RLS policies for import_jobs
create policy "Users can view import jobs in their workspace"
  on import_jobs for select
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

create policy "Users can create import jobs in their workspace"
  on import_jobs for insert
  with check (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

create policy "Users can update their own import jobs"
  on import_jobs for update
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
    and (
      created_by in (select id from sales where user_id = auth.uid())
      or
      workspace_id in (select workspace_id from sales where user_id = auth.uid() and administrator = true)
    )
  );

create policy "Users can delete their own import jobs"
  on import_jobs for delete
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
    and (
      created_by in (select id from sales where user_id = auth.uid())
      or
      workspace_id in (select workspace_id from sales where user_id = auth.uid() and administrator = true)
    )
  );

-- RLS policies for import_mapping_templates
create policy "Users can view mapping templates in their workspace"
  on import_mapping_templates for select
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

create policy "Users can create mapping templates"
  on import_mapping_templates for insert
  with check (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

create policy "Users can update their own mapping templates"
  on import_mapping_templates for update
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
    and (
      created_by in (select id from sales where user_id = auth.uid())
      or
      workspace_id in (select workspace_id from sales where user_id = auth.uid() and administrator = true)
    )
  );

create policy "Users can delete their own mapping templates"
  on import_mapping_templates for delete
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
    and (
      created_by in (select id from sales where user_id = auth.uid())
      or
      workspace_id in (select workspace_id from sales where user_id = auth.uid() and administrator = true)
    )
  );

-- Function to update updated_at timestamp
create or replace function update_import_job_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_import_job_updated_at
  before update on import_jobs
  for each row
  execute function update_import_job_updated_at();

create or replace function update_import_mapping_template_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_import_mapping_template_updated_at
  before update on import_mapping_templates
  for each row
  execute function update_import_mapping_template_updated_at();
