-- Historical Migration slice: the controlled-import mechanism for the
-- one-time historical Notion/Acuity/Stripe data migration (the frozen
-- Phase 3 dry-run manifest). This migration adds the MECHANISM only — it
-- imports zero historical client records itself.
--
-- Three problems solved, each with the smallest change that solves it:
--
-- 1. Historical Won deals must not fire live onboarding. handle_deal_won()
--    unconditionally creates a real Enrollment (status='onboarding') plus
--    onboarding checklist Tasks due "now() + 3 days" the instant
--    stage='won' is set (INSERT or UPDATE) -- correct for a real sale
--    closing today, wrong for a historical record from 2024/2025. Guarded
--    to return early when migration mode is on; the importer inserts the
--    correct, truthful FINAL-state Enrollment itself.
--
-- 2. Historical timestamps must survive, not get overwritten with now().
--    set_deal_stage_entered_at() and record_enrollment_status_event() both
--    unconditionally stamp now() -- guarded the same way. deals has a
--    stage_entered_at column to preserve a caller-supplied historical value
--    from; enrollments has no equivalent column, so for that one the
--    importer inserts enrollment_status_events rows itself, directly, with
--    the real historical date(s).
--
-- 3. Only a narrowly-authorized caller may ever turn migration mode on.
--    set_historical_migration_mode(boolean) is SECURITY DEFINER, pinned
--    search_path, and its own auth.role() check mirrors handle_deal_saved()'s
--    existing Won-authority guard exactly (NULL = trusted direct-connection
--    context, 'service_role' = the real webhook identity, anything else
--    rejected). Its ALTER-DEFAULT-PRIVILEGES grant to authenticated is
--    explicitly revoked below -- PUBLIC/anon never had it in the first
--    place (20260913230000_anon_table_grant_hardening.sql already narrowed
--    that). The GUC itself is set via set_config(..., true) -- the
--    is_local=true third argument -- so it is transaction-local by
--    PostgreSQL's own construction: it resets on COMMIT or ROLLBACK,
--    cannot leak into a later transaction on the same connection, and
--    cannot be observed by any other session at all.
--
-- Idempotency + auditability for the importer itself: historical_import_
-- records is a new, small, RLS-locked-to-service_role-only table (zero
-- policies -- see 05_policies.sql) giving a real database-enforced
-- idempotency key for entities that otherwise have none (most Pipeline/
-- Waitlist-only Contacts have neither a stripe_customer_id nor an
-- acuity_appointment_id to key off of), and a durable, queryable answer to
-- "did this record come from the 2026 historical migration" six months
-- from now. Deliberately one small table, not new columns bolted onto
-- contacts/deals/applications/waitlist_entries.
--
-- Hand-written, not CLI-generated: this sandbox has no Docker/Podman, so
-- `supabase db diff` cannot spin up its shadow database (same constraint as
-- every other hand-written migration this project has needed). Every
-- statement below matches the corresponding supabase/schemas/*.sql file
-- exactly.
--
-- This migration alone imports ZERO historical client records. It only
-- adds the mechanism a separate, explicitly-approved import step would use.

CREATE TABLE "public"."historical_import_records" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entity_table" text NOT NULL,
    "entity_id" bigint NOT NULL,
    "source_key" text NOT NULL,
    "source_system" text NOT NULL,
    "operation" text NOT NULL,
    "batch_id" text NOT NULL,
    -- Phase 4P: see 01_tables.sql for the full rationale.
    "evidence_notes" text,
    "imported_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "historical_import_records_entity_unique" UNIQUE ("entity_table", "entity_id"),
    CONSTRAINT "historical_import_records_source_unique" UNIQUE ("entity_table", "source_key"),
    -- 'notion_application' added in Phase 4G — see 01_tables.sql's own
    -- comment: the original LE/GYU application databases are a distinct
    -- source from the downstream 'notion_pipeline'.
    CONSTRAINT "historical_import_records_source_system_check" CHECK (source_system IN ('notion_pipeline', 'notion_waitlist', 'notion_application', 'acuity', 'stripe', 'existing_crm')),
    CONSTRAINT "historical_import_records_operation_check" CHECK (operation IN ('create', 'update'))
);

CREATE INDEX "historical_import_records_batch_id_idx" ON "public"."historical_import_records" USING btree (batch_id);

ALTER TABLE "public"."historical_import_records" ENABLE ROW LEVEL SECURITY;

revoke select, insert, update, delete on table "public"."historical_import_records" from "anon";
revoke select, insert, update, delete on table "public"."historical_import_records" from "authenticated";

CREATE OR REPLACE FUNCTION "public"."set_historical_migration_mode"("enable" boolean) RETURNS "void"
    LANGUAGE "plpgsql"
    SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
begin
  if auth.role() is not null and auth.role() <> 'service_role' then
    raise exception 'set_historical_migration_mode() is restricted to a service_role/direct-connection context';
  end if;
  perform set_config('app.migration_mode', case when enable then 'true' else 'false' end, true);
end;
$$;

revoke all on function public.set_historical_migration_mode(boolean) from public;
revoke all on function public.set_historical_migration_mode(boolean) from authenticated;
grant all on function public.set_historical_migration_mode(boolean) to service_role;

CREATE OR REPLACE FUNCTION "public"."handle_deal_won"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_cohort cohorts%ROWTYPE;
  v_enrollment_id bigint;
  v_contact_name text;
  v_item record;
begin
  -- Historical Migration slice: a historical Won Deal must never fire live
  -- onboarding (a real Enrollment at 'onboarding' status, checklist items,
  -- and Tasks due in 3 days from NOW) — the importer inserts the correct,
  -- truthful final-state Enrollment itself. See
  -- set_historical_migration_mode()'s own header for why this GUC check is
  -- safe: only that narrowly-restricted function can ever set it, and it is
  -- transaction-local by construction.
  if current_setting('app.migration_mode', true) = 'true' then
    return new;
  end if;

  if new.stage = 'won' and (tg_op = 'INSERT' or old.stage is distinct from 'won') then
    if new.cohort_id is not null then
      select * into v_cohort from cohorts where id = new.cohort_id;
    end if;

    -- Idempotent: the unique constraint on enrollments.opportunity_id means
    -- re-saving Won (or this trigger re-firing) never creates a duplicate.
    -- `returning ... into` only actually assigns on the genuine-insert
    -- path — the on-conflict no-op leaves v_enrollment_id null, which is
    -- exactly the signal the Contracts + Onboarding block below needs to
    -- stay just as replay-safe as the Enrollment creation it's gated on.
    insert into enrollments (opportunity_id, status, start_date, end_date)
    values (
      new.id,
      'onboarding',
      v_cohort.program_start_at::date,
      v_cohort.program_end_at::date
    )
    on conflict (opportunity_id) do nothing
    returning id into v_enrollment_id;

    if v_enrollment_id is not null then
      select trim(both ' ' from coalesce(first_name, '') || ' ' || coalesce(last_name, ''))
        into v_contact_name
        from contacts where id = new.contact_id;
      if v_contact_name is null or v_contact_name = '' then
        v_contact_name := new.name;
      end if;

      -- Seed this Enrollment's checklist from whichever requirement
      -- templates are currently active for this Deal's Offer (snapshotted,
      -- not a live reference — see onboarding_requirement_templates' own
      -- comment), one Task per REQUIRED item only (optional items get no
      -- auto-task — Contracts + Onboarding slice, §8/§11 of the
      -- architecture review).
      for v_item in
        insert into enrollment_onboarding_items
          (enrollment_id, requirement_key, label, task_text_template, is_required, sort_order)
        select v_enrollment_id, t.key, t.label, t.task_text_template, t.is_required, t.sort_order
        from onboarding_requirement_templates t
        where t.offer_id = new.offer_id and t.is_active
        returning id, is_required, task_text_template
      loop
        if v_item.is_required then
          insert into tasks (contact_id, type, text, due_date, status, enrollment_id, onboarding_item_id)
          values (
            new.contact_id,
            'onboarding_item',
            replace(v_item.task_text_template, '{name}', v_contact_name),
            -- Deliberately NOT now() — every required item due immediately
            -- at Enrollment creation would produce artificial overdue
            -- noise (someone paying late in the day reads as instantly
            -- behind). The Dashboard's Needs Onboarding section (driven
            -- directly off Enrollment state, not Tasks) is the primary
            -- "this person cannot disappear" signal; these Tasks' Overdue
            -- bucket is a secondary nudge, so a few real days of slack is
            -- correct, not a compromise.
            now() + interval '3 days',
            'pending',
            v_enrollment_id,
            v_item.id
          );
        end if;
      end loop;

      -- Scholarship Pricing + Capacity slice: atomically transition the
      -- slot this Deal holds (grant time) into Enrollment-held occupancy —
      -- a single UPDATE flipping both holder columns together, inside the
      -- same transaction as the enrollments INSERT above, so no other
      -- session can ever observe this Offer's slot as free between "Deal
      -- loses it" and "Enrollment gains it".
      if new.pricing_mode = 'scholarship' then
        update scholarship_slots
          set holder_deal_id = null, holder_enrollment_id = v_enrollment_id, updated_at = now()
          where offer_id = new.offer_id and holder_deal_id = new.id;
        if not found then
          raise exception 'Deal % reached Won as scholarship but held no scholarship slot for offer % — data inconsistency', new.id, new.offer_id;
        end if;

        insert into scholarship_slot_events (offer_id, deal_id, enrollment_id, event_type, occurred_at)
        values (new.offer_id, new.id, v_enrollment_id, 'deal_converted_to_enrollment', now());
      end if;
    end if;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."set_deal_stage_entered_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  -- Historical Migration slice: preserve the caller-supplied historical
  -- stage_entered_at verbatim instead of overwriting it with now() — see
  -- set_historical_migration_mode()'s own header.
  if current_setting('app.migration_mode', true) = 'true' then
    return new;
  end if;

  if tg_op = 'INSERT' or new.stage is distinct from old.stage then
    new.stage_entered_at := now();
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."record_enrollment_status_event"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  -- Historical Migration slice: enrollments has no per-status timestamp
  -- column of its own to source a truthful entered_at from (unlike deals'
  -- stage_entered_at), so there is nothing safe to substitute here — the
  -- importer inserts the correct, truthful enrollment_status_events row(s)
  -- itself, directly, with the real historical date(s). See
  -- set_historical_migration_mode()'s own header.
  if current_setting('app.migration_mode', true) = 'true' then
    return new;
  end if;

  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into enrollment_status_events (enrollment_id, status, entered_at)
    values (new.id, new.status, now());
  end if;
  return new;
end;
$$;

-- client_sessions gains 'completed' — see 01_tables.sql's own comment on
-- client_sessions_status_check for the full safety analysis (every live
-- consumer already either excludes only 'cancelled', or positively checks
-- 'booked' to gate an action that should correctly stay unavailable for a
-- completed historical session). No existing row changes; no live code
-- path sets this value — only the historical importer does.
alter table "public"."client_sessions" drop constraint "client_sessions_status_check";
alter table "public"."client_sessions" add constraint "client_sessions_status_check" check ((status = any (array['booked'::text, 'cancelled'::text, 'completed'::text]))) not valid;
alter table "public"."client_sessions" validate constraint "client_sessions_status_check";

-- applications gains 'denied' and 'waitlist' (Phase 4H) — see 01_tables.sql's
-- own comment on applications_status_check. Both are historical-import-only:
-- no live review action can ever set them (reviewApplication.ts's
-- ApplicationReviewOutcome is its own explicit type, deliberately not
-- derived from ApplicationStatus, precisely so these two can never leak
-- into a live review choice).
alter table "public"."applications" drop constraint "applications_status_check";
alter table "public"."applications" add constraint "applications_status_check" check ((status = any (array['pending'::text, 'approved'::text, 'needs_higher_care'::text, 'not_fit'::text, 'do_not_engage'::text, 'denied'::text, 'waitlist'::text]))) not valid;
alter table "public"."applications" validate constraint "applications_status_check";

-- Phase 4I: applications.offer_id / intended_cohort_id — see 01_tables.sql's
-- own column comments for the full architecture rationale (Leif's explicit
-- ruling: Application/Offer/Cohort-intent is a fact independent of Deal).
-- Both columns nullable for now; offer_id backfills deterministically from
-- every EXISTING row's Deal (every application row predating this migration
-- has opportunity_id NOT NULL, so its Offer is always knowable) and is
-- intended to tighten to NOT NULL in a LATER migration once backfilled —
-- not done here, so this migration alone cannot strand any row in a
-- contradictory state. intended_cohort_id has no backfill source (it is
-- new information the historical importer supplies going forward) and
-- stays nullable permanently by design.
alter table "public"."applications" add column "offer_id" bigint;
alter table "public"."applications" add column "intended_cohort_id" bigint;
alter table "public"."applications" add constraint "applications_offer_id_fkey" foreign key (offer_id) references public.offers(id);
alter table "public"."applications" add constraint "applications_intended_cohort_id_fkey" foreign key (intended_cohort_id) references public.cohorts(id);

-- Deterministic backfill for every application row that already exists
-- (none, on a fresh review of MAIN this round — see the final report's MAIN
-- read-only section — but this statement is correct and safe to include
-- regardless, since deals.offer_id is NOT NULL and the join is exact).
update "public"."applications" a
set "offer_id" = d.offer_id
from "public"."deals" d
where d.id = a.opportunity_id and a.offer_id is null;

-- Growing Yourself Up — January 2027 Cohort (Phase 4I, Leif's explicit
-- confirmation that this is a real cohort). Only offer_id/name/status are
-- NOT NULL on cohorts — every other column (dates, capacity) stays NULL
-- here deliberately: no application-open/close date, program start/end
-- date, or capacity figure is deterministically established in any pulled
-- source, and none is invented. status defaults to 'draft' (the correct
-- state for a cohort with no announced application window yet).
insert into "public"."cohorts" (offer_id, name)
select 2, 'Growing Yourself Up — January 2027'
where not exists (
  select 1 from "public"."cohorts" where offer_id = 2 and name = 'Growing Yourself Up — January 2027'
);


-- Phase 4O: applications.opportunity_id becomes nullable — the Phase 4H
-- proposal, actually applied now (real Postgres rejected the first Gate A
-- Contact+Application-only batch on this exact NOT NULL). See
-- 01_tables.sql's own comment on applications.opportunity_id.
ALTER TABLE "public"."applications" ALTER COLUMN "opportunity_id" DROP NOT NULL;

-- ===========================================================================
-- Gate A final candidate: an Application belongs to a CONTACT
-- ===========================================================================
-- Before this, an Application's only route to a person was
-- opportunity_id -> deals.contact_id. Gate A proved that leaves 88 of 159
-- legitimate historical Applications stored but unreachable, because those
-- applicants never became a sales Opportunity. The alternative — inventing
-- 88 Deals — would falsify sales history, so the relationship is fixed
-- instead:
--
--   Contact  -> Application            (canonical, required)
--   Deal     -> Application            (optional Opportunity relationship)
--
-- Additive and ordered so it is safe against whatever legitimate live
-- Applications MAIN holds at deploy time: add nullable, backfill, PROVE
-- every row resolved, only then enforce NOT NULL.

ALTER TABLE "public"."applications" ADD COLUMN IF NOT EXISTS "contact_id" bigint;

-- Record origin, same convention as sales_calls.source / client_sessions.source.
ALTER TABLE "public"."applications" ADD COLUMN IF NOT EXISTS "source" text NOT NULL DEFAULT 'public_form';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'applications_source_check') THEN
    ALTER TABLE "public"."applications"
      ADD CONSTRAINT "applications_source_check" CHECK (source IN ('public_form', 'historical_import'));
  END IF;
END $$;

-- Backfill from the only person relationship that existed before now. Every
-- live Application has an Opportunity (submit_public_application() always
-- resolves a Deal before inserting), so this resolves all of them.
UPDATE "public"."applications" a
   SET contact_id = d.contact_id
  FROM "public"."deals" d
 WHERE a.opportunity_id = d.id
   AND a.contact_id IS NULL;

-- Prove, then enforce. If any Application cannot be resolved to a Contact,
-- abort the migration loudly rather than leave the canonical relationship
-- optional or invent a person for it.
DO $$
DECLARE v_unresolved bigint;
BEGIN
  SELECT count(*) INTO v_unresolved FROM "public"."applications" WHERE contact_id IS NULL;
  IF v_unresolved > 0 THEN
    RAISE EXCEPTION
      'applications.contact_id backfill incomplete: % row(s) have no resolvable Contact. Resolve each one explicitly before deploying — never fabricate a Contact or a Deal.', v_unresolved;
  END IF;
END $$;

ALTER TABLE "public"."applications" ALTER COLUMN "contact_id" SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'applications_contact_id_fkey') THEN
    ALTER TABLE "public"."applications"
      ADD CONSTRAINT "applications_contact_id_fkey"
      FOREIGN KEY (contact_id) REFERENCES "public"."contacts"(id) ON UPDATE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "applications_contact_id_idx" ON "public"."applications" USING btree (contact_id);

-- Re-issued HERE, after applications.contact_id exists, rather than earlier
-- in this file: the body writes applications(contact_id, ...), and although
-- plpgsql resolves column references at runtime (so an earlier definition
-- would still deploy), defining it before the column exists leaves a window
-- in which a live public application submission would fail. Ordering it
-- after the column removes that window entirely.
-- Phase 4J: submit_public_application() re-issued to stamp the two new
-- applications columns at live-intake write time (offer_id/intended_cohort_id
-- from the already-validated p_offer_id/p_cohort_id — never re-derived from
-- the Deal). Every other line is byte-identical to the current deployed body;
-- only the two lines around the INSERT changed (marked with a Phase 4J
-- comment) — see 02_functions.sql for the source of truth this mirrors.
CREATE OR REPLACE FUNCTION "public"."submit_public_application"(
    "p_offer_id" bigint,
    "p_cohort_id" bigint,
    "p_first_name" text,
    "p_last_name" text,
    "p_email" text,
    "p_phone" text,
    "p_answers" jsonb
) RETURNS jsonb
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_email text := lower(trim(p_email));
  v_contact contacts%ROWTYPE;
  v_is_dne boolean;
  v_deal deals%ROWTYPE;
  v_deal_reused boolean := false;
  v_pending_app applications%ROWTYPE;
  v_answers_match boolean := false;
  v_application_id bigint;
  v_existing_application_id bigint;
  v_sales_id bigint;
  v_has_pending_task boolean;
  v_applicant_name text;
BEGIN
  IF p_offer_id IS NULL THEN
    RAISE EXCEPTION 'offer_invalid' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  IF coalesce(trim(p_first_name), '') = '' OR coalesce(trim(p_last_name), '') = '' THEN
    RAISE EXCEPTION 'name_invalid' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  IF v_email = '' THEN
    RAISE EXCEPTION 'email_invalid' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM offers WHERE id = p_offer_id AND is_active) THEN
    RAISE EXCEPTION 'offer_invalid' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  IF p_cohort_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM cohorts WHERE id = p_cohort_id AND offer_id = p_offer_id
  ) THEN
    RAISE EXCEPTION 'cohort_invalid' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('submit_public_application:' || v_email));

  SELECT * INTO v_contact
  FROM contacts c
  WHERE EXISTS (
    SELECT 1 FROM jsonb_array_elements(coalesce(c.email_jsonb, '[]'::jsonb)) AS e
    WHERE lower(trim(e ->> 'email')) = v_email
  )
  ORDER BY c.id ASC
  LIMIT 1;

  v_is_dne := v_contact.id IS NOT NULL AND v_contact.sales_eligibility = 'do_not_engage';

  IF v_contact.id IS NOT NULL AND NOT v_is_dne THEN
    SELECT * INTO v_deal
    FROM deals d
    WHERE d.contact_id = v_contact.id
      AND d.offer_id = p_offer_id
      AND (p_cohort_id IS NULL OR d.cohort_id = p_cohort_id)
      AND d.archived_at IS NULL
      AND d.stage <> 'won'
      AND d.outcome IS NULL
    ORDER BY d.id ASC
    LIMIT 1;
  END IF;

  IF v_deal.id IS NOT NULL THEN
    SELECT * INTO v_pending_app
    FROM applications a
    WHERE a.opportunity_id = v_deal.id
    ORDER BY a.id DESC
    LIMIT 1;
    IF v_pending_app.id IS NOT NULL AND v_pending_app.status <> 'pending' THEN
      v_pending_app := NULL;
    END IF;
  END IF;

  IF v_pending_app.id IS NOT NULL THEN
    v_answers_match := p_answers = v_pending_app.raw_answers;
  END IF;

  IF v_contact.id IS NOT NULL AND NOT v_is_dne THEN
    SELECT EXISTS (
      SELECT 1 FROM tasks
      WHERE contact_id = v_contact.id
        AND type = 'review_application'
        AND done_date IS NULL
    ) INTO v_has_pending_task;
  END IF;

  IF v_pending_app.id IS NOT NULL AND v_answers_match AND coalesce(v_has_pending_task, false) THEN
    RETURN jsonb_build_object(
      'status', 'submitted',
      'application_id', v_pending_app.id,
      'dne_auto_resolved', false
    );
  END IF;

  IF v_contact.id IS NOT NULL THEN
    UPDATE contacts SET last_seen = now() WHERE id = v_contact.id RETURNING * INTO v_contact;
  ELSE
    INSERT INTO contacts (
      first_name, last_name, email_jsonb, phone_jsonb, tags,
      has_newsletter, first_seen, last_seen, sales_eligibility
    ) VALUES (
      p_first_name, p_last_name,
      jsonb_build_array(jsonb_build_object('email', p_email, 'type', 'Other')),
      CASE WHEN coalesce(p_phone, '') <> ''
        THEN jsonb_build_array(jsonb_build_object('number', p_phone, 'type', 'Other'))
        ELSE '[]'::jsonb
      END,
      ARRAY[]::bigint[],
      false, now(), now(), 'normal'
    ) RETURNING * INTO v_contact;
  END IF;

  IF v_deal.id IS NULL THEN
    INSERT INTO deals (
      contact_id, offer_id, cohort_id, stage, outcome, owner_decision,
      amount, entry_path, description
    ) VALUES (
      v_contact.id, p_offer_id, p_cohort_id, 'application_received',
      CASE WHEN v_is_dne THEN 'lost' ELSE NULL END,
      CASE WHEN v_is_dne THEN 'do_not_engage' ELSE NULL END,
      (SELECT current_price FROM offers WHERE id = p_offer_id),
      'application_form', ''
    ) RETURNING * INTO v_deal;
  ELSE
    v_deal_reused := true;
    IF NOT v_is_dne THEN
      UPDATE waitlist_entries
      SET status = 'converted', converted_at = now(), converted_opportunity_id = v_deal.id
      WHERE contact_id = v_deal.contact_id
        AND offer_id = v_deal.offer_id
        AND status IN ('waiting', 'invited')
        AND (cohort_id IS NULL OR cohort_id = v_deal.cohort_id);
    END IF;
  END IF;

  IF v_pending_app.id IS NOT NULL THEN
    UPDATE applications
    SET raw_answers = p_answers, submitted_at = now()
    WHERE id = v_pending_app.id
    RETURNING id INTO v_application_id;
  ELSE
    SELECT a.id INTO v_existing_application_id
    FROM applications a
    WHERE a.opportunity_id = v_deal.id
    ORDER BY a.id DESC
    LIMIT 1;

    IF v_existing_application_id IS NOT NULL THEN
      v_application_id := v_existing_application_id;
    ELSE
      -- Phase 4J: offer_id/intended_cohort_id stamped directly from the
      -- already-validated parameters, never re-derived from v_deal.
      -- Phase 4J: offer_id/intended_cohort_id stamped directly from the
      -- already-validated parameters, never re-derived from v_deal.
      -- Gate A final candidate: contact_id is the Application's canonical
      -- person relationship (the Deal remains the optional Opportunity
      -- relationship), and source marks this as a live submission that
      -- legitimately represents outstanding review work.
      INSERT INTO applications (contact_id, opportunity_id, offer_id, intended_cohort_id, raw_answers, submitted_at, status, reviewed_at, source)
      VALUES (
        v_contact.id, v_deal.id, p_offer_id, p_cohort_id, p_answers, now(),
        CASE WHEN v_is_dne THEN 'do_not_engage' ELSE 'pending' END,
        CASE WHEN v_is_dne THEN now() ELSE NULL END,
        'public_form'
      ) RETURNING id INTO v_application_id;
    END IF;
  END IF;

  IF NOT v_is_dne THEN
    SELECT EXISTS (
      SELECT 1 FROM tasks
      WHERE contact_id = v_contact.id
        AND type = 'review_application'
        AND done_date IS NULL
    ) INTO v_has_pending_task;

    IF NOT v_has_pending_task THEN
      SELECT id INTO v_sales_id FROM sales WHERE administrator = true LIMIT 1;
      v_applicant_name := trim(both ' ' from coalesce(v_contact.first_name, '') || ' ' || coalesce(v_contact.last_name, ''));
      INSERT INTO tasks (contact_id, type, text, due_date, status, sales_id)
      VALUES (
        v_contact.id, 'review_application',
        'Review ' || v_applicant_name || '''s application',
        now(), 'pending', v_sales_id
      );
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'status', 'submitted',
    'application_id', v_application_id,
    'dne_auto_resolved', v_is_dne
  );
END;
$$;


-- ===========================================================================
-- Gate A final candidate: migration mode must not perform avatar HTTP
-- enrichment
-- ===========================================================================
-- handle_contact_saved() resolves a Contact avatar by calling gravatar.com
-- and then the email domain favicon service. That is an outbound request
-- per imported Contact during a bulk historical import, sending a hash of
-- each real client email address to a third party to decorate a back-filled
-- record. Guarded to skip ONLY that enrichment under migration mode.
-- Database-local contact invariants are unaffected: sales_id defaulting
-- (set_sales_id_default) and email lowercasing (lowercase_email_jsonb) are
-- separate triggers and continue to run. Normal live saves are unchanged.
CREATE OR REPLACE FUNCTION "public"."handle_contact_saved"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$declare contact_avatar text;
declare emails_length int8;
declare item jsonb;

begin
    if new.avatar is not null then
        return new;
    end if;

    -- Historical Migration slice: everything below this point is OUTBOUND
    -- HTTP enrichment — get_avatar_for_email() calls gravatar.com and then
    -- the email domain's favicon service. A bulk historical import fires
    -- one lookup per imported Contact, transmitting a hash of each real
    -- person's email address to third parties purely to decorate
    -- back-filled records (Gate A measured 271 such lookups). Migration
    -- mode skips the network enrichment ONLY: avatar is simply left null,
    -- to be filled by any later ordinary save. Every database-local
    -- contact invariant is untouched — sales_id defaulting and email
    -- lowercasing are their own separate triggers and still run. See
    -- set_historical_migration_mode()'s header for why this GUC is safe.
    if current_setting('app.migration_mode', true) = 'true' then
        return new;
    end if;

    select coalesce(jsonb_array_length(new.email_jsonb), 0) into emails_length;

    if emails_length = 0 then
        return new;
    end if;

    for item in select jsonb_array_elements(new.email_jsonb)
    loop
        select public.get_avatar_for_email(item->>'email') into contact_avatar;
        if (contact_avatar is not null) then
            exit;
        end if;
    end loop;

    if contact_avatar is null then
        return new;
    end if;

    new.avatar = concat('{"src":"', contact_avatar, '"}');
    return new;
end;$$;

-- ===========================================================================
-- Gate B: a no-showed sales call exits the Opportunity, atomically
-- ===========================================================================
-- Before this, completeSalesCallOutcome.ts's no_show branch deliberately
-- made NO Opportunity write, so a no-showed Deal sat at stage 'call_booked'
-- with outcome null — i.e. still in the active pipeline, indistinguishable
-- from a call that is still upcoming. A 'sales_call_no_show' Task existed
-- only to paper over that. Leif's rule: the no-show itself is certain
-- enough to exit the Opportunity, so the Deal leaves the pipeline and the
-- follow-up Task is no longer created.
--
-- One human action => one transaction. See the function body for why each
-- related change is represented the way it is.

CREATE OR REPLACE FUNCTION "public"."record_sales_call_no_show"("p_sales_call_id" bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  v_call sales_calls%ROWTYPE;
  v_tag_id bigint;
  v_now timestamptz := now();
  v_deal_exited boolean := false;
begin
  -- Gate B: marking a sales call No-show is ONE human action, so it is one
  -- transaction. Every related state change below either all lands or none
  -- does: the CRM can never persist "Sales Call = no_show" while the
  -- Opportunity stays in the active pipeline, or exit the Opportunity
  -- without the Contact carrying the visible history — which is exactly
  -- what a sequence of independent UI writes could do if one failed.
  --
  -- Narrow by construction: this fires only when this function is called,
  -- never on arbitrary sales_calls UPDATEs, so ordinary edits/reschedules
  -- keep their existing behavior.
  select * into v_call from sales_calls where id = p_sales_call_id for update;
  if not found then
    return jsonb_build_object('status', 'not-found');
  end if;
  if v_call.opportunity_id is null then
    -- An unmatched booking has no Opportunity to exit yet.
    return jsonb_build_object('status', 'no-opportunity');
  end if;
  if v_call.attendance = 'attended' then
    -- Never silently overwrite a recorded attended outcome.
    return jsonb_build_object('status', 'already-completed');
  end if;

  -- 1. The Sales Call is the CANONICAL historical record of the no-show.
  --    status leaves 'booked' so the partial unique index
  --    (sales_calls_one_booked_per_opportunity_idx) does not block a later
  --    genuine rebooking.
  if v_call.attendance is distinct from 'no_show' then
    update sales_calls
       set attendance = 'no_show',
           attendance_recorded_at = v_now,
           status = 'completed',
           updated_at = v_now
     where id = v_call.id;

    insert into sales_call_events (sales_call_id, kind, occurred_at, attendance)
    values (v_call.id, 'attendance_recorded', v_now, 'no_show');
  elsif v_call.status <> 'completed' then
    -- Already recorded as a no-show but never concluded: a row written
    -- before a concluded call was required to leave 'booked'. Converge the
    -- status WITHOUT inventing a second attendance timestamp or a
    -- duplicate history event — the original attendance_recorded_at is the
    -- truth about when it was observed. Leaving it at 'booked' would keep
    -- blocking a genuine rebooking via the partial unique index.
    update sales_calls
       set status = 'completed',
           updated_at = v_now
     where id = v_call.id;
  end if;

  -- 2. The Opportunity exits the ACTIVE pipeline. "Active" is canonically
  --    archived_at is null AND stage <> 'won' AND outcome is null (see
  --    DealList.tsx's own filter), so setting outcome is the existing exit
  --    mechanism — no new stage, no new column, no Nurture. 'lost' is the
  --    same exit the Do-Not-Engage path already uses (deals/dneOutcome.ts);
  --    the REASON stays durable on the Sales Call itself (attendance =
  --    'no_show'), which is why no reason column is invented here.
  --    stage is deliberately NOT rewritten: the Deal genuinely reached
  --    Call Booked, and falsifying stage history to mark an exit would
  --    destroy that truth.
  update deals
     set outcome = 'lost',
         updated_at = v_now
   where id = v_call.opportunity_id
     and outcome is null
     and archived_at is null
     and stage <> 'won';
  v_deal_exited := found;

  -- 3. The Contact carries a durable, visible No-show tag — reusing the
  --    existing tags table + contacts.tags array, not a bespoke boolean.
  --    It is a SUMMARY for at-a-glance history, never the source of truth
  --    (that stays the Sales Call), and it is attached at most once.
  select id into v_tag_id from tags where lower(name) = 'no-show' limit 1;
  if v_tag_id is null then
    insert into tags (name, color) values ('No-show', '#fde2e4')
    returning id into v_tag_id;
  end if;

  update contacts
     set tags = coalesce(tags, '{}'::bigint[]) || v_tag_id
   where id = v_call.contact_id
     and not (coalesce(tags, '{}'::bigint[]) @> array[v_tag_id]);

  -- 4. Task lifecycle. The call concluded, so its "Sales Call" task is
  --    done. NO ordinary follow-up task is created: the Opportunity has
  --    left the pipeline, so there is no stranded work to re-surface —
  --    that visibility gap was the only reason the old
  --    'sales_call_no_show' task existed. Any such task still pending from
  --    before this rule is superseded work, so it is closed rather than
  --    left behind as impossible work.
  update tasks
     set done_date = v_now, status = 'completed'
   where contact_id = v_call.contact_id
     and type in ('sales_call', 'sales_call_no_show')
     and done_date is null;

  return jsonb_build_object(
    'status', case when v_call.attendance = 'no_show' then 'already-no-show' else 'completed' end,
    'sales_call_id', v_call.id,
    'opportunity_id', v_call.opportunity_id,
    'contact_id', v_call.contact_id,
    'deal_exited', v_deal_exited,
    'tag_id', v_tag_id
  );
end;
$$;

revoke all on function public.record_sales_call_no_show(bigint) from public;
grant execute on function public.record_sales_call_no_show(bigint) to authenticated;
grant execute on function public.record_sales_call_no_show(bigint) to service_role;

-- ===========================================================================
-- Pre-live UX: a manually-created Waitlist Entry records itself as 'manual'
-- ===========================================================================
-- waitlist_entries.source carried only marketing-attribution values, so an
-- entry Leif adds by hand in the CRM had nothing truthful to say about
-- where it came from and rendered as "Unknown". 'manual' is the same
-- record-origin value sales_calls.source and client_sessions.source
-- already use for exactly this ("a human created this row here").
ALTER TABLE "public"."waitlist_entries"
  DROP CONSTRAINT IF EXISTS "waitlist_entries_source_check";
ALTER TABLE "public"."waitlist_entries"
  ADD CONSTRAINT "waitlist_entries_source_check"
  CHECK (source IN ('instagram', 'referral', 'podcast', 'workshop', 'substack', 'google', 'other', 'manual'));

-- ===========================================================================
-- Waitlist invitations: batches + per-person invitation events
-- ===========================================================================
-- Leif's real workflow: when the sales-call calendar reopens he invites a
-- large batch (30-40 people) off a waitlist to book. That is a durable
-- business event, not an email feature — Gmail will later be a DELIVERY
-- MECHANISM attached to these records.
--
-- Why not just waitlist_entries.status = 'invited': a membership can
-- legitimately be invited more than once over its life (August, never
-- books; October, never books; January, books). One status + one
-- invited_at can only remember the most recent invitation, so every
-- earlier one — and the fact that this person has been asked three times —
-- would be silently overwritten. Same append-only shape as the existing
-- deal_stage_events / sales_call_events / enrollment_status_events tables.

CREATE TABLE IF NOT EXISTS "public"."waitlist_invitation_batches" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "offer_id" bigint NOT NULL,
    "cohort_id" bigint,
    "label" text,
    "status" text NOT NULL DEFAULT 'prepared',
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "waitlist_invitation_batches_status_check"
        CHECK (status IN ('prepared', 'sending', 'completed', 'cancelled')),
    CONSTRAINT "waitlist_invitation_batches_offer_id_fkey"
        FOREIGN KEY (offer_id) REFERENCES "public"."offers"(id),
    CONSTRAINT "waitlist_invitation_batches_cohort_id_fkey"
        FOREIGN KEY (cohort_id) REFERENCES "public"."cohorts"(id)
);

CREATE TABLE IF NOT EXISTS "public"."waitlist_invitations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "batch_id" bigint NOT NULL,
    "waitlist_entry_id" bigint NOT NULL,
    "contact_id" bigint NOT NULL,
    "status" text NOT NULL DEFAULT 'prepared',
    "delivery_method" text,
    "prepared_at" timestamp with time zone NOT NULL DEFAULT now(),
    "sent_at" timestamp with time zone,
    "failed_at" timestamp with time zone,
    "failure_reason" text,
    "booked_sales_call_id" bigint,
    "booked_at" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "waitlist_invitations_status_check"
        CHECK (status IN ('prepared', 'sent', 'failed', 'cancelled')),
    CONSTRAINT "waitlist_invitations_delivery_method_check"
        CHECK (delivery_method IN ('manual', 'gmail')),
    -- Structural guarantee that nothing is ever marked delivered without
    -- real delivery evidence.
    CONSTRAINT "waitlist_invitations_sent_evidence_check"
        CHECK (status <> 'sent' OR (sent_at IS NOT NULL AND delivery_method IS NOT NULL)),
    CONSTRAINT "waitlist_invitations_batch_id_fkey"
        FOREIGN KEY (batch_id) REFERENCES "public"."waitlist_invitation_batches"(id),
    CONSTRAINT "waitlist_invitations_waitlist_entry_id_fkey"
        FOREIGN KEY (waitlist_entry_id) REFERENCES "public"."waitlist_entries"(id),
    CONSTRAINT "waitlist_invitations_contact_id_fkey"
        FOREIGN KEY (contact_id) REFERENCES "public"."contacts"(id),
    CONSTRAINT "waitlist_invitations_booked_sales_call_id_fkey"
        FOREIGN KEY (booked_sales_call_id) REFERENCES "public"."sales_calls"(id)
);

-- One invitation per membership PER BATCH — never one per membership
-- forever. Re-inviting the same person in a later batch is the point.
CREATE UNIQUE INDEX IF NOT EXISTS "waitlist_invitations_batch_entry_idx"
    ON "public"."waitlist_invitations" USING btree (batch_id, waitlist_entry_id);
CREATE INDEX IF NOT EXISTS "waitlist_invitations_contact_id_idx"
    ON "public"."waitlist_invitations" USING btree (contact_id);
CREATE INDEX IF NOT EXISTS "waitlist_invitations_waitlist_entry_id_idx"
    ON "public"."waitlist_invitations" USING btree (waitlist_entry_id);
CREATE INDEX IF NOT EXISTS "waitlist_invitations_batch_id_idx"
    ON "public"."waitlist_invitations" USING btree (batch_id);

ALTER TABLE "public"."waitlist_invitation_batches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."waitlist_invitations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON "public"."waitlist_invitation_batches" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON "public"."waitlist_invitation_batches" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON "public"."waitlist_invitation_batches" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable read access for authenticated users" ON "public"."waitlist_invitations" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON "public"."waitlist_invitations" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON "public"."waitlist_invitations" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

GRANT ALL ON TABLE "public"."waitlist_invitation_batches" TO authenticated;
GRANT ALL ON TABLE "public"."waitlist_invitation_batches" TO service_role;
GRANT ALL ON TABLE "public"."waitlist_invitations" TO authenticated;
GRANT ALL ON TABLE "public"."waitlist_invitations" TO service_role;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."waitlist_invitation_batches" FROM anon;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."waitlist_invitations" FROM anon;
