-- ===========================================================================
-- An Acuity appointment type does not mean one thing forever
-- ===========================================================================
-- acuity_appointment_type_map keyed the appointment type as its PRIMARY KEY,
-- which encodes "one type, one meaning, for all time". That is false, and
-- Leif's own business history is the counterexample:
--
--   Acuity type 64654501 is called "Growing Yourself Up" today, and today
--   that is what booking it means. But GYU did not exist in 2024-2025. The
--   fifteen 2024-2025 bookings still sitting on that type were Leif's
--   earlier 1:1 coaching work, and reading them through the type's CURRENT
--   name would invent a GYU sales history that never happened — GYU
--   Opportunities, GYU cohort intent, GYU pipeline state, none of it real.
--
-- So the meaning becomes effective-dated: a type may hold several mappings,
-- each valid for a period, and resolution takes the APPOINTMENT'S DATE as
-- well as its type. A reconciliation reading a 2025 booking gets the 2025
-- meaning; one reading next week's booking gets today's.
--
-- Note on what this table is and is not. It resolves what a booking was
-- ABOUT when no stronger evidence exists — a new booking, or an unmatched
-- historical one. It never overrides an Opportunity a booking is already
-- attached to: those attachments came from Leif's Notion records, which are
-- business truth and do not follow appointment type at all (a 2026-03-05
-- booking on the "GYU" type is attached to a Living Example Opportunity,
-- correctly). Evidence outranks inference; this is the inference.

-- ---------------------------------------------------------------------------
-- 1. Re-key the table so one type can hold several periods.
-- ---------------------------------------------------------------------------
ALTER TABLE "public"."acuity_appointment_type_map"
  ADD COLUMN IF NOT EXISTS "id" bigint GENERATED BY DEFAULT AS IDENTITY;

-- valid_from is inclusive, valid_to EXCLUSIVE — so adjacent periods are
-- written [a, b) and [b, ...) with no overlap and no one-day gap to get
-- wrong. NULL valid_to means "still current".
ALTER TABLE "public"."acuity_appointment_type_map"
  ADD COLUMN IF NOT EXISTS "valid_from" date NOT NULL DEFAULT '-infinity',
  ADD COLUMN IF NOT EXISTS "valid_to" date;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'acuity_appointment_type_map_pkey'
       AND conrelid = 'public.acuity_appointment_type_map'::regclass
  ) THEN
    ALTER TABLE "public"."acuity_appointment_type_map"
      DROP CONSTRAINT "acuity_appointment_type_map_pkey";
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'acuity_appointment_type_map_id_pkey'
  ) THEN
    ALTER TABLE "public"."acuity_appointment_type_map"
      ADD CONSTRAINT "acuity_appointment_type_map_id_pkey" PRIMARY KEY ("id");
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'acuity_appointment_type_map_period_check'
  ) THEN
    ALTER TABLE "public"."acuity_appointment_type_map"
      ADD CONSTRAINT "acuity_appointment_type_map_period_check"
      CHECK (valid_to IS NULL OR valid_to > valid_from);
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Two mappings for the same type may never claim the same day.
-- ---------------------------------------------------------------------------
-- Enforced by trigger rather than an EXCLUDE constraint so production does
-- not need the btree_gist extension installed for a table this small. This
-- is hand-maintained configuration, not a concurrent write path, so the
-- check-then-insert window is not a practical race.
CREATE OR REPLACE FUNCTION "public"."acuity_type_period_no_overlap"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v_conflict text;
begin
  select coalesce(m.label, m.id::text) into v_conflict
    from acuity_appointment_type_map m
   where m.acuity_appointment_type_id = new.acuity_appointment_type_id
     and m.id <> coalesce(new.id, -1)
     -- Two half-open periods [a,b) and [c,d) overlap iff a < d and c < b,
     -- with NULL upper bounds read as infinity.
     and new.valid_from < coalesce(m.valid_to, 'infinity'::date)
     and m.valid_from < coalesce(new.valid_to, 'infinity'::date)
   limit 1;

  if v_conflict is not null then
    raise exception 'acuity appointment type % already has a mapping covering that period (%)',
      new.acuity_appointment_type_id, v_conflict;
  end if;
  return new;
end;
$$;

DROP TRIGGER IF EXISTS "acuity_type_period_no_overlap_trigger" ON "public"."acuity_appointment_type_map";
CREATE TRIGGER "acuity_type_period_no_overlap_trigger"
  BEFORE INSERT OR UPDATE OF "acuity_appointment_type_id", "valid_from", "valid_to"
  ON "public"."acuity_appointment_type_map"
  FOR EACH ROW EXECUTE FUNCTION "public"."acuity_type_period_no_overlap"();

CREATE INDEX IF NOT EXISTS "acuity_appointment_type_map_lookup_idx"
  ON "public"."acuity_appointment_type_map"
  USING btree ("acuity_appointment_type_id", "valid_from");

-- ---------------------------------------------------------------------------
-- 3. The one resolution entry point.
-- ---------------------------------------------------------------------------
-- Every caller — historical backfill, periodic reconciliation, the webhook,
-- any future helper — asks this question and gets the meaning that was true
-- on the appointment's own date. Passing the date is not optional, which is
-- the point: there is no way to accidentally resolve a historical booking
-- through today's mapping.
CREATE OR REPLACE FUNCTION "public"."resolve_acuity_appointment_type"(
  "p_appointment_type_id" text,
  "p_on" date
) RETURNS TABLE (
  "offer_id" bigint,
  "offer_name" text,
  "kind" text,
  "cohort_id" bigint,
  "label" text,
  "valid_from" date,
  "valid_to" date
)
    LANGUAGE "sql"
    STABLE
    SET "search_path" TO 'public'
    AS $$
  select m.offer_id, o.name, m.kind, m.cohort_id, m.label, m.valid_from, m.valid_to
    from acuity_appointment_type_map m
    join offers o on o.id = m.offer_id
   where m.acuity_appointment_type_id = p_appointment_type_id
     and p_on >= m.valid_from
     and (m.valid_to is null or p_on < m.valid_to)
   limit 1;
$$;

-- ---------------------------------------------------------------------------
-- 4. The periods, from Leif's stated business history.
-- ---------------------------------------------------------------------------
-- Boundary 2026-01-01 is Leif's own division: "2024-2025 appointment type
-- 64654501 -> historical 1:1 / legacy coaching. Current-era 64654501 -> GYU
-- sales call." Every one of the fifteen unmatched bookings on that type
-- falls on 2025-10-01 or earlier, and every genuine GYU booking is
-- 2026-03-05 or later, so the boundary separates them cleanly with room on
-- both sides.
DO $$
DECLARE
  v_legacy bigint;
  v_gyu    bigint;
  v_le     bigint;
BEGIN
  SELECT id INTO v_legacy FROM offers WHERE name = '1:1 Coaching (Legacy)';
  SELECT id INTO v_gyu    FROM offers WHERE name = 'Growing Yourself Up';
  SELECT id INTO v_le     FROM offers WHERE name = 'The Living Example';

  IF v_legacy IS NULL OR v_gyu IS NULL OR v_le IS NULL THEN
    RAISE EXCEPTION 'expected Offers are missing: legacy=% gyu=% le=%', v_legacy, v_gyu, v_le;
  END IF;

  -- 64654501: close the existing open-ended GYU row at the boundary, then
  -- add the legacy period before it.
  UPDATE acuity_appointment_type_map
     SET valid_from = DATE '2026-01-01',
         label = 'Growing Yourself Up sales call (current era)'
   WHERE acuity_appointment_type_id = '64654501'
     AND valid_from = DATE '-infinity';

  INSERT INTO acuity_appointment_type_map
    (acuity_appointment_type_id, offer_id, kind, is_current, label, valid_from, valid_to)
  SELECT '64654501', v_legacy, 'sales_call', false,
         'pre-GYU 1:1 coaching sales call', DATE '-infinity', DATE '2026-01-01'
   WHERE NOT EXISTS (
     SELECT 1 FROM acuity_appointment_type_map
      WHERE acuity_appointment_type_id = '64654501' AND valid_to = DATE '2026-01-01');

  -- 78497441 ("chat", deleted in Acuity): its nine 2025 bookings belong to
  -- the same pre-GYU 1:1 era as above — four of those people are literally
  -- the same humans as the unmatched 64654501 bookings. Its four 2026
  -- bookings are Living Example (Sam Milz, Milos Bojovic, Libby
  -- Sloan-O'Brien, Sigrid Kipper Thau all carry real 2026 LE/GYU records),
  -- so the same boundary applies.
  UPDATE acuity_appointment_type_map
     SET valid_from = DATE '2026-01-01',
         label = 'chat (2026 Living Example sales call)'
   WHERE acuity_appointment_type_id = '78497441'
     AND valid_from = DATE '-infinity';

  INSERT INTO acuity_appointment_type_map
    (acuity_appointment_type_id, offer_id, kind, is_current, label, valid_from, valid_to)
  SELECT '78497441', v_legacy, 'sales_call', false,
         'chat (pre-2026 1:1 coaching sales call)', DATE '-infinity', DATE '2026-01-01'
   WHERE NOT EXISTS (
     SELECT 1 FROM acuity_appointment_type_map
      WHERE acuity_appointment_type_id = '78497441' AND valid_to = DATE '2026-01-01');

  -- 91345095 (Mini Deep Dive) and 90522599 (Zoom 1:1) have only ever meant
  -- one thing: both first appear in 2026, after LE existed. They keep a
  -- single open period, which is the honest shape for a type with one era.
END $$;

-- ---------------------------------------------------------------------------
-- 5. Prove the mapping answers the questions this migration exists for.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  v_name text;
BEGIN
  -- A 2025 booking on the "GYU" type must NOT resolve to GYU.
  SELECT offer_name INTO v_name FROM resolve_acuity_appointment_type('64654501', DATE '2025-07-24');
  IF v_name IS DISTINCT FROM '1:1 Coaching (Legacy)' THEN
    RAISE EXCEPTION '2025 booking on 64654501 resolved to % (expected legacy 1:1)', v_name;
  END IF;

  -- A current booking on the same type must resolve to GYU.
  SELECT offer_name INTO v_name FROM resolve_acuity_appointment_type('64654501', DATE '2026-10-16');
  IF v_name IS DISTINCT FROM 'Growing Yourself Up' THEN
    RAISE EXCEPTION 'current booking on 64654501 resolved to % (expected GYU)', v_name;
  END IF;

  -- chat, both eras.
  SELECT offer_name INTO v_name FROM resolve_acuity_appointment_type('78497441', DATE '2025-05-21');
  IF v_name IS DISTINCT FROM '1:1 Coaching (Legacy)' THEN
    RAISE EXCEPTION '2025 chat resolved to % (expected legacy 1:1)', v_name;
  END IF;
  SELECT offer_name INTO v_name FROM resolve_acuity_appointment_type('78497441', DATE '2026-09-15');
  IF v_name IS DISTINCT FROM 'The Living Example' THEN
    RAISE EXCEPTION '2026 chat resolved to % (expected LE)', v_name;
  END IF;

  -- The single-era types keep working at any date.
  SELECT offer_name INTO v_name FROM resolve_acuity_appointment_type('91345095', DATE '2026-09-22');
  IF v_name IS DISTINCT FROM 'The Living Example' THEN
    RAISE EXCEPTION 'Mini Deep Dive resolved to %', v_name;
  END IF;

  -- At most one mapping may MATCH any (type, date) pair — the period
  -- predicate is the whole point, so the check applies it rather than just
  -- counting the periods a type has.
  IF EXISTS (
    SELECT 1
      FROM acuity_appointment_type_map m
      CROSS JOIN (VALUES (DATE '2024-06-01'), (DATE '2025-07-24'), (DATE '2026-01-01'),
                         (DATE '2026-10-16'), (DATE '2027-06-01')) d(day)
     WHERE d.day >= m.valid_from
       AND (m.valid_to IS NULL OR d.day < m.valid_to)
     GROUP BY m.acuity_appointment_type_id, d.day
    HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'more than one mapping matches some (type, date)';
  END IF;

  RAISE NOTICE 'temporal appointment-type resolution verified';
END $$;
