-- Create workspaces table for multi-tenancy
create table if not exists "public"."workspaces" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "slug" text not null unique,
    "settings" jsonb default '{}'::jsonb
);

alter table "public"."workspaces" enable row level security;

-- Add workspace_id to all entity tables
alter table "public"."companies" add column if not exists "workspace_id" bigint references workspaces(id) on delete cascade;
alter table "public"."contacts" add column if not exists "workspace_id" bigint references workspaces(id) on delete cascade;
alter table "public"."deals" add column if not exists "workspace_id" bigint references workspaces(id) on delete cascade;
alter table "public"."contactNotes" add column if not exists "workspace_id" bigint references workspaces(id) on delete cascade;
alter table "public"."dealNotes" add column if not exists "workspace_id" bigint references workspaces(id) on delete cascade;
alter table "public"."tasks" add column if not exists "workspace_id" bigint references workspaces(id) on delete cascade;
alter table "public"."tags" add column if not exists "workspace_id" bigint references workspaces(id) on delete cascade;
alter table "public"."sales" add column if not exists "workspace_id" bigint references workspaces(id) on delete cascade;

-- Create default workspace and migrate existing data
insert into "public"."workspaces" (name, slug)
values ('Default Workspace', 'default')
on conflict (slug) do nothing;

-- Migrate existing data to default workspace
update "public"."companies" set workspace_id = (select id from workspaces where slug = 'default') where workspace_id is null;
update "public"."contacts" set workspace_id = (select id from workspaces where slug = 'default') where workspace_id is null;
update "public"."deals" set workspace_id = (select id from workspaces where slug = 'default') where workspace_id is null;
update "public"."contactNotes" set workspace_id = (select id from workspaces where slug = 'default') where workspace_id is null;
update "public"."dealNotes" set workspace_id = (select id from workspaces where slug = 'default') where workspace_id is null;
update "public"."tasks" set workspace_id = (select id from workspaces where slug = 'default') where workspace_id is null;
update "public"."tags" set workspace_id = (select id from workspaces where slug = 'default') where workspace_id is null;
update "public"."sales" set workspace_id = (select id from workspaces where slug = 'default') where workspace_id is null;

-- Make workspace_id not null after migration
alter table "public"."companies" alter column "workspace_id" set not null;
alter table "public"."contacts" alter column "workspace_id" set not null;
alter table "public"."deals" alter column "workspace_id" set not null;
alter table "public"."contactNotes" alter column "workspace_id" set not null;
alter table "public"."dealNotes" alter column "workspace_id" set not null;
alter table "public"."tasks" alter column "workspace_id" set not null;
alter table "public"."tags" alter column "workspace_id" set not null;
alter table "public"."sales" alter column "workspace_id" set not null;

-- Create indexes for workspace_id
create index if not exists companies_workspace_id_idx on "public"."companies"(workspace_id);
create index if not exists contacts_workspace_id_idx on "public"."contacts"(workspace_id);
create index if not exists deals_workspace_id_idx on "public"."deals"(workspace_id);
create index if not exists contactNotes_workspace_id_idx on "public"."contactNotes"(workspace_id);
create index if not exists dealNotes_workspace_id_idx on "public"."dealNotes"(workspace_id);
create index if not exists tasks_workspace_id_idx on "public"."tasks"(workspace_id);
create index if not exists tags_workspace_id_idx on "public"."tags"(workspace_id);
create index if not exists sales_workspace_id_idx on "public"."sales"(workspace_id);

-- RLS policies for workspaces (admin only can create/manage workspaces)
create policy "Users can view their workspace"
  on workspaces for select
  using (
    id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

-- Update RLS policies for all tables to include workspace isolation
-- Companies
drop policy if exists "Users can view companies" on companies;
create policy "Users can view companies"
  on companies for select
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

drop policy if exists "Users can create companies" on companies;
create policy "Users can create companies"
  on companies for insert
  with check (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

drop policy if exists "Users can update companies" on companies;
create policy "Users can update companies"
  on companies for update
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

drop policy if exists "Users can delete companies" on companies;
create policy "Users can delete companies"
  on companies for delete
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

-- Contacts
drop policy if exists "Users can view contacts" on contacts;
create policy "Users can view contacts"
  on contacts for select
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

drop policy if exists "Users can create contacts" on contacts;
create policy "Users can create contacts"
  on contacts for insert
  with check (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

drop policy if exists "Users can update contacts" on contacts;
create policy "Users can update contacts"
  on contacts for update
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

drop policy if exists "Users can delete contacts" on contacts;
create policy "Users can delete contacts"
  on contacts for delete
  using (
    workspace_id in (
      select workspace_id from sales where user_id = auth.uid()
    )
  );

-- Similar policies for other tables...
-- (abbreviated for brevity, but would include deals, contactNotes, dealNotes, tasks, tags, sales)
