--
-- Domain fields for companies, contacts, deals and meetings (tasks), plus the
-- `choices` referential backing the user-extensible option lists.
--

-- Companies
alter table public.companies add column if not exists nb_sites integer;

-- Contacts
alter table public.contacts add column if not exists company_start_date date;
alter table public.contacts add column if not exists decision_role text;
alter table public.contacts add column if not exists relationship_status text;
alter table public.contacts add column if not exists linked_contact_ids bigint[];

-- Deals
alter table public.deals add column if not exists confidentiality text;
alter table public.deals add column if not exists reference text;
alter table public.deals add column if not exists origin text;
alter table public.deals add column if not exists motivation text;
alter table public.deals add column if not exists objectives text[];
alter table public.deals add column if not exists other_expectations text;

-- Tasks (meetings)
alter table public.tasks add column if not exists location text;
alter table public.tasks add column if not exists mode text;

-- Company headcount brackets moved from (1, 2-9, 10-49, 50-249, 250+) to
-- (<50, 50-100, 100-250, 250-500, +500). Values 1 and 10 both fall under 50.
update public.companies set size = 50 where size in (1, 10);

--
-- Choices: user-extensible option lists. Records store the label itself, so
-- removing a choice never orphans existing data.
--
create table if not exists public.choices (
    id bigint generated by default as identity primary key,
    category text not null,
    label text not null
);

create unique index if not exists uq__choices__category_label on public.choices using btree (category, label);

alter table public.choices enable row level security;

create policy "Enable read access for authenticated users" on public.choices for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.choices for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.choices for update to authenticated using (true) with check (true);
create policy "Choice Delete Policy" on public.choices for delete to authenticated using (true);

grant all on table public.choices to anon;
grant all on table public.choices to authenticated;
grant all on table public.choices to service_role;

grant all on sequence public.choices_id_seq to anon;
grant all on sequence public.choices_id_seq to authenticated;
grant all on sequence public.choices_id_seq to service_role;

insert into public.choices (category, label) values
    ('company_sector', 'Services de communication'),
    ('company_sector', 'Consommation discrétionnaire'),
    ('company_sector', 'Consommation de base'),
    ('company_sector', 'Énergie'),
    ('company_sector', 'Finance'),
    ('company_sector', 'Santé'),
    ('company_sector', 'Industrie'),
    ('company_sector', 'Technologies de l''information'),
    ('company_sector', 'Matériaux'),
    ('company_sector', 'Immobilier'),
    ('company_sector', 'Services aux collectivités'),
    ('deal_origin', 'Préventica'),
    ('deal_origin', 'Solutions CSE'),
    ('deal_origin', 'Site internet'),
    ('deal_origin', 'Prospection'),
    ('deal_origin', 'Linkedin'),
    ('deal_origin', 'Recommandation'),
    ('deal_origin', 'Partenaire'),
    ('deal_objective', 'Sensibiliser'),
    ('deal_objective', 'Former'),
    ('deal_objective', 'Structurer une démarche'),
    ('deal_objective', 'Réduire les RPS'),
    ('deal_objective', 'Accompagner les managers'),
    ('deal_objective', 'Répondre à une obligation'),
    ('rdv_mode', 'Présentiel'),
    ('rdv_mode', 'Visioconférence'),
    ('rdv_mode', 'Téléphone'),
    ('rdv_mode', 'Salon'),
    ('rdv_type', 'Premier contact'),
    ('rdv_type', 'Rendez-vous découverte'),
    ('rdv_type', 'Rendez-vous de suivi'),
    ('rdv_type', 'Restitution'),
    ('rdv_type', 'Bilan annuel'),
    ('rdv_type', 'Préparation d''une proposition'),
    ('rdv_type', 'Lancement de mission')
on conflict (category, label) do nothing;

-- Sectors moved from configuration slugs to the `choices` referential, which
-- stores the label itself. Translate the slugs already in the column.
update public.companies set sector = mapped.label
from (values
    ('communication-services', 'Services de communication'),
    ('consumer-discretionary', 'Consommation discrétionnaire'),
    ('consumer-staples', 'Consommation de base'),
    ('energy', 'Énergie'),
    ('financials', 'Finance'),
    ('health-care', 'Santé'),
    ('industrials', 'Industrie'),
    ('information-technology', 'Technologies de l''information'),
    ('materials', 'Matériaux'),
    ('real-estate', 'Immobilier'),
    ('utilities', 'Services aux collectivités')
) as mapped(slug, label)
where public.companies.sector = mapped.slug;

--
-- Summary views: new columns are inserted mid-list, so the views must be
-- dropped and recreated (CREATE OR REPLACE can only append columns).
--
drop view if exists public.companies_summary;
drop view if exists public.contacts_summary;

create view public.companies_summary with (security_invoker = on) as
select
    c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    c.nb_sites,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts
from public.companies c
    left join public.deals d on c.id = d.company_id
    left join public.contacts co on c.id = co.company_id
group by c.id;

create view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    co.company_start_date,
    co.decision_role,
    co.relationship_status,
    co.linked_contact_ids,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
    left join public.companies c on co.company_id = c.id
group by co.id, c.name;

grant all on table public.companies_summary to anon;
grant all on table public.companies_summary to authenticated;
grant all on table public.companies_summary to service_role;

grant all on table public.contacts_summary to anon;
grant all on table public.contacts_summary to authenticated;
grant all on table public.contacts_summary to service_role;
