-- Client + Session Operations: cadence exception state-machine fix.
--
-- Human acceptance found two real, related gaps in the cadence
-- correction (20260906060000/20260906070000): (1) a human classification
-- (Known skip / Rescheduled / Missed-ghosted) was permanently immutable
-- once set — Leif had no way to change or reopen a mistaken judgment;
-- (2) marking a fulfilling session No-show broke fulfillment but never
-- created/reactivated the corresponding cadence issue, leaving an inert,
-- non-actionable "Unresolved" display with no linked Task. This
-- migration adds the durable event history a real state machine needs;
-- the application-level logic (markClientSessionNoShow.ts,
-- reverseClientSessionNoShow.ts, setCadenceIssueClassification.ts,
-- reopenCadenceIssue.ts) is what actually drives the transitions — see
-- this slice's own report for the full reasoning on when an automated
-- caller may reopen/reactivate an issue versus when it must leave an
-- existing human classification untouched.

create table "public"."client_session_cadence_issue_events" (
    "id" bigint generated by default as identity primary key,
    "cadence_issue_id" bigint not null,
    "kind" text not null,
    "classification" text,
    "note" text,
    "occurred_at" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now(),
    constraint "client_session_cadence_issue_events_kind_check" check ((kind = any (array['created'::text, 'resolved'::text, 'reclassified'::text, 'reopened'::text]))),
    constraint "client_session_cadence_issue_events_classification_check" check ((classification is null or classification = any (array['known_skip'::text, 'rescheduled'::text, 'missed_ghosted'::text])))
);

create index "client_session_cadence_issue_events_issue_id_idx" on "public"."client_session_cadence_issue_events" using btree ("cadence_issue_id");

alter table "public"."client_session_cadence_issue_events" add constraint "client_session_cadence_issue_events_issue_id_fkey" foreign key ("cadence_issue_id") references "public"."client_session_cadence_issues"("id") on update cascade on delete cascade;

alter table "public"."client_session_cadence_issue_events" enable row level security;

create policy "Enable read access for authenticated users" on "public"."client_session_cadence_issue_events" for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."client_session_cadence_issue_events" for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."client_session_cadence_issue_events" for update to authenticated using (true) with check (true);
create policy "Client Session Cadence Issue Events Delete Policy" on "public"."client_session_cadence_issue_events" for delete to authenticated using (true);

grant all on table "public"."client_session_cadence_issue_events" to "anon";
grant all on table "public"."client_session_cadence_issue_events" to "authenticated";
grant all on table "public"."client_session_cadence_issue_events" to "service_role";

grant all on sequence "public"."client_session_cadence_issue_events_id_seq" to "anon";
grant all on sequence "public"."client_session_cadence_issue_events_id_seq" to "authenticated";
grant all on sequence "public"."client_session_cadence_issue_events_id_seq" to "service_role";
