-- ===========================================================================
-- Two domain gaps Leif's Round 2 acceptance exposed
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Agreed payment schedules
-- ---------------------------------------------------------------------------
-- deals already carries a commercial snapshot, but only an EQUAL-installment
-- one: selected_payment_total plus a count and a single per-payment amount.
-- That cannot express "$400 deposit now, $1,000 on January 1st" — unequal
-- amounts, specific due dates, and some already paid. The only way to record
-- such a client was to flatten it to a total and lose the arrangement.
--
-- This table is the AGREED SCHEDULE, deliberately not a ledger of financial
-- transactions. It is what was agreed and what is believed to have been
-- honoured, which is a different claim from "Stripe confirms this payment" —
-- see the status/paid_on/source columns below, which keep those apart rather
-- than collapsing them.
CREATE TABLE IF NOT EXISTS "public"."deal_payment_schedule_items" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "deal_id" bigint NOT NULL,
    "amount" numeric(10, 2) NOT NULL,
    -- Ordinal within the schedule, so "deposit then balance" keeps its order
    -- even when neither item has a due date.
    "sequence" smallint NOT NULL DEFAULT 1,
    -- Null when genuinely unknown. A historical deposit may be known to have
    -- been paid without anyone recording when it was due.
    "due_date" date,
    "status" text NOT NULL DEFAULT 'scheduled',
    -- Null when the payment is known to have happened but the date is not.
    -- Never back-filled with a placeholder to satisfy a NOT NULL, which is
    -- exactly how invented dates get mistaken for evidence later.
    "paid_on" date,
    -- How we know. 'owner_stated' is Leif telling us; 'stripe' means a
    -- verified external transaction, and only the Stripe integration may
    -- ever write it. The distinction is the whole reason this column exists:
    -- a schedule may truthfully say "$400 — Paid" on Leif's word without
    -- claiming Stripe confirms it.
    "source" text NOT NULL DEFAULT 'owner_stated',
    "stripe_payment_intent_id" text,
    "notes" text,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "deal_payment_schedule_items_amount_check" CHECK (amount > 0),
    CONSTRAINT "deal_payment_schedule_items_status_check"
      CHECK (status IN ('scheduled', 'paid', 'void')),
    CONSTRAINT "deal_payment_schedule_items_source_check"
      CHECK (source IN ('owner_stated', 'stripe', 'historical_import')),
    -- A paid item must not carry a Stripe id unless it says it came from
    -- Stripe, and a Stripe-sourced item must carry one. This is what stops
    -- "paid on Leif's word" from drifting into "paid, per Stripe".
    CONSTRAINT "deal_payment_schedule_items_stripe_provenance_check"
      CHECK (
        (source = 'stripe' AND stripe_payment_intent_id IS NOT NULL)
        OR (source <> 'stripe' AND stripe_payment_intent_id IS NULL)
      ),
    -- Only a paid item can have a paid date.
    CONSTRAINT "deal_payment_schedule_items_paid_on_check"
      CHECK (status = 'paid' OR paid_on IS NULL),
    UNIQUE ("deal_id", "sequence")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'deal_payment_schedule_items_deal_id_fkey') THEN
    ALTER TABLE "public"."deal_payment_schedule_items"
      ADD CONSTRAINT "deal_payment_schedule_items_deal_id_fkey"
      FOREIGN KEY ("deal_id") REFERENCES "public"."deals"("id") ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "deal_payment_schedule_items_deal_id_idx"
  ON "public"."deal_payment_schedule_items" USING btree ("deal_id");

ALTER TABLE "public"."deal_payment_schedule_items" ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'deal_payment_schedule_items' AND policyname = 'Enable read access for authenticated users') THEN
    CREATE POLICY "Enable read access for authenticated users" ON "public"."deal_payment_schedule_items" FOR SELECT TO authenticated USING (true);
    CREATE POLICY "Enable insert for authenticated users only" ON "public"."deal_payment_schedule_items" FOR INSERT TO authenticated WITH CHECK (true);
    CREATE POLICY "Enable update for authenticated users only" ON "public"."deal_payment_schedule_items" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Deal Payment Schedule Items Delete Policy" ON "public"."deal_payment_schedule_items" FOR DELETE TO authenticated USING (true);
  END IF;
END $$;

GRANT ALL ON TABLE "public"."deal_payment_schedule_items" TO authenticated;
GRANT ALL ON TABLE "public"."deal_payment_schedule_items" TO service_role;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."deal_payment_schedule_items" FROM anon;

-- ---------------------------------------------------------------------------
-- 2. The legacy 1:1 Offer
-- ---------------------------------------------------------------------------
-- Leif did one-to-one work with people before either current Offer existed.
-- Those clients were imported onto Growing Yourself Up because deals.offer_id
-- is NOT NULL and there was nothing truthful to point them at — so the CRM
-- asserted they were in a group programme that did not exist yet.
--
-- This Offer is that missing truth, and it is inactive: offers.is_active
-- already existed for exactly this ("an Offer that is no longer sold"), and
-- the app now honours it by keeping inactive Offers out of every
-- new-business picker while still resolving them everywhere history is
-- displayed. The NOT NULL invariant on deals.offer_id is untouched.
--
-- current_price is 0 because this Offer is not for sale at any price. It is
-- never displayed as a client's terms: the Client page shows
-- selected_payment_total when it is known and says the terms were not
-- recorded when it is not — which is the honest state for these clients.
INSERT INTO "public"."offers" ("name", "type", "duration", "current_price", "is_active", "max_active_clients")
SELECT '1:1 Coaching (Legacy)', 'individual', 'Varies (historical)', 0, false, NULL
WHERE NOT EXISTS (
  SELECT 1 FROM "public"."offers" WHERE "name" = '1:1 Coaching (Legacy)'
);
