-- Client + Session Operations slice A: LE Session Ledger + Client
-- Operational View. See supabase/schemas/01_tables.sql for the full
-- rationale comments (this migration mirrors that declarative schema).

alter table public.offers
    add column client_session_acuity_appointment_type_id text;

create unique index offers_client_session_acuity_appointment_type_id_idx on public.offers (client_session_acuity_appointment_type_id) where (client_session_acuity_appointment_type_id is not null);

create table public.client_sessions (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    enrollment_id bigint,
    offer_id bigint not null,
    status text not null default 'booked',
    scheduled_at timestamp with time zone not null,
    reschedule_count smallint not null default 0,
    last_rescheduled_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    completed_at timestamp with time zone,
    source text not null default 'manual',
    acuity_appointment_id text,
    acuity_appointment_type_id text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint client_sessions_status_check check (status in ('booked', 'cancelled', 'completed')),
    constraint client_sessions_source_check check (source in ('acuity', 'manual'))
);

create unique index client_sessions_acuity_appointment_id_idx on public.client_sessions (acuity_appointment_id) where (acuity_appointment_id is not null);
create index client_sessions_contact_id_idx on public.client_sessions using btree (contact_id);
create index client_sessions_enrollment_id_idx on public.client_sessions using btree (enrollment_id);
create index client_sessions_offer_id_idx on public.client_sessions using btree (offer_id);

create table public.client_session_events (
    id bigint generated by default as identity primary key,
    client_session_id bigint not null,
    kind text not null,
    occurred_at timestamp with time zone not null default now(),
    previous_scheduled_at timestamp with time zone,
    new_scheduled_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint client_session_events_kind_check check (kind in ('booked', 'rescheduled', 'cancelled', 'completed', 'reopened'))
);

create index client_session_events_client_session_id_idx on public.client_session_events using btree (client_session_id);

alter table public.client_sessions
    add constraint client_sessions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.client_sessions
    add constraint client_sessions_enrollment_id_fkey foreign key (enrollment_id) references public.enrollments(id) on update cascade on delete set null;

alter table public.client_sessions
    add constraint client_sessions_offer_id_fkey foreign key (offer_id) references public.offers(id) on update cascade on delete cascade;

alter table public.client_session_events
    add constraint client_session_events_client_session_id_fkey foreign key (client_session_id) references public.client_sessions(id) on update cascade on delete cascade;

alter table public.client_sessions enable row level security;
alter table public.client_session_events enable row level security;

create policy "Enable read access for authenticated users" on public.client_sessions for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.client_sessions for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.client_sessions for update to authenticated using (true) with check (true);
create policy "Client Sessions Delete Policy" on public.client_sessions for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.client_session_events for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.client_session_events for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.client_session_events for update to authenticated using (true) with check (true);
create policy "Client Session Events Delete Policy" on public.client_session_events for delete to authenticated using (true);

grant all on table public.client_sessions to anon;
grant all on table public.client_sessions to authenticated;
grant all on table public.client_sessions to service_role;

grant all on table public.client_session_events to anon;
grant all on table public.client_session_events to authenticated;
grant all on table public.client_session_events to service_role;

grant all on sequence public.client_sessions_id_seq to anon;
grant all on sequence public.client_sessions_id_seq to authenticated;
grant all on sequence public.client_sessions_id_seq to service_role;

grant all on sequence public.client_session_events_id_seq to anon;
grant all on sequence public.client_session_events_id_seq to authenticated;
grant all on sequence public.client_session_events_id_seq to service_role;
