-- Migration: Create feedback_items table for in-app feedback inbox ("chatt-widget")
-- Created: 2026-06-08
-- Description: Shared team inbox where logged-in users log feedback about the CRM
--              itself (what works, bugs, feature requests) directly while working.
--              Acts as a single source of truth that can be read and acted upon.

CREATE TABLE IF NOT EXISTS "public"."feedback_items" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "text" text NOT NULL,
  -- category: 'works' (funkar bra), 'bug' (funkar inte), 'request' (förslag/saknas)
  "category" text NOT NULL CHECK (category IN ('works', 'bug', 'request')),
  -- status: 'open' (ej åtgärdad) eller 'done' (klar)
  "status" text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done')),
  -- page_context: window.location.pathname vid skapande, så vi vet var feedbacken gäller
  "page_context" text,
  -- sales_id fylls automatiskt av trigger nedan (set_sales_id_default), ej av frontend
  "sales_id" bigint REFERENCES sales(id) ON DELETE SET NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE "public"."feedback_items" ENABLE ROW LEVEL SECURITY;

-- RLS Policies — delad teaminkorg: alla inloggade får läsa/skriva/uppdatera.
-- Ingen DELETE-policy: feedback raderas inte, den markeras som 'done'.
CREATE POLICY "Authenticated can view feedback" ON "public"."feedback_items"
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can insert feedback" ON "public"."feedback_items"
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update feedback" ON "public"."feedback_items"
  FOR UPDATE
  USING (auth.role() = 'authenticated');

-- Återanvänder den befintliga set_sales_id_default()-funktionen
-- (se 20260108160722_task_default_sales.sql) så frontend slipper skicka sales_id.
CREATE TRIGGER set_feedback_items_sales_id_trigger
BEFORE INSERT ON "public"."feedback_items"
FOR EACH ROW
EXECUTE FUNCTION set_sales_id_default();

-- Indexes
CREATE INDEX idx_feedback_items_created_at ON feedback_items(created_at DESC);
CREATE INDEX idx_feedback_items_status ON feedback_items(status);
CREATE INDEX idx_feedback_items_sales_id ON feedback_items(sales_id);
