
  create table "public"."company_machines" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "company_id" bigint not null,
    "product_id" bigint not null,
    "serial_number" text,
    "purchase_date" date,
    "deal_id" bigint,
    "notes" text
      );


alter table "public"."company_machines" enable row level security;


  create table "public"."deal_products" (
    "id" bigint generated by default as identity not null,
    "deal_id" bigint not null,
    "product_id" bigint not null,
    "quantity" smallint not null default 1,
    "unit_price" bigint
      );


alter table "public"."deal_products" enable row level security;


  create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "reference" text not null,
    "name" text not null,
    "type" text,
    "price" bigint,
    "description" text,
    "active" boolean not null default true,
    "sales_id" bigint
      );


alter table "public"."products" enable row level security;


  create table "public"."service_contracts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "company_id" bigint,
    "contact_ids" bigint[],
    "deal_id" bigint,
    "machine_ids" bigint[],
    "start_date" date not null,
    "renewal_date" date not null,
    "amount" bigint,
    "notes" text,
    "status" text not null default 'actif'::text,
    "sales_id" bigint
      );


alter table "public"."service_contracts" enable row level security;

CREATE INDEX company_machines_company_id_idx ON public.company_machines USING btree (company_id);

CREATE UNIQUE INDEX company_machines_pkey ON public.company_machines USING btree (id);

CREATE INDEX deal_products_deal_id_idx ON public.deal_products USING btree (deal_id);

CREATE UNIQUE INDEX deal_products_pkey ON public.deal_products USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE INDEX service_contracts_company_id_idx ON public.service_contracts USING btree (company_id);

CREATE UNIQUE INDEX service_contracts_pkey ON public.service_contracts USING btree (id);

CREATE INDEX service_contracts_renewal_date_idx ON public.service_contracts USING btree (renewal_date);

alter table "public"."company_machines" add constraint "company_machines_pkey" PRIMARY KEY using index "company_machines_pkey";

alter table "public"."deal_products" add constraint "deal_products_pkey" PRIMARY KEY using index "deal_products_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."service_contracts" add constraint "service_contracts_pkey" PRIMARY KEY using index "service_contracts_pkey";

alter table "public"."company_machines" add constraint "company_machines_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE not valid;

alter table "public"."company_machines" validate constraint "company_machines_company_id_fkey";

alter table "public"."company_machines" add constraint "company_machines_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES public.deals(id) not valid;

alter table "public"."company_machines" validate constraint "company_machines_deal_id_fkey";

alter table "public"."company_machines" add constraint "company_machines_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."company_machines" validate constraint "company_machines_product_id_fkey";

alter table "public"."deal_products" add constraint "deal_products_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE not valid;

alter table "public"."deal_products" validate constraint "deal_products_deal_id_fkey";

alter table "public"."deal_products" add constraint "deal_products_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."deal_products" validate constraint "deal_products_product_id_fkey";

alter table "public"."products" add constraint "products_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."products" validate constraint "products_sales_id_fkey";

alter table "public"."service_contracts" add constraint "service_contracts_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE not valid;

alter table "public"."service_contracts" validate constraint "service_contracts_company_id_fkey";

alter table "public"."service_contracts" add constraint "service_contracts_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES public.deals(id) not valid;

alter table "public"."service_contracts" validate constraint "service_contracts_deal_id_fkey";

alter table "public"."service_contracts" add constraint "service_contracts_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."service_contracts" validate constraint "service_contracts_sales_id_fkey";

create or replace view "public"."service_contracts_with_machines" as  SELECT sc.id,
    sc.created_at,
    sc.name,
    sc.company_id,
    sc.contact_ids,
    sc.deal_id,
    sc.machine_ids,
    sc.start_date,
    sc.renewal_date,
    sc.amount,
    sc.notes,
    sc.status,
    sc.sales_id,
    COALESCE(( SELECT json_agg(json_build_object('id', cm.id, 'product_id', cm.product_id, 'serial_number', cm.serial_number, 'purchase_date', cm.purchase_date, 'product_name', p.name, 'product_reference', p.reference)) AS json_agg
           FROM (public.company_machines cm
             JOIN public.products p ON ((p.id = cm.product_id)))
          WHERE (cm.id = ANY (sc.machine_ids))), '[]'::json) AS machines
   FROM public.service_contracts sc;


grant delete on table "public"."company_machines" to "anon";

grant insert on table "public"."company_machines" to "anon";

grant references on table "public"."company_machines" to "anon";

grant select on table "public"."company_machines" to "anon";

grant trigger on table "public"."company_machines" to "anon";

grant truncate on table "public"."company_machines" to "anon";

grant update on table "public"."company_machines" to "anon";

grant delete on table "public"."company_machines" to "authenticated";

grant insert on table "public"."company_machines" to "authenticated";

grant references on table "public"."company_machines" to "authenticated";

grant select on table "public"."company_machines" to "authenticated";

grant trigger on table "public"."company_machines" to "authenticated";

grant truncate on table "public"."company_machines" to "authenticated";

grant update on table "public"."company_machines" to "authenticated";

grant delete on table "public"."company_machines" to "service_role";

grant insert on table "public"."company_machines" to "service_role";

grant references on table "public"."company_machines" to "service_role";

grant select on table "public"."company_machines" to "service_role";

grant trigger on table "public"."company_machines" to "service_role";

grant truncate on table "public"."company_machines" to "service_role";

grant update on table "public"."company_machines" to "service_role";

grant delete on table "public"."deal_products" to "anon";

grant insert on table "public"."deal_products" to "anon";

grant references on table "public"."deal_products" to "anon";

grant select on table "public"."deal_products" to "anon";

grant trigger on table "public"."deal_products" to "anon";

grant truncate on table "public"."deal_products" to "anon";

grant update on table "public"."deal_products" to "anon";

grant delete on table "public"."deal_products" to "authenticated";

grant insert on table "public"."deal_products" to "authenticated";

grant references on table "public"."deal_products" to "authenticated";

grant select on table "public"."deal_products" to "authenticated";

grant trigger on table "public"."deal_products" to "authenticated";

grant truncate on table "public"."deal_products" to "authenticated";

grant update on table "public"."deal_products" to "authenticated";

grant delete on table "public"."deal_products" to "service_role";

grant insert on table "public"."deal_products" to "service_role";

grant references on table "public"."deal_products" to "service_role";

grant select on table "public"."deal_products" to "service_role";

grant trigger on table "public"."deal_products" to "service_role";

grant truncate on table "public"."deal_products" to "service_role";

grant update on table "public"."deal_products" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."service_contracts" to "anon";

grant insert on table "public"."service_contracts" to "anon";

grant references on table "public"."service_contracts" to "anon";

grant select on table "public"."service_contracts" to "anon";

grant trigger on table "public"."service_contracts" to "anon";

grant truncate on table "public"."service_contracts" to "anon";

grant update on table "public"."service_contracts" to "anon";

grant delete on table "public"."service_contracts" to "authenticated";

grant insert on table "public"."service_contracts" to "authenticated";

grant references on table "public"."service_contracts" to "authenticated";

grant select on table "public"."service_contracts" to "authenticated";

grant trigger on table "public"."service_contracts" to "authenticated";

grant truncate on table "public"."service_contracts" to "authenticated";

grant update on table "public"."service_contracts" to "authenticated";

grant delete on table "public"."service_contracts" to "service_role";

grant insert on table "public"."service_contracts" to "service_role";

grant references on table "public"."service_contracts" to "service_role";

grant select on table "public"."service_contracts" to "service_role";

grant trigger on table "public"."service_contracts" to "service_role";

grant truncate on table "public"."service_contracts" to "service_role";

grant update on table "public"."service_contracts" to "service_role";


  create policy "Company Machines Delete Policy"
  on "public"."company_machines"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."company_machines"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."company_machines"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."company_machines"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Deal Products Delete Policy"
  on "public"."deal_products"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."deal_products"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."deal_products"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."deal_products"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable insert for authenticated users only"
  on "public"."products"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."products"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."products"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Products Delete Policy"
  on "public"."products"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."service_contracts"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."service_contracts"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."service_contracts"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Service Contracts Delete Policy"
  on "public"."service_contracts"
  as permissive
  for delete
  to authenticated
using (true);


CREATE TRIGGER set_product_sales_id_trigger BEFORE INSERT ON public.products FOR EACH ROW EXECUTE FUNCTION public.set_sales_id_default();

CREATE TRIGGER set_service_contract_sales_id_trigger BEFORE INSERT ON public.service_contracts FOR EACH ROW EXECUTE FUNCTION public.set_sales_id_default();


